### ISSUE TITLE
Time System

### ISSUE THREAD

**Issue by ManavTriv** [UQcsse3200/2023-studio-1#10]
# **Description**
The in-game time system will be a clock that runs and is constantly displayed on the screen, when the user is playing the game. It displays the current time and provides an indication of whether it is currently day or night and allows 
player to gauge the growth rate of plants. The internal game time is controlled by the class `GameTime` however this will need to be extended so that the time can be converted to a time of day (eg. 12pm). A time scale also needs to be decided (e. A whole day in the game is 12 mins in real life). The clock and day-night indicator UI will always be on the screen be updated based on the current in-game time. 

Furthermore the implementation will need to follow an observer pattern. There will be entities such as plants that are dependent on the time (eg. plants need to know if time has pass so they can update and grow). Therefore entities will need to be stored so that the time system class can notify these entities to update.

Additional features such as a pause functionality will also need to be implemented.

## SubFeature/component
- Time Controller - `TimeController` will be the observable and control the updates that are sent to entities that are dependent on the time. It will also need to contain the logic to determine the actual in game time so that it can update `GameTimeDisplay` with the current hour of the game. This class will extend from `GameTime` service, and will be heavily dependent on it, as it will receive the current real time of the game in milliseconds from it using `getTime()` which will then be converted to the in game time.
- Game Time Display - `GameTimeDisplay` will be the UI implementation of the clock design and day-night indicator and will be an observer to `TimeController`. When it recieves a notification from `TimeController` with the current hour of the game, then it will know to update the UI to match that hour.
- Clock Display - A digital clock that visually displays the time (12 hr clock with am and pm) to the player in a visually appealing but readable way. 
- Day-Night Indicator - A visual display that dynamically updates to represent whether the time is currently day or night

### SubFeature/component Task Tickets
- https://github.com/UQcsse3200/2023-studio-1/issues/41
- https://github.com/UQcsse3200/2023-studio-1/issues/69
- https://github.com/UQcsse3200/2023-studio-1/issues/71
- https://github.com/UQcsse3200/2023-studio-1/issues/102

## Examples
- The clock says the time is 8:30pm, then the day-night indicator will display a moon to indicate that it is night
- Day-Night Indicator changes from a sun to a moon when the time changes from 5pm to 6pm

# **Dependencies**
This feature will be heavily dependent on the `GameTime` service. There will be no other major dependencies, rather other features will be dependent on the `TimeController` class. 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Goal 1 (Aug. 20): Collaborate with the design committee to create the visual design of the clock interface, which matches the aesthetic of the game as well as being readable
- [x] Goal 2 (Aug. 21): Collaborate with the design committee to create the visual design of the day-night indicator
- [x] Goal 3 (Aug. 24): Development team to work on the `GameTimeDisplay` class to implement the UI display in the game, including the clock interface and day-night indicator
- [x] Goal 4 (Aug. 27): Development team to implement the observable class `TimeController` and register the observers within. The logic of calculating the in-game time will need to be implemented so that `GameTimeDisplay` can update
- [x] Goal 5 (Aug. 28): Implement additional features in `TimeController`
- [x] Goal 6 (Aug. 29): Finalise testing and debugging of the classes as well as the UI to ensure it functions as intended

**Completion Deadline:** Aug. 29

# **Extras**
- [ ] Add an in-game calendar 
- [ ] Add a random event where clouds appear on the clock display 

# **Documentation**
- [Time System](https://github.com/UQcsse3200/2023-studio-1/wiki/Time-System)
- [Art Influences](https://github.com/UQcsse3200/2023-studio-1/wiki/Art-Influences)
- [UI](https://github.com/UQcsse3200/2023-studio-1/wiki/UI)

# **Members**
- Gil Wise (@gilgilgilgilgil) (Gil)
- Manav Trivedi (@ManavTriv) (Manav Trivedi)
- Daniel Cottrell (@daniel-cottrell) (Daniel Cottrell)
- Matilda Damman (@MatildaDamman) (Matilda Damman)
- Arjun Singh (@arj-sng) (Arjun Singh)
