### ISSUE TITLE
Time System Revamp

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#102]
# **Description**
**Task:** Time System Revamp
**Feature:** Time System - #10 

This task if for a new version of the time system which is more flexible, reduces coupling significantly and allows for the integration of time and other entities.
 
- A new `TimeService` class which is responsible for keeping track of the in-game time and letting other entities know of any time changes.

At the moment, the current implementation of `TimeController`, `GameTimeDisplay` and `GameTime` introduces significant coupling and is not flexible for future features. To improve on this time system, a different approach is suggested. In the new system, the `TimeService` class is responsible for keeping track of the in-game time. It will only use the `GameTime` class to calculate the passing of time in the real world. From this the `TimeService` class will calculate the hour and day of the in-game time. Additionally, entities will be able to register themselves for in-game hourly and daily event triggers. This significantly decouples the system and reduces unnecessary processing (eg: `GameTimeDisplay` only updates when the hour changes, and not every time a frame is rendered).
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Complete initial design of new time system
- [x] Implement functionality to register entities to receive hourly and daily updates
- [x] Implement calculation of hour and days using `GameTime`
- [x] Complete implementation of this revamp
- [ ] Discuss changes with team 5 and merge PR
- [ ] Complete relevant wiki sections for this time service

**Completion Deadline:** Middle of sprint 2
 
# **Documentation**
- https://github.com/UQcsse3200/2023-studio-1/wiki/Time-System
 
# **Member**
- Lucas Hicks (@lucashicks1 ) (Lucas Hicks)
- Manav Trivedi (@ManavTriv) (Manav Trivedi)
