### ISSUE TITLE
Map Generation

### ISSUE THREAD

**Issue by HunterWhitty** [UQcsse3200/2023-studio-1#11]
# **Description**
This ticket is for the game's map generation. The map for this game will be pre-defined for the Minimal Viable Product (MVP) but may eventually include the addition of other pre-defined maps or a procedural generation system. A map entity will contain the tile entities which will be displayed on the game map. The map entity will use the Terrain Factory component, further utilizing the TerrainComponent and TerrainTile components. 

The map will be small in scale, but the exact size will have to be determined by the design committee. Factors for this decision should include the size of tiles and the speed at which a player character can traverse the entire length of the map.

## SubFeature/component
- [x] Map Data structure - How the map date is stored behind the scenes.
- [x] Map Generate - Determine the map to be used for the current playthrough (select a pre-defined map or procedurally generate a map) and create a way to store this information and methods to access this information.
- [x] Map Display - Display the grid tiles and the terrain in the game grid according to the information stored in the map entity.

## **Examples (optional)**
-  When a new game is created, the player should load into a game where the map is displayed
- The map should update (be re-drawn) when needed to display new information (player changes the state of a tile by placing a plant etc.)

# **Dependencies**
- Team 7 #8  We need to communicate with Team 7 so that we can determine the types of Tiles to be expected and the tiles that need to be included in map generation/pre-defined maps at the start of the game. We also need to communicate how the information for the tile sprites and graphical representation is assigned and stored.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Goal 1 (Aug. 17) - Communicate with Team 7 to determine how we will work together to get the tile and map system to display the tiles.
- [x] Goal 2 (Aug 23) - Modify the TerrainTile java class
	- [x] Create files for tile graphics
	- [x] Getter and setter methods for properties
- [x] Goal 3 (Aug. 25) - Create a map object with class constants and methods by extending TiledMap and the objects associated with it if necessary (TiledMapTileSets, TileMapTileSet, TiledMapTile (implemented as TerrainTile)).
	- [x] Class Constants (length, width)
	- [x] Getter and Setter methods for tiles
	- [x] Load pre-defined map sets into a data structure (read text file)
- [x] Goal 4 (Aug. 27) - Draw and re-draw methods for map within TerrainFactory class
	- [x] Create pre-defined map/s

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] Minimap for map
- [ ] Procedural Generation

# **Documentation**
- [Terrain (from the wiki)](../wiki/Terrain)
- [Game Areas (from the wiki)](../wiki/Game-Areas)
- more to be added

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- Hunter (HunterWhitty) (Hunter Whitlock)
- Riley (RileyWhitty) (Riley Whitlock)
- Angus (AngusWhittaker) (Angus Whittaker)
- Nathaniel (Radius-XT)
- Thang (thanghoang7020202) (Cao Quoc Thang Hoang)
