### ISSUE TITLE
Tool art and animations

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#12]
# **Adding art for tools and using them**
**Task:** Tool Art.
**Feature:** #7 adding-farm-tools-enchancement

Make art for the tools, this includes: inventory sprites and animations for when they are being used, this will be 4 directional animations to match the walk cycles. Should help give visual feedback to the user on what they are doing and where they are interacting with. Documentation will also be made to highlight key choices made.

# **Dependencies**
- [x] Need player model (at least idle stance) prior to starting animations #14 
 
# **Milestones**
- [x] Step 1 (Aug. 17) - Basic inventory sprites to be made 
- - [x] Hoe
- - [x] Shovel
- - [x] Watering Can
- - [x] Sickle

- [x] Step 2 (Aug. 22) - Blocking of animations to be completed
- - [x] Hoe
- - [x] Shovel
- - [x] Watering Can
- - [x] Sickle
- [x] Step 3 (Aug. 27) - Full animations to be completed
- - [x] Hoe
- - [x] Shovel
- - [x] Watering Can
- - [x] Sickle
 
**Completion Deadline:** Aug. 28

 
# **Documentation**
 
# **Member**
- Jackson Trenerry (@JTrenerry )

**Comment by JTrenerry** [comment]
![image](https://github.com/UQcsse3200/2023-studio-1/assets/105094182/820a186c-3264-45d2-ad95-6172bba5860d)

Inventory sprites

**Comment by JTrenerry** [comment]
Base player model took a bit longer than expected so deadlines will be pushed back to match this.
Changes:
* 25th for blocking animations out. 
The rest will remain the same.

**Comment by JTrenerry** [comment]
All done as per the commit above.
