### ISSUE TITLE
Load / Save game and TRAKTOR™

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#125]
# **Description**
Allow the player to save / load save files in order to keep their progress. This will work by serializing the needed variables to a .json file and then de serializing on load using a new class called GameState.

## SubFeature/component
Finishing off tasks from last sprint:
- [x] Add in player animations for tool use.

Sprint 2:
- [x] Save feature - Saves the game into a json file correctly
- [x] Load feature - Loads the game into a json file correctly
- [x] TRACTOR - Interactions on tiles (pending work done by map team and speed of Save/Load)

# **Milestones**
- [x] Goal 1 (Sept. 1) - Tool Animations triggered
- [x] Goal 2 (Sept. 12) - Save / Load game completed
- [x] Goal 3 (Sept. 12) - Tractor (Somewhat optional)

**Completion Deadline:** Sept. 12

# **Documentation**
https://github.com/UQcsse3200/2023-studio-1/wiki/Save---Load-game
https://github.com/UQcsse3200/2023-studio-1/wiki/Tractor

# **Members**
Shanon Lakshan Chandrasekara (@86LAK)
Jackson Trenerry (@JTrenerry)
Peter Lahanas (@p-lahanas)
Cohen Porteous (@cmp6)
Liam Anderson (@LiamAnd)

**Comment by 86LAK** [comment]
Fixed name

**Comment by 86LAK** [comment]
I Think We are Ready For PR my friends
