### ISSUE TITLE
Base Tool factory

### ISSUE THREAD

**Issue by cmp6** [UQcsse3200/2023-studio-1#13]
# **Base Tool implementation - TICKET-WIP**
**Task:** [Task Name](#3)
**Feature:** [Adding Farm Tools Enhancement](https://github.com/UQcsse3200/2023-studio-1/issues/7#issue-1848380260)

The basic tool entity that contains all necessary components from which other, more fleshed out tools can build upon.
 
## **Example**
- All tools in the game will rely on a base set of components to function, the basicTool entity supplies these while allowing easy extensibility through the 'Factory' design pattern.

# **Dependencies**
- [x] #15 

# **Milestones**
- [x] identify necessary components (Aug. 17)
- [x] modify/create components (Aug. 18)
- [ ] add components (Aug. 19)
- [ ] test (Aug. 22)
 
**Completion Deadline:** Aug. 22
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Members**
- Cohen Porteous (cmp6) (cmp1)
- Peter Lahanas (p-lahanas) (pete0827)

**Comment by 86LAK** [comment]
closing this ticket as is completed and  specific tool work will be continued in #51 for the implementation of specific tools
