### ISSUE TITLE
Refinement and enrichment of plant functionality

### ISSUE THREAD

**Issue by tomedwa** [UQcsse3200/2023-studio-1#130]
# **Description**
This feature ticket is designed to enrich the plants, to refine and clean up the functionality between other teams' work as well. This will be done by implementing more detailed non-functional aspects, such as; descriptions, audio, and animation, and functional aspects, such as; growth stages, harvesting (dropping items), and effects on the player. These details will complete basic plant functionality and permit a playable game.

# **Dependencies**
- [x] Time
- [x] Items

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x]  [Establish growth stages for plants (Sep. 10) ] (https://github.com/UQcsse3200/2023-studio-1/issues/163#event-10267832110)
    - [x] Growth stage updates once per (in game) day (Sep. 5)
    - [x] Plant texture changes when the plant enters a new growth stage (Sep. 10)
- [x] Implement plant harvesting functionality (Sep. 12)
    - [x] Create items that are dropped when harvested (Sep. 12)
    - [x] Handle harvesting at different growth stages (Sep. 12)
- [x] Plant descriptions and audio files  (Sep. 12)
- [x] Updated tests:
    - [x] PlantComponent (Sep. 12)
- [x] Update Wiki with all new changes (Sep. 12)

**Completion Deadline:** Sep. 12

# **Extras (optional)**
- [ ] Entry level achievements relating to plants 

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
- Connor (@Quarter-645) (Connor Morrison)
- Tom (@tomedwa) (Tom Edwards)
- Aadya @abhat0 (Aadya)
- Sanchit (@Sanchitjain16) (Sanchit Jain)
- Zebb (@ZebbMcAteer) (Zebb)
- Codie (@kodee-koder) (Codie Chung)

**Comment by JTrenerry** [comment]
Hey
1)  spelling mistake on your 2nd milestone
2) Can you please implement planting seeds, I will personally help you (it should be really easy and the code is almost done same for your drops when harvested)

**Comment by JTrenerry** [comment]
red
