### ISSUE TITLE
Plant descriptions and audio files

### ISSUE THREAD

**Issue by Quarter-645** [UQcsse3200/2023-studio-1#131]
# **Description**
**Task:** Plant descriptions and audio files
**Feature:** [Feature which this tasks contributes to implementing](#130)

This task will implement more detailed plant descriptions and well as audio files that will be used to help improve immersion into the story. This will be done by adding voice lines, ambient audio, and comprehensive canon plant descriptions into the game. The audio will be implemented as per the wiki states and the descriptions will be put into the plant.json file.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Write up descriptions (Sep. 06)
- [x] Get regular audio files (Sep. 07)
- [x] Record voice lines (Sep. 07)
- [x] Recheck descriptions (Sep. 10)
- [x] Implement audio files to play on certain actions, harvesting, attacking, being planted, walking past etc. (Sep. 11)
 
**Completion Deadline:** Sep. 12
 
# **Documentation**
- Javadoc
- [Plant Properties and Types](/wiki/Plant-Properties-and-Types)

# **Members**
Connor (@Quarter-645) (Connor Morrison)
Aadya (@abhat0) (Aadya Bhatia)

**Comment by Quarter-645** [comment]
Donezo, (was done earlier than this but forgot to close!)
