### ISSUE TITLE
Plant Harvesting

### ISSUE THREAD

**Issue by zmacca** [UQcsse3200/2023-studio-1#132]
# **Description**
**Task:** Implementing harvesting functionality for plants
**Feature:** [Refinement and enrichment or plant functionality](#130)

One primary purpose for growing plants is to harvest the produce that they create once they reach maturity. This task will implement a flexible system for harvesting plants that allows for customisable selection of harvestable items per plant. When the player harvests a plant, it will check whether it is in a harvestable state and, if so, drop its harvestable items on the ground for the player to pick up. Some plants may be destroyed when harvested (think of carrots), in which case the plant will handle its own destruction.

# **Dependencies**
Most dependencies for this task have already been implemented, namely items and the plant component. Discussion with the team in charge of the player will need to be had to determine how the player would interact with plants.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design a flexible system for setting harvestable items (Sep. 4)
- [x] Implement the design system above (Sep. 5)
- [ ] Create some basic items that can be dropped by harvested plants (Sep. 8)
 
**Completion Deadline:** Sep. 12
 
# **Documentation**
- [Plant component](/wiki/Plant-Component)
 
# **Member**
- Zebb McAteer (@ZebbMcAteer ) (.mrlegume)
- Connor Morrison (@Quarter-645) (quarterpastgametime)
