### ISSUE TITLE
Updating player animation frames

### ISSUE THREAD

**Issue by vilnor** [UQcsse3200/2023-studio-1#133]
# **Description**
The current player animations (using tools, moving, interacting, idling) have inconsistent frame sizes. Because there is no way to set an anchor point for the sprites, this causes some animations to make the player look like they're moving incorrectly or in an inconsitent manner to what's expected, particularly when using tools or triggering the interact animation.

This ticket will focus on reconstructing the player spritesheet so that all animation frames are within one set frame size so that they appear smoothly. This will also need to consider any updates to the player collision box so that it does not end up extending more than is expected.

# **Milestones**
- [x] Decide on specific player sprite size (Aug. 30)
- [x] Update spritesheet png (Sep. 3)
- [x] Update player atlas (Sep. 4)
- [x] Update player collision box (Sep 6.)

**Completion Deadline:** Sep. 6

# **Documentation**
- [Player Design and Animation](../wiki/Player-Design-and-Animation)

# **Members**
- Liv (@vilnor) (Liv Ronda)
