### ISSUE TITLE
Alien NPC for checking missions

### ISSUE THREAD

**Issue by vilnor** [UQcsse3200/2023-studio-1#135]
# **Description**
The game will be introducing missions in the next two sprints. To integrate these features within the game universe, an alien NPC will be created to provide progress updates on what missions are available, and which ones have been completed.

This ticket will likely require design discussions with the design comittee and the teams responsible for implementing the mission framework (Team 5 & Team 7) before the design of the information overlay is finalised. 

## SubFeatures
- **Alien NPC Entity**
    - A friendly NPC that is restricted to a specific part of the map so that they are easy to access.
    - Can be interacted with by the player
    - Only needs basic sprites for this sprint (no animations yet)
- **Information Overlay** 
    - Pops up stylised like a very large speech bubble next to the alien NPC
    - For quests, contains a button for accepting which starts the quest completion timer
    - Exact presentation of content dependant on how missions will be set up
- **New/Updated Mission Indicator**
    - Shows up next to the NPC
    - Shows a status for missions
        - New quest available to accept
        - A quest's timeframe has expired
        - A quest has been complete and a reward is ready to collect
        - An achievemnt has been completed 

# **Dependencies**

- Mssion Framework (#148)

# **Milestones**
- [x] Alien NPC added and stays in specfiic location on map (Sep. 8)
- [x] Alien NPC can be interacted with and shows a speech bubble next to them (Sep. 10) 
- [x] Content layout is discussed with relevant teams and a design is finalised (Sep. 10)
- [x] Content layout is implemented in speech bubble (Sep. 11)
- [x] Current state of achievements & quests is hooked up  (Sep. 12)
- [x] Indicator hooked up

**Completion Deadline:** Sep. 12

# **Documentation**
- [Missions](../wiki/Missions-%28Achievements-and-Quests%29-System) (collaboration with other teams)
- [Mission UI](../wiki/Mission-UI)

# **Members**
- Liv (@vilnor) (Liv Ronda)
- Wilko (@yetanothercarbot) (Wilko Grunefeld)
- Ali (@bunnyycat) (Ali Spanevello)
- Alvaro (@alw0ng) (Alvaro Wong)
- Liam (@liamhemmett) (Liam Hemmett)

**Comment by JTrenerry** [comment]
pls dj khaled
