### ISSUE TITLE
Implement planetary oxygen service functionality

### ISSUE THREAD

**Issue by gilgilgilgilgil** [UQcsse3200/2023-studio-1#137]
# **Description**
In order to implement the proposed end-game targets/goals, it is required that a service regarding the planet's oxygen be implemented. The planet's atmospheric oxygen percentage is expected to be displayed in a similar fashion to the GameTimeDisplay, with a small, constant display present.
The functionality expected from this feature includes the following:

1. Oxygen can be added/produced and removed/consumed from the planet. This will need to be performable by any entity, such as mobs, tractors or potentially other 'combustion related' future items like campfires.
2. The addition/removal of oxygen will be available through two configurations: singular and continuous, with continuous being an hourly addition/consumption rate. (The idea is for entities like animals or a running tractor using up a constant rate of oxygen.)
3. Update an observing display service for the planet's atmospheric oxygen percentage.

It is expected that this functionality will be implemented through the following (To be updated if any changes occur):

1. A singleton 'subject' class PlanetOxygenService.java used to log and report on oxygen production and consumption on the planet.
2. An OxygenLevel interface to be implemented by this singleton class as well as any other future oxygen-storing items, a potential example being a player's personal tank in their spacesuit.

## SubFeature/component
- `OxygenLevel` Interface
- `PlanetOxygenService` class
- `OxygenDisplay` class

# **Dependencies**

- #147 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Implement OxygenLevel Interface (Sept. 2)
- [x] Implement basic functionality of PlanetOxygenService singleton class (Sept. 4)
- [x] Test PlanetOxygenService functionality (Sept. 5)
- [x] Set entity types' respective hourly oxygen consumption/production rates. (Sept. 7)
- [x] Link update() method to "hourUpdate" event from TimeService (Sept. 8)
- [x] Implement call of oxygen ui display update method.(Sept. 10)
- [x] Trigger end condition at 0 oxygen (Sept. 11)

**Completion Deadline:** Sept. 11

# **Extras **
- [ ] Player oxygen tank.
- [ ] 'Blackout' screen visual at low/dangerous oxygen levels

# **Documentation**
- [Oxygen System](https://github.com/UQcsse3200/2023-studio-1/wiki/Oxygen-System)

# **Members**
- Gil Wise (GitHub: @gilgilgilgilgil ) (Slack @Gil)
- Daniel Cottrell (@daniel-cottrell) (Daniel)
