### ISSUE TITLE
Implement ItemSlot Class

### ISSUE THREAD

**Issue by tristanduncombe** [UQcsse3200/2023-studio-1#138]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

Implement a ItemFrame class which constructs the inventory display of an item slot. This should display the item frame, the item texture, and the number of item.
 
# **Dependencies**
Nill

# **Milestones**
List of steps that need to be completed for this task.
- [x] Introduce Class (Sept. 1)
- [x] Implement display of item texture correctly (Sept. 2)
- [x] Implement count of item correctly (Sept. 2)
 
**Completion Deadline:** Sept. 2 

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Tristan Duncombe @tristanduncombe Slack: Tristan Duncombe
