### ISSUE TITLE
Art Assets for Plants

### ISSUE THREAD

**Issue by bunnyycat** [UQcsse3200/2023-studio-1#139]
# **Art Assets for Plants**
**Task:** Art Assets for Plants(#139).
**Feature:** Refinement and enrichment of plant functionality(#130)

This ticket is for all the art assets for the plants players can grow in the game.
The full list of assets required is as follows.
Item drops:
- Corn (cosmicCob)
- Gel (aloeVera)
- Alien tech/hammer (hammerPlant)
- Bone (venusFlyTrap)
- Vial with an alien symbol (waterWeed)
- Berry (atropaBelladonna)

Plant stages:
- Seedling (works for all plant types)
- Sprout/seed bag (sprout and seed bag use the same sprite) (one for each type)
- Juvenile (one for each type)
- Adult (one for each type)
- Decaying (one for each type)
- Dead (works for all plant type)

Animations:
- 'leaf explosion' destroy animation (works for all plants and stages)
- Harvest animation (for Producing stage)

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Growth stages of plants, plant names, plant drop items decided (#130)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Plant drop items done (September 4)
- [x] Seedling and Dead. Adult and Sprout for all plant types (September 6)
- [x] Juvenile and Decaying for all plant types. Destroy animation (September 9)
- [x] Harvest animation for all plant types (September 10)
 
**Completion Deadline:** September 11
 
# **Documentation**
- coming soon
 
# **Member**
- Ali (@bunnyycat) (Ali Spanevello)
- Alvaro (@alw0ng) (Alvaro Wong)
