### ISSUE TITLE
Player Sprite & Animation

### ISSUE THREAD

**Issue by yetanothercarbot** [UQcsse3200/2023-studio-1#14]
# **Description**
This ticket is for implementing the main character’s movement animation for various scenarios within the game. Movement animations are a key part of having players connect with characters in games. When the player walks around or interacts with objects, this will be represented by their character also performing these actions in-game (as opposed to the player’s character levitating around and using telekinesis to interact). 

## Components
This feature ticket can be split into five main components:

**Character Sprites & Design**
The main character’s sprites should be created for the desired movements and actions. Since there is no existing character design, this ticket will include creating the base character as well.

**Player Animation Controller**
In order to respond to player movements and actions, the `PlayerAnimationController` class should be created to manage event listeners on the player entity. The `PlayerFactory` should also be updated to use this animation controller.

**Movement Animations**
Player movements should trigger events for the animation controller to act on. The existing `triggerWalkEvent` functions should be updated to take a walk direction to trigger a direction event for the animation controller to change the orientation of the player sprite. A player movement animation `atlas` file should be created with animations for 

- Walking left
- Walking right
- Walking up
- Walking down

**Stationary Animations**
The player should have the following stationary animations

- Stretching
- Blinking eyes
- Yawning

These will eventually be hooked up to the in-game time component, where a random stationary animation will trigger after a certain amount of time has passed without player movement or interaction. For this sprint, this sub feature will focus on creating the stationary `atlas` file, and temporarily hooking events up to a keybinding to demonstrate functionality.

**Interaction Animations**
A generic “interact” animation where the character gestures in front of them should be created for future use. This could be applied to opening a chest, pushing a button, placing an item, etc. This will eventually be hooked up to the interaction events when they are implemented. 

For this sprint, this sub feature will focus on creating the interaction atlas file, and temporarily hooking events up to a keybinding to demonstrate functionality.

# **Dependencies**
This feature ticket has no hard dependencies, but we will work together with the teams implementing tools (#7), keybindings (#6) and time system (#10).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.

**Character Sprites & Design**
- [x] Draft player character design demoed to design committee and approved (Aug. 25)
- [x] Basic player walking animation sprites with at least 2 frames each created (Aug. 25)
- [x] Basic player stationary animation sprites with at least 2 frames each created (Aug. 27)
- [x] Basic player interaction animation sprites with at least 2 frames each created (Aug. 29)
- [x] Animation sprites extended with additional frames (Aug. 29)

**Player Animation Controller**
- [x] Implement `PlayerAnimationController` and connect to `PlayerFactory` (Aug. 16)

**Movement Animations**
- [x] Update `triggerWalkEvent` function to trigger directional event (Aug. 16)
- [x] Player walking animation `atlas` file with basic sprites created and connected to event triggers (Aug. 20)

**Stationary Animations**
- [x] Add temporary keybind for triggering stationary animation events (Aug. 20)
- [x] Player stationary animation `atlas` file with basic sprites created and connected to event triggers (Aug. 25)

**Interaction Animations**
- [x] Add temporary keybinding for triggering interaction animation events (Aug 23.)
- [x] Player interaction animation atlas file with basic sprites created and connected to event triggers (Aug. 25)

**Feature Completion Deadline: Aug. 30**

# **Extras (optional)**
- Additional animations for when the player bumps into obstacles such as rocks
- Additional animations for when the player is running instead of walking
- Tractor mount/dismount animation (as suggested in [this comment](https://github.com/UQcsse3200/2023-studio-1/issues/33#issuecomment-1682109674))

# **Documentation**
- [Animations](../wiki/Animations)
- [User documentation](../wiki/Terrain)
- ...

# **Members**
- Alvaro Wong (alw0ng) (@Alvaro Wong)
- Wilko Grunefeld (yetanothercarbot) (@Wilko)
- Olivia Ronda (vilnor) (@Liv Ronda)
- Ali Spanevello (bunnyycat) (@Ali Spanevello)
- Liam Hemmett (liamhemmett) (@Liam Hemmett)

**Comment by JTrenerry** [comment]
Hey, are the basic sprites done yet (like one facing left, forward and back)?
