### ISSUE TITLE
Pause Functionality

### ISSUE THREAD

**Issue by ManavTriv** [UQcsse3200/2023-studio-1#140]
# **Description**
**Task:** Pause Functionality
**Feature:** Pause Feature

The current implementation of the pause function only paused the in-game time and hence did not affect other aspects of the game. 

This needs to be extended so the state of entities stop getting updated whenever the in-game time is paused. Or rather whenever `ServiceLocator.getTimeService().isPaused() == true`. Furthermore, animations should also be paused and continue exactly from where it was paused from when the game is unpaused. 

# **Dependencies**
- Pause Feature
- https://github.com/UQcsse3200/2023-studio-1/issues/71
- https://github.com/UQcsse3200/2023-studio-1/issues/10

# **Milestones**
- [x] Step 1: Prevent entities from updating when the game is paused
- [x] Step 2: Prevent animations from continuing when the game is paused
- [x] Step 3: Test the functionality to ensure that its working as intended
 
**Completion Deadline:** Sep. 11
 
# **Documentation**
- Pause Feature
- [Time System](https://github.com/UQcsse3200/2023-studio-1/wiki/Time-System-(Sprint-2-onwards))
 
# **Member**
- Manav Trivedi (@ManavTriv) (Manav Trivedi)
