### ISSUE TITLE
Lose Event, Screen and Timer

### ISSUE THREAD

**Issue by ManavTriv** [UQcsse3200/2023-studio-1#143]
# **Description**

When the player loses the game, the game must stop and the lose game screen should appear. The player will be able to potentially lose the game in numerous ways therefore a general way to trigger the 'lose event' must be implemented. Hdnce, when the game starts up, a listener should be registered under the event handler for the player entity (jn `MainGameScreen`).  This is because losing the game will result in the player failing, so it makes the most sense to register an event under the player entity instead of a different class. A losing screen must be implemented as well, with a button to either exit the game or return to the main menu. Finally, an initial loose lose condition will be implemented in the form of a timer - the player will automatically lose when the game reaches a certain day. In later sprints this condition can be made stricter to ensure that the player will lose only if certain conditions aren't met.

## SubFeature/component (optional)
- Lose screen listener will be added to the player entities event handler so event can be triggered anywhere by any class by accessing the service locator, then getting the map and then the player. 
- `LoseScreen` in the folder `Screens` and  `LoseScreenDisplay` in components to manage the screen and UI for the losing screen
- An initial lose timer in the `TimeService` class that will trigger the lose event after a certain amount of games

# **Dependencies**
- https://github.com/UQcsse3200/2023-studio-1/issues/10

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Goal 1: Create the design for the lose game screen
- [x] Goal 2: Create the `LoseScreen` and  `LoseScreenDisplay` class so that the lose game screen UI is implemented
- [x] Goal 3: Add the listener to player entities event handler, and ensure that the game stops and switches to the lose screen UI when the event is triggered
- [x] Goal 4: Add the loose lose condition timer in `TimeService`

**Completion Deadline:** Aug. 10

# **Documentation**
- https://github.com/UQcsse3200/2023-studio-1/wiki/Menu-Screens - Lose Screen Section
- https://github.com/UQcsse3200/2023-studio-1/wiki/Time-System-(Sprint-2-Onwards) 

# **Members**
- Manav Trivedi (@ManavTriv) (Manav Trivedi)
