### ISSUE TITLE
Implement the Oxygen Display UI

### ISSUE THREAD

**Issue by daniel-cottrell** [UQcsse3200/2023-studio-1#147]
# **Implement the Oxygen Display UI**
**Task:** [Implement Oxygen UI](#3)
**Feature:** [Implement planetary oxygen level functionality](#137)

Implement a UI component to display the oxygen bar on the main game screen, showing the oxygen level as a percentage. `OxygenDisplay` extends `UIComponent` and will track the current oxygen level through a `ServiceLocator` instance. It will update every hour, showing the correctly scaled oxygen level depending on the oxygen logic calculations.
 
## **Example (optional)**
- **Visual Appearance**: The oxygen will always appear in the game, updating as time progresses.

# **Dependencies**

- #137
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create the assets that will be used for the oxygen display (Sep. 3)
- [x] Manually display the oxygen UI components on the screen (Sep. 5)
- [x] Adjust the `OxygenDisplay` class to be able to take percentages of oxygen and update the display according to them (Sep. 6)
- [x] Add an endgame check that ends the game once the oxygen level reaches 0% (Sep. 9)
- [x] Update the wiki for `OxygenDisplay` and oxygen related info (Sep. 10)
- [x] Verify the functionality of `OxygenDisplay` through user testing (Sep. 11)
 
**Completion Deadline:** Sep. 11
 
# **Documentation**
- [Oxygen System](../wiki/Oxygen-System)
 
# **Member**
- Daniel Cottrell (@daniel-cottrell) (Daniel Cottrell)
- Gil Wise (@gilgilgilgilgil) (Gil)
