### ISSUE TITLE
Achievements & Quests System

### ISSUE THREAD

**Issue by Tom-Strooper** [UQcsse3200/2023-studio-1#148]
# Description
The achievements & quests system (a.k.a., *missions system*) will be a system that manages in-game quests and achievements. Missions are tasks that can or must be completed by the player.

Achievements are types of missions that are optional and apply across the whole game. Once an achievement is completed, it is completed permanently.

Quests are types of missions that can be either optional or mandatory, have a time limit, and can result in a reward for the player upon successful completion.

The missions system aims to be flexible and extensible, to allow any member of the studio to add their own quests or achievements which relate to their own features to the game.

## Features
- A `MissionManagerService` class accessible by anyone through the `ServiceLocator`. This will be used by any member of the studio add missions for the player
- A `Mission` abstract class, along with the `Achievement` and `Quest` abstract subclasses, which represent in-game `Achievement`s and `Quest`s respectively. Members of the studio will be able to create subclasses which can be instantiated to create trackable in-game missions.
- An in-game NPC from which players will be able to gain new quests
- A UI screen from which players will be able to view all visible achievements (accessible from the homescreen or from the pause menu)

## Examples
- To create an in-game quest, a studio member should create an extension of the abstract `Quest`, overriding any important functionality methods. They should also privately keep track of all stats related to the quest, and update them through listening to the appropriate events on the `MissionManagerService`.
- The player should be able to see the NPC, who has a thought bubble indicating that there are quests which the player can accept. The player goes over to the NPC, and interacts with them. They see a list of available quests, and choose to accept a quest involving planting 50 corn. Over the next few in-game days, they plant corn and complete the quest before its expiry. They then return to the NPC to claim their reward
- The player should be able to access a list of completed and uncompleted achievements from the home or pause screens

# Dependencies
In order to properly implement mandatory quests, which result in a game-over if left uncompleted before their expiry, a functional game-over system needs to be implemented. See #143.

# Milestones
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Complete preliminary wiki page outline of feature, for other teams’ input (Sep. 2)
- [x] Implement the `Mission` abstract class (Sep. 6)
- [x] Implement the `MissionManagerService` class (Sep. 6)
- [x] Implement the `Reward` class (Sep. 6)
- [x] Implement the `Quest` and `Achievement` classes (Sep. 6)
- [x] Implement the `MissionEvent` enum (Sep. 6)

**Completion Deadline:** Sep. 12

# Documentation
- [Missions System](https://github.com/UQcsse3200/2023-studio-1/wiki/Missions-%28Achievements-and-Quests%29-System)

# Members
- Tom Strooper (@Tom-Strooper) (Tom Strooper)
- Charlotte Birkinshaw (@charliebkw) (Charlotte)
