### ISSUE TITLE
Weather and climate system

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#149]
# **Description**
This feature ticket is for a weather system that will be added to the game. This weather system will allow the game to have random weather events that impact the climate conditions of the game area and affect the player's stats. Ideally, this system will have an effect on the visible game area, and may have sound effects depending on the weather event (eg: rain sounds if the weather event is rain). 

## Components
- `ClimateController` class which will contain the climate information of the game area (eg: temperature, humidity, oxygen level)
- Weather events that will occur randomly for a fixed duration and will affect the climate of the game
- Visual game overlay and sound effects corresponding to each weather event

# Dependencies
- Time System (Tickets #71 and #102)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Implement `ClimateController` class 1 (Sep. 5)
- [x] Implement `WeatherEvent` abstract class and implementations (Sep 8)
- [x] Develop visual game overlay for each weather event (Sep 10)
- [x] Integrate climate modifiers with other system (Sep 11)

**Completion Deadline:** Sep. 12

# **Documentation**
- [Documentation](../wiki/Weather-and-Climate-System)

# **Members**
- Lucas Hicks (@lucashicks1) (Lucas Hicks)
- Tom Strooper (@Tom-Strooper) (Tom Strooper)
- Shristi Gupta (@shristigupta1408) (Shristi Gupta)

**Comment by lucashicks1** [comment]
Closed as completed.
