### ISSUE TITLE
Item Class

### ISSUE THREAD

**Issue by 86LAK** [UQcsse3200/2023-studio-1#15]
# **Description**
**Task:** Item Class.
**Feature:** #7 

Broad item class which will act as the parent for tool class and others similar. This item class acts as a versatile parent structure that lays the groundwork for various subclasses, such as the tool class and potentially others that share similar attributes and behaviours.  The item class framework will enable efficient subclass creation while ensuring that each subclass inherits essential functionalities and characteristics from its parent. Extensive documentation for this class will also be made to ensure future subclass development is easily possible. 

 
# **Milestones**

- [x] Basic implementation of items

- [x] Change items to fit under ECS model

- [x] ItemComponent

- [x] Do extensive documentation for Items to allow easy item creation etc.

 - [x] JUnit testing to cover all 

**Completion Deadline:** Aug. 22
 
# **Member**
- Shanon Lakshan Chandrasekara @86LAK

**Comment by 86LAK** [comment]
https://github.com/UQcsse3200/2023-studio-1/wiki/Items

**Comment by 86LAK** [comment]
finished adding itemComponent class and tests and documentation
