### ISSUE TITLE
Mission Classes Implementation

### ISSUE THREAD

**Issue by Tom-Strooper** [UQcsse3200/2023-studio-1#150]
# **Description**
**Task:** Mission Abstract Class Implementation (#150).
**Feature:** Missions System (#148)

Create and implement the `Mission` class. The `Mission` class is an abstract class representing some form of trackable in-game task. This class will be extended in the form of `Quest`s and `Achievement`s. The abstract `Mission` class will contain methods to deal with indicating the progress of missions to the `MissionManagerService`.

Instances of `Mission`s should track stats related to the completion of the task, and listen to events triggered on the `MissionManagerService`'s `EventHandler` to update their internal state.

# **Milestones**
The steps that need to be completed include:
- [x] Add information about the class to the [Missions System Wiki](https://github.com/UQcsse3200/2023-studio-1/wiki/Missions-%28Achievements-and-Quests%29-System) (Sep. 2)
- [x] Implement the `Mission` abstract class (Sep. 4)
- [x] Add javadocs to the class (Sep. 4)
- [x] Add implementation for `Reward` class and concrete `ItemReward` and `StatReward` classes (Sep. 6)
- [x] Add implementation for `Quest` class (Sep. 6)
- [x] Add implementation for `Achievement` class (Sep. 6)
- [x] Add unit testing to the classes (Sep. 10)
 
**Completion Deadline:** Sep. 6 (initial implementation), Sep. 10 (full task complete)

# **Documentation**
- [Missions System Wiki](https://github.com/UQcsse3200/2023-studio-1/wiki/Missions-%28Achievements-and-Quests%29-System)
 
# **Member**
- Tom Strooper (@Tom-Strooper) (Tom Strooper)
