### ISSUE TITLE
ClimateController class

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#151]
# **Description**
**Feature:** #149 

Task ticket is to create the `ClimateController` class which is responsible for handling random weather events. This `ClimateContoller` class will be accessible through implementations of the `GameArea` class. Some of the key climate attributes that this game will have is:
- Temperature
- Humidity

# **Dependencies**
- [x] Time System #102 
- [x] Weather Events #164 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement `ClimateController` class (Sep 5)
- [x] Add tests for class (Sep 7)
- [x] Add relevant javadocs (Sep 9)
- [x] Add to wiki (Sep 9)

**Completion Deadline:** Sep 9

# **Documentation**
- [Main description of feature](../wiki/Weather-and-Climate-System)

# **Member**
- Lucas Hicks (@lucashicks1 ) (Lucas Hicks)
- Shristi Gupta (@shristigupta1408) (Shristi Gupta)
