### ISSUE TITLE
MissionManagerService Class Implementation

### ISSUE THREAD

**Issue by Tom-Strooper** [UQcsse3200/2023-studio-1#152]
# **Description**
**Task:** MissionManagerService Class Implementation (#152)
**Feature:** Missions System (#148)

The `MissionManagerService` class is a class that manages all active `Mission`s (including `Achievement`s and `Quest`s). It contains an `EventHandler` which classes will be able to use to trigger certain events which will update the status of tracked `Mission`s.

# **Dependencies**
- [x] The `Mission` class needs to be defined (#150)
 
# **Milestones**
The following Milestones need to be completed:
- [x] Add information about the class to the [Missions System Wiki](https://github.com/UQcsse3200/2023-studio-1/wiki/Missions-(Achievements-and-Quests)-System) (Sep. 2)
- [x] Implement the `MissionManagerService` class (Sep. 4)
- [x] Add javadocs to the class (Sep. 4)
- [x] Add unit testing to the class (Sep. 10)
 
**Completion Deadline:** Sep. 4 (initial implementation), Sep. 10 (full task complete)
 
# **Documentation**
- [Missions System](https://github.com/UQcsse3200/2023-studio-1/wiki/Missions-(Achievements-and-Quests)-System)
 
# **Member**
- Tom Strooper (@Tom-Strooper) (Tom Strooper)
- Lucas Hicks (@lucashicks1) (Lucas Hicks)
