### ISSUE TITLE
Seeds and Fertiliser

### ISSUE THREAD

**Issue by DonghyugDavidJeong** [UQcsse3200/2023-studio-1#156]
# **Description**
This feature ticket is designed to create Seeds, which will allow the player to create plants for the farm, and Fertiliser, which will enrich the farming experience. Seeds are essential to allow the player to create plants they wish, and fertiliser is necessary to allow the player to interact with the game on more levels, while also giving them something to do to decrease the amount of time they just sit around and wait. Seeds and Fertiliser will both be consumable items that will be able to be picked up into the inventory and used.

## Sub-Features/components
- `Seeds` which determine what plant is being planted and how many of that type they can plant. There will need to be a separate seed for each plant.
- `Fertiliser` which triggers the fertilise event on the `CropTileComponent`, modifying the growth rate of the plant.

## **Examples/use cases**
- Seeds: A player could hold `"Venus Flytrap Seed"`, go to a `CropTileComponent` and plant the seed, to create an entity with `PlantComponent` `VenusFlyTrap` on it.
- Fertiliser: A player could hold the fertiliser, go to a `CropTileComponent` which has a plant, and fertilise the CropTile to boost the growth rate.

# **Dependencies**
- Team 6 - #130 - As the seeds are merely planting existing plant components, the connection with the existing plants will need to be made through collaboration with the plant team.
- Team 2 - #139 - The seeds will need their own sprites.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Create Seed and Fertiliser Items that can be placed in inventory (Sep. 5)
- [x] Connect seed, plant and croptile (Sep. 7)
- [x] Give sprites to seed and fertiliser (Sep. 10)
- [x] Add Javadocs (Sep. 10)
- [x] Write wiki page for seeds/fertiliser (Sep. 10)
- [x] Add UML Diagram for seeds/fertiliser in wiki page (Sep. 10)

**Completion Deadline:** Sep. 12 3pm

# **Documentation**
- [Items](https://github.com/UQcsse3200/2023-studio-1/wiki/Items)
- [Plant Component](https://github.com/UQcsse3200/2023-studio-1/wiki/Plant-Component)

# **Members**
- David (@DonghyugDavidJeong) (Donghyug David Jeong)
