### ISSUE TITLE
Additional Features when Tamed

### ISSUE THREAD

**Issue by UniversalTze** [UQcsse3200/2023-studio-1#158]
# **Description**
**Task:** Additional features/ behaviours of the animals when tamed. (#4 ).
**Feature:** This extends the functionality of the Tameable component. (#39)

Implementing this task will give behaviour to animals when tamed. Whether that be protecting the farm/spaceship/player from pests or being able to provide the player with natural resources. An idea for when tamed, is that the animal will follow the player when the player has food. 
 
## **Example**
- **Food Benefits**: When the AstroCluck (chicken) is tamed, it can provide eggs for the player. Or if the GalaticGlazer (cow) is tamed it could provide other resource like food or milk. 
- **Additional Protection**: The tamed animals could serve as protectors of the player's home and farm. 

# **Dependencies**
- [x] Dependency 1 Animal Team Implementing Enemy Animals
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1  Implement a simple Tamed Task where tamed animals will not wonder outside a fixed area of the player. (Sep. 10)
- [x] Step 2 Have Discussions with studio about the player's home and farm (Sep. 12)
- [x] Step 3 Find animations for when animal is tamed (Sep. 11)
- [x] Step 4 Implement that functionality into the game (Sep. 29)
- [x] Step 5 Develop unit tests for feature
 
**Completion Deadline:** 
- [x] Initial idea of tamed animals behaviour cemented (Sep. 12).
- [x] `Tamed task` class implemented and tested (Sep. 20).
- [x] Documentation of `Behaviour when tamed` updated on wiki (Sep. 20).
 
# **Documentation**
- [Animals](https://github.com/UQcsse3200/2023-studio-1/wiki/Animals)
 
# **Member**
- Tze Kheng Goh UniversalTze

**Comment by UniversalTze** [comment]
Feature has been completed.
