### ISSUE TITLE
Reward Class

### ISSUE THREAD

**Issue by charliebkw** [UQcsse3200/2023-studio-1#159]
# **Description**
**Task:** [Reward Class](#159).
**Feature:** [Achievements & Quests System](#148)

The `Reward` class is an abstract class representing an in-game reward which can be collected as a result of completing a Mission **(v1 only!)** or milestone **(v2 only!)**. The public `isCollected()` method is provided by default, and returns `true` iff the reward’s `collect()` method has been called. The `Reward` class will then be extended by the `StatReward` and `ItemReward` classes to provide more specific reward functionalities.
 
## **Example**
- **Rewards**: When a player completes a Quest they can receive a `Reward`.
- **StatReward**: An extension of the `Reward` class. When the `collect()` method is called on this type of reward it can update the `Player`s stats e.g. speed, health.
- **ItemReward**: An extension of the `Reward` class. When the `collect()` method is called on this type of reward it can add Items to the `Player`s inventory such as Seeds, fertiliser etc.

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Wiki documentation (Sep. 2)
- [x] Create the classes (Sep 4.)
- [x] Add Javadocs (Sep. 5)
- [x] Create tests (Sep. 5)
 
**Completion Deadline:** Sep. 6

 
# **Documentation**
- [Mission System](https://github.com/UQcsse3200/2023-studio-1/wiki/Missions-%28Achievements-and-Quests%29-System)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Charlotte Birkinshaw (@charliebkw) (Charlotte)

**Comment by lucashicks1** [comment]
Closed as completed
