### ISSUE TITLE
TerrainEntityFactory

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#16]
# **Task Description**
**Task:** TerrainEntityFactory Abstract Class
**Feature:** #8 

An abstract factory interface which will be implemented by other factories that created terrain entities (Entities that have the `TerrainComponent` component). This task will be relatively simple to implement as most of the implementation will be done in the concrete (non-abstract) classes.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Identify necessary components of class (Aug. 16)
- [x] Create the interface 3 (Aug. 18)
- [x] Add the Javadocs (Aug. 19)
 
**Completion Deadline:** Aug. 20

# **Documentation**
- [Feature Description](https://github.com/UQcsse3200/2023-studio-1/wiki/Tile-System)
 
# **Member**
- Lucas (@lucashicks1) (Lucas Hicks)

**Comment by lucashicks1** [comment]
This interface will be removed as it is only providing the createTerrainEntity() method and this method makes sense to be static and static methods in interfaces need a body. Additionally, static methods can't be overridden.
