### ISSUE TITLE
Implement Seeds

### ISSUE THREAD

**Issue by DonghyugDavidJeong** [UQcsse3200/2023-studio-1#161]
# **Description**
**Task:** [Implement Seeds](#3).
**Feature:** [Seeds and Fertiliser](#156)

This task ticket is designed to create `Seeds`, which will allow the player to create plants for the farm. `Seeds` are essential to allow the player to create plants they wish. `Seeds` will determine what plant is being planted and how many of that type they can plant. There will need to be a separate seed for each plant. Seeds will be consumable items that will be able to be picked up into the inventory and used.
 
## **Example (optional)**
A player could hold `"Venus Flytrap Seed"`, go to a `CropTileComponent` and plant the seed, to create an entity with `PlantComponent` VenusFlyTrap on it.

# **Dependencies**
- Team 6 - #130 - As the seeds are merely planting existing plant components, the connection with the existing plants will need to be made through collaboration with the plant team.
- Team 2 - #139 - The seeds will need their own sprites.

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create Seed Items that can be placed in inventory (Sep. 5)
- [ ] Connect seed, plant and croptile (Sep. 7)
- [ ] Give sprites to seeds (Sep. 10)
- [ ] Add Javadocs (Sep. 10)
- [ ] Write wiki page for seeds/fertiliser (Sep. 10)
 
**Completion Deadline:** Sep. 12 3pm

# **Documentation**
- [Items](https://github.com/UQcsse3200/2023-studio-1/wiki/Items)
- [Plant Component](https://github.com/UQcsse3200/2023-studio-1/wiki/Plant-Component)
 
# **Members**
- David (@DonghyugDavidJeong) (Donghyug David Jeong)
