### ISSUE TITLE
Implement Fertiliser

### ISSUE THREAD

**Issue by DonghyugDavidJeong** [UQcsse3200/2023-studio-1#162]
# **Description**
**Task:** [Implement Fertiliser](https://github.com/UQcsse3200/2023-studio-1/issues/162).
**Feature:** [Seeds and Fertiliser](https://github.com/UQcsse3200/2023-studio-1/issues/156)

This task ticket is designed to create `Fertilisers`, which will enrich the farming experience. `Fertilisers` are necessary to allow the player to interact with the game on more levels, while also giving them something to do to decrease the amount of time they just sit around and wait. `Fertilisers` will be a consumable item that will be able to be picked up into the inventory and used.
 
## **Example (optional)**
- `Fertiliser` which triggers the fertilise event on the `CropTileComponent`, modifying the growth rate of the plant.

# **Dependencies**
- [ ] CropTileComponent (#19)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create Fertiliser Items that can be placed in inventory (Sep. 5)
- [ ] Give sprites to fertiliser (Sep. 10)
- [ ] Add Javadocs (Sep. 10)
- [ ] Write wiki page for fertiliser (Sep. 10)
 
**Completion Deadline:** Sep. 12 3pm

e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Items](https://github.com/UQcsse3200/2023-studio-1/wiki/Items)
- [Plant Component](https://github.com/UQcsse3200/2023-studio-1/wiki/Plant-Component)
 
# **Member**
- David (@DonghyugDavidJeong) (Donghyug David Jeong)
