### ISSUE TITLE
Plant Growth Stages

### ISSUE THREAD

**Issue by tomedwa** [UQcsse3200/2023-studio-1#163]
**Task:** Plant Growth Stages (#163).
**Feature:** Refinement and enrichment of plant functionality (#130)

# **Description**
Implement the plant growth feature by introducing a new property called 'growth threshold' for each plant, which will indicate the current stage of growth. These growth thresholds will allow different plants to have unique grow times based on various factors that effect the growth rate provided by the crop tile where the plant will be located. Additionally, each plant will display distinct sprites corresponding to its current growth stage.
 
# **Dependencies**
- [x] CropTileComponent (#19): Provides the growth level based on the current conditions of the tile.
- [x] Time Fucntionality (#71): Provides the time so which can indicate when the plant will grow.
- [x] Art Assets for Plants (#139): Provides the sprites representing different growth stages of the plants.
 
# **Milestones**
- [x] Create a constructor in the PlantComponentClass to handle passing unique growth stage thresholds to a plant (Sep. 5)
- [x] Include methods in the PlantComponents class to update the growth stage of the plant based on currentGrowthLevel and how long a plant has been an adult (Sep. 5)
- [x] Update plants.json (Sep. 12)
     - [x] Include different growth thresholds (e.g sproutThreshold, juvenileThreshold, and adultThreshold) (Sep. 6)
     - [x] Include paths to images for different growth stages (Sep. 12)
- [x] Update the BasePlantConfig class to handle the different growth stage values defined in the plant.json file (Sep. 7)
- [x] Update PlantComponent to update the maximum health of the plant when the growth stage changes
- [x] Update PlantFactory to pass unique growth stage thresholds to different plants (Sep 7.)
- [x] Change the current sprite of the plant based on the current growth stage (Sep. 10).
- [x] Javadocs for all new methods (Sep. 12).

**Completion Deadline:** Sep. 12
 
# **Documentation**
- [Plant Component] https://github.com/UQcsse3200/2023-studio-1/wiki/Plant-Component
- [Plant Properties and Types] https://github.com/UQcsse3200/2023-studio-1/wiki/Plant-Properties-and-Types
- [Plant Configs] https://github.com/UQcsse3200/2023-studio-1/wiki/PlantConfigs
- [[JavaDoc](JavaDoc/Location/Package/Class)](https://uqcsse3200.github.io/2023-studio-1/com/csse3200/game/components/plants/PlantComponent.html)
 
# **Member**
- Tom (@tomedwa) (Tom Edwards)
- Sanchit (@Sanchitjain16) (Sanchit Jain)
- Codie (@kodee-koder) (Codie Chung)
