### ISSUE TITLE
Weather Event abstract class and implementations

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#164]
# **Description**
This task will implement weather events like rain and solar flare in the game. These will be applied based on in-game hours and will have various effects like change in the humidity and temperature. The amount of change will be generated randomly and each weather event will have a severity between 1 and 1.5. This feature will add a sense of mystery and realism to the game.

# **Dependencies**

No dependencies.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Implement `WeatherEvent` abstract class (Sep 6)
- [x] Implement `RainEvent` and `HeatWaveEvent` (Sep 8)
- [x] Add tests (Sep 10)
- [x] Add JavaDocs (Sep 10)

**Completion Deadline:** Sep 10

# **Documentation**
- [Main description of feature](../wiki/Weather-and-Climate-System)

# **Members**
- Shristi Gupta (@shristigupta1408 ) (Shristi Gupta)
- Lucas Hicks (@lucashicks1) (Lucas Hicks)
