### ISSUE TITLE
Player Movement/Stats affected by Terrain

### ISSUE THREAD

**Issue by HunterWhitty** [UQcsse3200/2023-studio-1#167]
# **Description**
Currently, the player has a maximum walk and run speed modifier which is kept in the PlayerActions class. These variables are represented as static Vector2 instances. The goal of this feature ticket is to introduce a movement speed modifier that is affected by the type of terrain the current player is standing on. Another goal is to prevent the player from moving onto un-traversable tiles. It would also be useful to provide a framework to allow other teams the ability to add modifiers to the terrain that affect other entities (requiring work through both the GameMap and the affected entities).

## SubFeature/component (optional)
- Movement modifiers from terrain for players
- Movement modifiers from terrain for other entities
- Impassible Terrain
- Thorough documentation to ensure the process can be replicated easily for other entities/properties

## **Examples (optional)**
- Player walking on sand: Player movement is slightly reduced
- Player walking on grass: Default movement speed
- Player trying to walk into deep water: Prevented from doing so

# **Dependencies**
- Requires the getter methods for specific tiles from the Map team (Team 3)

# **Milestones**
- [x] Understand Player Movement (Sept. 5)
- [x] Modify Player Movement in Meaningful Way (Sept. 6)
- [x] Implement Terrain Movement Affects (Sept. 9)
- [x] Implement Impassable Terrain (Sep. 10)

**Completion Deadline:** Sept. 12

# **Documentation**
- [User documentation](../wiki/Terrain) - need to add

# **Members**
- Hunter (HunterWhitty) (Hunter Whitlock)
- Riley (RileyWhitty) (Riley Whitlock)
- Angus (AngusWhittaker) (Angus Whittaker)
- Nathaniel (Radius-XT)
- Thang (thanghoang7020202) (Cao Quoc Thang Hoang)
