### ISSUE TITLE
Implement Alien Animals Advanced

### ISSUE THREAD

**Issue by v1dyut** [UQcsse3200/2023-studio-1#168]
# **Description**
This feature seeks to extend on the previous feature [Implement Alien Animals Basic](#4). This will include spawning behaviour,  visual updates and refactoring behaviours. Advanced animals will implement additional layers of gameplay complexity and directly contribute to the win condition.

## SubFeature/component
* Loot drops, animals will passively drop items once tamed and will drop items on death.
* Implement animal death.
* Recolour and add taming indicators to animals. Recolour animals to align with studio design guidelines and convey the alien theme. Taming indicators will show when an animal is tamed, will take the form of a green circle around the animal.
* Refactor the follow, chase and runway tasks to remove duplicate code.
* Implement mechanism to allow for interactions with non-tile entities (such as feeding, taking damage).
* Implement spawning behaviour to only occur on valid map tiles (etc., no spawning on lava).
* Implement Astrolotl adding oxygen when fed items.
* Add sound effects for animals.

# **Dependencies**
* Item (need to be able to create items that animals drop). (#15)
* Inventory (need to be feed animals using items in inventory). (#5 )
* Damage tool (need a sword to be able to damage the animals). (#174)
* Time service (need to implement passive dropping behaviour periodically). (#10)
* Oxygen meter (Astrolotl needs to add to the oxygen meter). (#149)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Recolour and add taming indicators.  (Sep. 5)
- [x] Animal passive loot drops including design of items. (Sep. 8)
- [x] Refactor follow, chase and runaway. (Sep. 9)
- [x] Implement universal interaction mechanism for animals. (Sep. 9)
- [x] Implement Astrolotl creating oxygen when fed food. (Sep. 11)

**Completion Deadline:** Sep. 12

# **Documentation**
- [Animals](https://github.com/UQcsse3200/2023-studio-1/wiki/Animals)
- [Hostiles](https://github.com/UQcsse3200/2023-studio-1/wiki/Hostile-Animals)

# **Members**
- @27abdullah 
- @v1dyut 
- @pchsa 
- @UniversalTze 
- @Bradbowi
