### ISSUE TITLE
Implement Hostile Animals

### ISSUE THREAD

**Issue by v1dyut** [UQcsse3200/2023-studio-1#169]
# **Description**
This feature seeks to implement hostile animals that hinder the player. They perform actions such as consuming oxygen, attacking plants and attacking the player. Hostile animals add an additional layer of complexity to the game by hindering the player's progress. They force the player to take actions to prevent their harmful behaviours otherwise they risk losing progress.

## SubFeature/component (optional)
* Find art assets and recolour them to align with studio design guidelines.
* Add non-tile entity interaction mechanism (for damaging, dealing damage).
* Spawning behaviour.
* Indicator to show that hostile animal exists.

### Further SubFeatures
Oxygen Eater
* Reduce oxygen meter.
* Add ranged knockback attack.

Plant Eater
* Target plant entities, deal damage to plants.
* Add runaway task

Player Damager
* Target player and deal damage.

# **Dependencies**
* Advanced animal functionalities (interaction mechanism, spawning behaviour). (#176 )
* Oxygen meter (for Oxygen Eater). (#149)
* Plant functionality (locations and access health). (#20)

# **Milestones**
- [x] Find art assets and recolour them (Sep. 5)
- [x] Add hostile animals with targeting and damaging functionality (Sep. 30)
- [x] Implement damage tool(s) (Sep. 28)
- [x] Add indicators to show the presence of the plant eater and oxygen eater (Oct. 2)
- [x] Implement intelligent spawning behaviour (Oct. 3)

**Completion Deadline:** Oct. 4

# **Documentation**
- [Animals](https://github.com/UQcsse3200/2023-studio-1/wiki/Animals)
- [Hostiles](https://github.com/UQcsse3200/2023-studio-1/wiki/Hostile-Animals)

# **Members**
- @v1dyut 
- @pchsa 
- @27abdullah
- @Bradbowi 
- @UniversalTze
