### ISSUE TITLE
Passive item drop for animals

### ISSUE THREAD

**Issue by 27abdullah** [UQcsse3200/2023-studio-1#170]
# **Description**
**Task:** [Passive item drop for animals](#170).
**Feature:** [Implement Alien Animals Advance](#168)

Create and integrate the `PassiveDropComponent`. This component will inherit from `Component` and will allow animals to passively drop items at regular intervals once tamed. These items will be beneficial for the player as to encourage them to tame animals. Different animals will drop different items to encourage the player to grow/harvest a variety of plants in order to tame the different animals.

# **Dependencies**
- [x] Items (#15)
- [x] Time system - determine when the item is dropped (#10 )
- [x] TameableComponent - determine when to activate the component

# **Milestones**
- [x] Decide on characteristics of dropped items e.g., what animal drops them, benefits, design (Sep. 6)
- [x] Create items to be dropped (Sep. 8)
- [x] Create item dropping component (Sep. 8)
- [x] Integrate time scheduling system (Sep. 11)
- [x] Integrate TameableComponent so that animals drop items once tamed (Sep. 11)
 
**Completion Deadline:** Sep. 12
 
# **Documentation**
- [Animals](../wiki/Animals)
 
# **Member**
- Abdullah (@27abdullah)
- Vidyut (@v1dyut)
