### ISSUE TITLE
Refactor ChaseTask, RunAwayTask and FollowTask

### ISSUE THREAD

**Issue by 27abdullah** [UQcsse3200/2023-studio-1#171]
# **Description**
**Task:** [Refactor ChaseTask, RunAwayTask, FollowTask](#171).
**Feature:** [Implement Alien Animals Advance](#168)

The `FollowTask` and `RunAwayTask` have shared functionality with the `ChaseTask` . To reduce duplication, these classes will be refactored to have `FollowTask` and `RunAwayTask` inherit from `ChaseTask`. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Update `ChaseTask` to make it useful for inheritance (Sep. 4.)
- [x] Refactor `FollowTask` to inherit from `ChaseTask` (Sep. 6)
- [x] Refactor `RunAwayTask` to inherit from `ChaseTask` (Sep. 7)

**Completion Deadline:** Sep. 12

# **Documentation**
- [Descriptions of these components](../wiki/Animals)
 
# **Member**
- Abdullah (@27abdullah)
