### ISSUE TITLE
Update animal visuals and add new hostile visuals

### ISSUE THREAD

**Issue by v1dyut** [UQcsse3200/2023-studio-1#172]
# **Description**
**Task:** [Update animal visuals and add new hostile visuals](#170).
**Features:** [Implement Alien Animals Advanced](#168 ) /  [Implement Hostile Animals](#169)

This current animals in the game need to align more closely with the studio's art style and assets need to be found/modified for the hostile animals. This includes adding taming indicators that display around the animal when they are tamed.
 
## **Example (optional)**
- **Tamed Indicator**: after an animal has been tamed, a green indicator will show around the animals. 
- **Hostile Animals**: the hostile animals implemented in the game will be carefully considered to ensure they align with the studio's goal of developing a relaxing game. The animals will most likely take the form of small pests, this might include things like small frog like monsters or insect like winged creatures. Care will be taken to ensure these animals are not excessively scary and daunting.

# **Dependencies**
- [x] Basic animal implementation for animations (includes animation rendering functions) (#4)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Recolour existing animals using studio colour palette (Sep. 6)
- [x] Recolour new hostile animal assets (Sep. 7)
- [x] Add green tamed rings to tameable animals (Sep. 7)
- [x] Update the .atlas files and PNG files to include both wild and tamed sprites (Sep. 8)
- [x] Create PNG files and .atlas files for hostile animals (Sep. 9)
 
**Completion Deadline:** (Sep. 9)

 
# **Documentation**
- [Animals](https://github.com/UQcsse3200/2023-studio-1/wiki/Animals#animal-species)
- [Hostiles](https://github.com/UQcsse3200/2023-studio-1/wiki/Hostile-Animals#hostile-species)

 
# **Member**
- @v1dyut
