### ISSUE TITLE
Weather Event Overlay

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#173]
# **Description**
**Feature:** #149 

This task ticket is for investigating and possibly implementing visual effects on the screen (visual overlay) that will change the way the player sees the game area depending on the current weather event. For example, if a solar flare were to occur, the game screen would have a red tint surrounding the edges. It is aimed that this will be further extended to work with the day/night cycle of the game, making the screen dark when the game time is night time.

*See page 339 of mastering game development in libgdx book for inspiration*

# **Dependencies**
- [x] Time System #102 
- [x] Weather Events #164 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Investigate how to create visual overlay 1 (Sep 7)
- [x] Design best way to link visual overlays to weather events (Sep 8)
- [x] Implement basic visual overlay for a weather event (Sep 10)
- [x] Create javadocs for overlay (Sep 11)
 
**Completion Deadline:** Sep 12
 
# **Documentation**
- [Main description of feature](../wiki/Weather-and-Climate-System)
 
# **Member**
- Lucas Hicks (@lucashicks1) (Lucas Hicks)
