### ISSUE TITLE
Damage Tool

### ISSUE THREAD

**Issue by v1dyut** [UQcsse3200/2023-studio-1#174]
# **Description**
**Task:** [Damage Tool](#174).
**Feature:** [Implement Alien Animals Advanced](#168)

The goal of this task is to implement a damage tool that the player can use to inflict damage on other entities. This damage tool will use the game physics engine to interact with entities and not the tiles. As one of the key decisions made by the studio was to add additional dimensions to gameplay which involved adding hostile animals, there needs to be a way to damage them. Furthermore, non-hostile animals need to take damage in order for them to drop items on death. The damage tool will most likely take the form of a basic sword in line with the art style used by the [existing tools](#12). 
 
## **Example**
- **Sword**: When the player is holding the sword and uses the interact key, they will swing and deal damage entities within its range.
- **Gun**: When the player is holding the gun and uses the interact key, they will shoot a bullet entity and deal damage entities that come in contact with the bullet.

# **Dependencies**
- [x] Inventory (#5)
- [x] Item Class (#15)

# **Milestones**
As this task has not yet been allocated to a team, no deadlines have been set.
List of steps that need to be completed for this task.
- [x] Create Sword Item (Sep. 25)
- [x] Create Gun Item (Sep. 25)
- [x] Implement Sword Attack Logic (Sep. 28)
- [x] Implement Gun Bullet Spawning Behaviour (Sep. 28)
- [x] Obtain Sprites for new Items (Sep. 30)
- [x] Create Sword Animation (Oct. 1)
- [x] Create Gun Animation (Oct. 2)
 
Completion Deadline: Oct. 3

# **Documentation**
- [Tools Types](https://github.com/UQcsse3200/2023-studio-1/wiki/Tool-Types)
 
# **Member**
- @Bradbowi 
- @pchsa

**Comment by 86LAK** [comment]
Not sure why our team label is attached to this as nothing  was discussed with us.

**Comment by v1dyut** [comment]
> Not sure why our team label is attached to this as nothing was discussed with us.

Hey Lakshan, I created this ticket as a dependency for another feature and was going to talk to your team about this tomorrow during the studio. My understanding is Team 1 is the tool team and this task would be relevant to you.

**Comment by 86LAK** [comment]
Hey we are happy for you guys to implement swords using tools. Everything is there and documented. If you have any questions or anything feel free to ask us. I will leave the team 1 label off this though as we are busy working on different features this sprint.
