### ISSUE TITLE
Animal Interaction Mechanism

### ISSUE THREAD

**Issue by v1dyut** [UQcsse3200/2023-studio-1#176]
# **Description**
**Task:** [Animal Interaction Mechanism](#176).
**Feature:** [Implement Alien Animals Advanced](#168)

The animal team has recognised a need to implement a mechanism by which animals are able to interact with non-tile entities. Features and behaviours the animals exhibit such as being fed food or taking damage require them to interact with non-tile entities. Furthermore, hostile animals would deal damage to plant or player entities.
 
## **Example (optional)**
- **Animal taking damage**: when a weapon is used by the player, the animal should take damage.

# **Dependencies**
- [x] Implement Alien Animals Basic (#4)

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Write InteractionDetector component to detect entities within the players range (Sept. 5)
- [x] Integrate InteractionDetector into ItemActions, to be used when player is holding food to (Sept. 8)
- [x] Write Tests (Sept. 10)
- [x] Write Documentation (Sept. 10)
 
**Completion Deadline:** Aug. 10

# **Documentation**
- [InteractionDetector Wiki](https://github.com/UQcsse3200/2023-studio-1/wiki/Interaction-with-non%E2%80%90tile-entities)
- [JavaDoc](https://uqcsse3200.github.io/2023-studio-1/com/csse3200/game/components/player/InteractionColliderComponent.html)

 
# **Member**
- @pchsa
