### ISSUE TITLE
Animal/Hostile Spawning Behaviour

### ISSUE THREAD

**Issue by v1dyut** [UQcsse3200/2023-studio-1#177]
# **Description**
**Task:** [Animal Spawning Behaviour](#177).
**Feature:** [Implement Alien Animals Advanced](https://github.com/UQcsse3200/2023-studio-1/issues/168)

The entities in the game need to spawn in intelligent and meaningful ways to ensure they add value to the gameplay experience. The entities both need to spawn in valid game areas and spawn periodically as the player may kill them. This applies to both the hostile and passive entities. 

For the spawning behaviour of hostiles, they should only spawn when the player has completed a specific mandatory quest that will allow the player to defend himself. In addition, the spawning behaviour will be similar to minecraft's hostile spawning behaviour. In the day, there will be more normal animals hanging around instead of hostiles. At night, anything can happen when hostiles are out and about. 
 
## **Example**
- **Valid tiles**: The entities should only be spawned on valid tiles, not on [impassable terrain or outside the map](#167).
- **Spawning behaviour**: Entities should spawn at somewhat random (though still meaningful) times to make the game less predictable. Hostile animals may only spawn after a certain number of days have passed to allow the player time to familiarise themselves with gameplay mechanics. More hostiles should be spawned as the player progresses as to increase the difficulty with the players familiarity with the game.

# **Dependencies**
- [x] Game map terrain (#167)
- [x] Time system (#10)
- [x] Quest systems (#387)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1  Discuss with studios idea about spawning animals and hostile. (Sep. 25)
- [x] Step 2 Create the base functionality for the spawner (Sep. 30)
- [x] Step 3 Integrate spawning with hostiles and animals (October. 1)
- [x] Step 4 Write tests for feature (October. 2)
 
**Completion Deadline:** October. 2

 
# **Documentation**
- [Animals](https://github.com/UQcsse3200/2023-studio-1/wiki/Animals/)
 
# **Member**
- Tze Kheng Goh (@UniversalTze)
- Abdullah Badat (@27abdullah)

**Comment by UniversalTze** [comment]
Completed
