### ISSUE TITLE
Astrolotl Adding Oxygen

### ISSUE THREAD

**Issue by v1dyut** [UQcsse3200/2023-studio-1#178]
# **Description**
**Task:** [Astrolotl Adding Oxygen](#178).
**Feature:** [Implement Alien Animals Advanced](#168)

As one of the game's win conditions was to increase the oxygen level on the planet, we decided to allow one of the animals to contribute towards this. The Astroltl is one of the animals implemented in [Basic Alien Animals](#4), as it's current animal includes it blowing bubbles, the animal team decided that when fed, it would increase the planet's oxygen levels. This adds additional gameplay elements and integrates with both the [Plants](#20) and [Oxygen](#149) increasing overall feature cohesion and interactions. There will be a cooldown on how often the Astrolotl can be fed.
 
## **Example**
- **Feeding Astrolotl**: When the Astrolotl is fed it's favourite food, it will increase the oxygen meter.

# **Dependencies**
- [x] Implement Alien Animals Basic (#4)
- [x] Inventory (need to be able to interact with the inventory to get the food). (#5)
- [x] Time service (need to add a cooldown on the Astrolotl). (#10)
- [x] Oxygen meter (need to access the oxygen meter to be able to add to it). (#149)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Aug. 19)
- [ ] Step 2 (Aug. 20)
- [ ] Step 3 (Aug. 23)
- [ ] Step 4 (Aug. 23)
 
**Completion Deadline:** Oct. 4
 
# **Documentation**
- [Animals](https://github.com/UQcsse3200/2023-studio-1/wiki/Animals#animal-species)
 
# **Member**
- @v1dyut 
- @27abdullah
