### ISSUE TITLE
Animal Sound Effects

### ISSUE THREAD

**Issue by v1dyut** [UQcsse3200/2023-studio-1#179]
*in progress*
# **Description**
**Animal Sound Effects:** [Animal Sound Effects](#179).
**Feature:** [Implement Alien Animals Advanced](#168 )

The animals should play sound effects. To create an immersive game, it is important that the player is able to both visually and audially interact with the animals. The sound effects also provide responsive feedback to the player as they interact with animal entities. Sound effects could also be used to signal events that are occurring outside of the player field of vision.

This task is intended for both hostile and non-hostile animals.
 
## **Example**
- **Chicken playing sounds frequently**: The Chicken entity could frequently play sounds similar to a real chicken. 
- **Animal playing sounds when taking damage**: Animals could play distressed sounds when they take damage. This would provide feedback to the player.

# **Dependencies**
- [ ] Implement Alien Animals Basic (#4)

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Aug. 19)
- [ ] Step 2 (Aug. 20)
- [ ] Step 3 (Aug. 23)
- [ ] Step 4 (Aug. 23)
 
**Completion Deadline:** Aug. 23

e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
