### ISSUE TITLE
TerrainCropTileFactory Class

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#18]
# **Task Description**
**Task:** TerrainCropTileFactory Class
**Feature:** #8 

Implements a factory that creates crop tile entities. This factory extends the `TerrainEntityFactory` class. This factory creates entities with the `CropTileComponent` along with other components needed for a crop tile. Additionally, these created crop tile entities will have some default stats (see #TODO). These tiles are entities wherein the player can house plants (see #19 ).  

# **Dependencies**
As this factory extends the abstract `TerrainEntityFactory` it is solely reliant on it's implementation to be complete, before this ticket can be started. Additionally, for the factory to create these entities, the `CropTileComponent` must also be implemented.

- [x] `CropTileComponent` needs to be created - #19
- [x] `CropTileConfig` needs to be created - #28 
- [ ] Crop tile sprites need to be created - #27 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create documentation in the wiki (Aug. 19)
- [x] Add unit testing in the test directory (Aug. 20)
- [ ] Fully implement crop tile factory with completed dependencies (Aug. 24)

**Completion Deadline:** Aug. 26

# **Documentation**
- [Feature description](https://github.com/UQcsse3200/2023-studio-1/wiki/Tile-System)
- [JavaDoc](#TODO)
 
# **Member**
- Lucas (@lucashicks1) (Lucas Hicks)
- Shristi (@shristigupta1408) (Shristi Gupta)
