### ISSUE TITLE
Entity Indicator

### ISSUE THREAD

**Issue by v1dyut** [UQcsse3200/2023-studio-1#182]
# **Description**

A key aspect of gameplay includes the presence of hostile animals that hinder the player performance and work against the game's win conditions. However, due to the large scale of the map, it is important the player is alerted to the presence of hostile animals. In particular, the player must be alerted to the presence of the Plant Eater and Oxygen Eater. These hostiles do not target the player, instead they target the game's two win conditions, food and oxygen. 

An indicator will appear along the edge of the screen that points in the direction of the entity. This will inform the player of a hostile entity which is attacking the games win conditions, and will allow the player to take the necessary actions to stop the hostile entities. The indicator should only show up when the entity is off-screen,  because on-screen entities are already visible to the player. The indicator will be a ! (exclamation mark), as that will clearly indicate that something important is happening.

## Subfeature
- `EntityIndicator` class which handles the UI drawing and logic for determining the indicator position
- Implement a function in `CameraComponent` to check if an entity is currently on camera

## **Example (optional)**
- **Sound effect plays when Oxygen Eater spawns**: When the Oxygen Eater is spawns and is sucking away oxygen, the player hears a 'whooshing' wind sound effect. The player then knows to search for this hostile entity and kill it.
- **Indicator alert for when plants are under attack**: When plants added by the player are under attack, an indictor appears on their screen alerting them of the situation.

# **Dependencies**
- [Implement Hostile Animals](#169) - This feature is a component of the 'Hostile Animals' feature
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Create the UI design for the indicator
- [x] Step 2: Create a class `EntityIndicator` for the UI component
- [x] Step 3: Implement logic in `CameraComponent` for entity detection
- [x] Step 4: Implement calculations in `EntityIndicator` in the `update()` function to update the position of the indicator
- [x] Step 5: Integrate with hostile entities
 
**Completion Deadline:** Oct. 3

## Extras
- [x] Make the indicator more general so it can be re-used. For example, a pointer to a quest objective or npc
 
# **Documentation**
- Hostile Entity Wiki Page
 
# **Member**
- Manav Trivedi (@ManavTriv ) (Manav Trivedi)
