### ISSUE TITLE
Lighting effects - see #207

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#183]
# **Description**
**Feature:** #149 

This task ticket is for implementing dynamic lighting effects in the game based on the in-game time and other in-game events that are occurring. It will be done with Box2dLights as this is provided in the base game-engine. 

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Time System (#102)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Investigate how to use the lighting system (Sep. 7)
- [ ] Implement basic lighting effects (Sep. 8)
- [ ] Make the lighting effects change based on the in-game time (Sep. 11)
 
**Completion Deadline:** Sep. 12

# **Documentation**
- [Main description of feature](../wiki/Lighting-System)
 
# **Member**
- Lucas Hicks (@lucashicks1) (Lucas Hicks)

**Comment by lucashicks1** [comment]
Closed as this has been moved to feature ticket #207
