### ISSUE TITLE
How-to guide for Mission creation to wiki

### ISSUE THREAD

**Issue by Tom-Strooper** [UQcsse3200/2023-studio-1#184]
# **Description**
**Task:** How-to guide for Mission creation to wiki #184
**Feature:** Missions System #148

The how-to guide will show members of different teams how to interact with the `MissionManagerService` and the broader Missions System. It will allow them to add their own `Quest`s and `Achievement`s pertinent to their designed system(s).

# **Milestones**
The following milestones need to be completed:
- [x] Create the how-to guide wiki page (Sep. 6)
- [x] Add relevant details (Sep. 6)
- [x] Update to match studio and Mission system updates following mid-sprint meeting (Sep. 8)
- [x] Create example Achievement and Quest classes (Sep. 8)

**Completion Deadline:** Sep. 8

# **Documentation**
- [Missions System](https://github.com/UQcsse3200/2023-studio-1/wiki/Missions-%28Achievements-and-Quests%29-System)
- [How-to Guide: Creating a Mission](https://github.com/UQcsse3200/2023-studio-1/wiki/How-to-Guide%3A-Creating-a-Mission)
- [How to Guide: Creating a Reward](https://github.com/UQcsse3200/2023-studio-1/wiki/How-to-Guide%3A-Creating-a-Reward)
 
# **Member**
- Tom Strooper (@Tom-Strooper) Tom Strooper
