### ISSUE TITLE
MissionEvent enum

### ISSUE THREAD

**Issue by Tom-Strooper** [UQcsse3200/2023-studio-1#185]
# **Description**
**Task:** MissionEvent enum #185
**Feature:** Missions System #148

The `MissionEvent` enum will contain an enumeration of all possible events which could be triggered on the `MissionManagerService`'s `EventHandler`. The enum will map symbolic representations of the events to the strings which the event handler will use as keys to trigger and listen to events. The purpose of this class will be to reduce the chance of spelling or mistyping errors when members of the studio add event listeners or trigger events for the `MissionManagerService`.

# **Milestones**
The following milestones need to be completed:
- [x] Create the enum class (Sep. 6)
- [x] Create the mapping of enumeration to String representations (Sep. 6)
- [x] Add a few basic example events to the enum (Sep. 6)

**Completion Deadline:** Sep. 6
 
# **Documentation**
- [Missions System](https://github.com/UQcsse3200/2023-studio-1/wiki/Missions-%28Achievements-and-Quests%29-System)
- How-to guide
 
# **Member**
- Tom Strooper (@Tom-Strooper) Tom Strooper
