### ISSUE TITLE
Mission Information Overlay

### ISSUE THREAD

**Issue by vilnor** [UQcsse3200/2023-studio-1#187]
# **Description**
**Task:** Mission Information Overlay.
**Feature:** #135 Alien NPC for checking missions.

Overview
- Pops up stylised like a very large speech bubble next to the alien NPC
- For quests, contains a button for accepting which starts the quest completion timer
- Exact presentation of content dependant on how missions will be set up
 
Implementation Details
- Create new `MissionDisplay` class extending `UIComponent`
- Overly background is the speech bubble, content is added on top depending on if quests or achievements are being viewed
- `MissionDisplay` is added as a component on the NPC Entity (use player entity for testing)
- Listens for an event on the NPC to open - this event will end up being triggered by the player interact key

# **Milestones**
- [x] Base `MissionDisplay` component is created & added to player for testing (Sep. 8)
- [x] Basic quests display added (Sep. 11)
- [x] Basic achievements display added (Sep. 11)
 
**Completion Deadline:** Sep. 12
 
# **Documentation**
- [Missions](../wiki/Missions-%28Achievements-and-Quests%29-System) (collaboration with other teams)
 
# **Member**
- Liam (@liamhemmett) (Liam Hemmett)
- Liv (@vilnor) (Liv Ronda)
