### ISSUE TITLE
CropTileComponent Class

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#19]
# **Description**
**Task:** CropTileComponent Class
**Feature:** #8 

As this game engine uses [ECS](https://github.com/UQcsse3200/2023-studio-1/wiki/Entity-Component-System-(ECS)), we have followed a certain in our approach to creating crop tiles. As a result, we plan to have a crop tile entity which is an entity that stores useful information for growing crops on the tile (eg: water level, soil quality, is fertilised, etc.). This entity will also handle interactions by the player in regard to planting and modifying soil quality, through adding listeners to a variety of events associated with player interaction.
 
## **Example**
- **Water, Soil Quality, and Fertiliser** - The `CropTileComponent` will keep track of a variety of qualities associated with the plot of land on which a crop could be planted. These include water content, the quality of the soil, and whether there is fertiliser currently in the soil. The values of these factors will determine the growth rate of the crop which is planted on the tile

# **Dependencies**
No dependencies at this stage, but will need to incorporate "croptileconfig" file (file extension not decided yet) later for initialising new entities with CropTileComponents.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create documentation in the wiki (Aug. 20)
- [x] Add unit testing in the test directory (Aug. 22)
- [x] Create the component (Aug. 22)
- [x] Add Javadocs (Aug. 23)
 
**Completion Deadline:** Aug. 23

 
# **Documentation**
- [Feature description](https://github.com/UQcsse3200/2023-studio-1/wiki/Tile-System)
- [JavaDoc](#TODO)
 
# **Member**

**Comment by lucashicks1** [comment]
Reopened as plant interaction needs to be completed.

**Comment by lucashicks1** [comment]
Adjust assignees as new ticket was created #73

**Comment by lucashicks1** [comment]
Closed as complete
