### ISSUE TITLE
Add UI for hotkey selection

### ISSUE THREAD

**Issue by adamFittlerUQ** [UQcsse3200/2023-studio-1#199]
# **Description**
**Task:** Add UI for hotkey selection
**Feature:** Implement Player Inventory

The purpose of this task is to give the player a visual feedback when they select an item in their toolbar using the hotkeys.  Initially this will just be a the cell in the table highlighting to show them which item they are currently holding. 

# **Dependencies**
This depends on the implementation of the hokeys working as well as the removing of the itemframe to display items with a frame around them.  Since both of these tickets have been closed it should be good to begin implementation right away. 

- [x] 126-add-inventory-hotkey-numbers
- [x] 160-remove-itemframe-and-use-libgdx

# **Milestones**
List of steps that need to be completed for this task.
- [x] Add selection image to the table using itemslot as a stack (Sep. 7)
- [x] Implement a method to update the backgrounds of the images when an image is selected (Sep. 10)
- [x] Refine implementation and work out bugs and kinks if necessary (Sep. 11)
 
**Completion Deadline:** Sep. 11
 
# **Member**
- Adam Fittler (Stormed #8135) (Adam Fittler)
