### ISSUE TITLE
Plant Component and Plants

### ISSUE THREAD

**Issue by Quarter-645** [UQcsse3200/2023-studio-1#20]
# **Description**
The objective for this sprint is to craft initial plant entities to integrate into the game. To accomplish this, it's necessary to create plant components, plant configs and a plant factory. The plant factory will enable the representation of many plant variants, while the plant components will include methods for managing and retrieving data regarding plant wellbeing, location, type, status, water lever and other attributes.

Within the game, various types of plants will be used. These categories include food, health, repair, defence and production. Food plants will provide the player with food, health plants will provide restorative items, repair plants will mend nearby plants, defence plants will safeguard the player and other plants from enemies, and production plants will specialise in generating oxygen, temperature, etc. Our aim is to showcase a plant class that sets a strong foundation for the basic structure of a plant by the end of this sprint. This will make it easier to create the specialised plants discussed above in subsequent sprints.

# **Dependencies**
- **CropTileComponent** : Dependent for getting waterLevel, soil quality, fertiliser status. #8
-  **Items** : Some plants will drop item #15

# **Milestones**
- [x] Brainstorm some ideas for different plants for each plant type (Food, Health, Repair, Defence, Production)
    - [x] Add this information about types of plants to the Wiki
- [x] Create a 'PlantComponentClass' with some constructors and basic methods.
    - [x] Unit testing 
    - [x] Javadocs 
- [x] Define some properties in 'plant.json' that will be used to initialise different plant types.
- [x] Create config classes for different types of plants
    - [x]  BasePlantConfig
    - [x] PlantConfigs
- [x] Create a base 'PlantFactory' class to allow for the creation of a plant.
    - [x] Unit testing
    - [x] Javadocs
- [x] Plant - Crop Tile Interaction
- [x] Find some sprites to use as placeholders for different plant types.

**Completion Deadline:** Aug. 29

# **Documentation**
- [Plant Component](Plant-Properties-and-Types)
- [Plant Properties and Types](Plant-Component)
- [Plant Configs](PlantConfigs)
- [Creating Plants using PlantFactory.java](Creating-Plants-using-PlantFactory.java)

# **Members**
- Connor (@Quarter-645) (Connor Morrison)
- Tom (@tomedwa) (Tom Edwards)
- Aadya @abhat0 (Aadya)
- Sanchit (@Sanchitjain16) (Sanchit Jain)
- Zebb (@ZebbMcAteer) (Zebb)
- Codie (@kodee-koder) (Codie Chung)
