### ISSUE TITLE
In-game lighting

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#207]
# **Description**
This is a feature ticket for adding lighting into the game. With this feature, the game will have a day/night cycle as well as lighting effects given to different entities. This feature will also involve the creation of various components usable with the ECS system so that entities can have lighting effects directly related to them.

*Note:* This feature ticket was created as an extension of issue #183 

## SubFeature/component (optional)
* `LightService` - an in-game service that houses the `RayHandler` and wraps the `UpdateAndRender()` so that it can be used in the game loops
* `AuraLightComponent` - an aura of light that can be added to entities which is a component-like wrapper for the `PointLight` class given in Box2dLights
* `ConeLightComponent` - a cone light that can be added to entities which is a component-like wrapper for the `ConeLight` class given in Box2dLights allowing for entities to have a *torch-like* light attached to them.

# **Dependencies**
This feature is mainly reliant on an external libgdx framework called [Box2dLights](https://github.com/libgdx/box2dlights/blob/master/README.md) which uses the Box2d physics engine to render lighting effects

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Implement a `LightService` that contains the `RayHandler` that handles light
- [x] Implement `AuraLightComponent` which emits an aura light around an entity 
- [x] Implement `ConeLightComponent` which shines a cone light in a direction from an entity 
- [x] Modify the game rendering so that the UI can be rendered after the light is rendered.
- [x] Add docs for the lighting system

**Completion Deadline:**  Sep 20

# **Documentation**
- [Lighting System](../wiki/Lighting-System)

# **Members**
- Lucas Hicks (@lucashicks1) (Lucas Hicks)

**Comment by lucashicks1** [comment]
Closed as all tasks completed and PR has been merged #339
