### ISSUE TITLE
LightService - lighting system

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#208]
# **Description**
**Feature:** #207 

This task is to create a `LightService` class that contains an instance of `RayHandler` provided by the `Box2dLights` framework in libgdx. This `LightService` class will allow lights to be created from anywhere as the service will be accessible from the `ServiceLocator`.

# **Dependencies**
This task is mainly dependent on the physics engine provided in the base game.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement basic version of `LightService`
- [x] Refine lighting settings for `RayHandler` instance
- [x] Add tests
- [x] Add to the Javadocs

**Completion Deadline:** Sep 20

# **Documentation**
- [Lighting System](../wiki/Lighting-System)

# **Members**
- Lucas Hicks (@lucashicks1) (Lucas Hicks)
