### ISSUE TITLE
AuraLightComponent - lighting system

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#209]
# **Description**
**Feature:** #207 

This task is to create an `AuraLightComponent` which can be attached to entities giving them an aura light in the game world. This aura light will follow the entity as it moves. This is essential a component-style wrapper for the `PointLight` class given in `Box2dLights`.

# **Dependencies**
The completion of this task is dependent on the completion of the `LightService` class which is a service allowing for access to the `RayHandler`.

- [x] #208 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement basic version of the `AuraLightComponent`
- [x] Adjust lighting settings and shadows so the light matches the game theme
- [x] Add tests
- [x] Add to the Javadocs

**Completion Deadline:**  Sep 20

# **Documentation**
- [Lighting System](../wiki/Lighting-System)

# **Members**
- Lucas Hicks (@lucashicks1) (Lucas Hicks)
