### ISSUE TITLE
DirectionalLightComponent - lighting system

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#210]
# **Description**
**Feature:** #207 

This task is to create a `DirectionalLightComponent` which can be attached to entities giving them a *torch-like* light fixture which moves when they move. This will ideally be used by the tractor entity. This is a component-like wrapper for the `DirectionalLight` class given by `Box2dLights`.

# **Dependencies**
The completion of this task is dependent on the completion of the `LightService` class which is a service allowing for access to the `RayHandler`.

- [ ] #208 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Implement basic version of the `DirectionalLightComponent`
- [ ] Adjust lighting and shadows so that they match the game theme
- [ ] Add tests
- [ ] Add to the Javadocs

**Completion Deadline:** TBD

# **Documentation**
- [Lighting System](../wiki/Lighting-System)

# **Members**
- Lucas Hicks (@lucashicks1) (Lucas Hicks)

**Comment by lucashicks1** [comment]
Closed as not needed.

**Comment by lucashicks1** [comment]
Identified as not needed
