### ISSUE TITLE
Rerendering UI - lighting system

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#211]
# **Description**
**Feature:** #207 

A one paragraph description of the task on which you will work. It should briefly explain what will be done (e.g. "Implement an armour component"). This includes textual explanations of the work. (e.g. "`Armour` inherits from `Component` and will add an event handler to the player entity so that the armour takes damage rather than the player. Different types of armour will have different durability. Once the armour is broken (durability reaches zero), it will no longer take damage and more attacks on the player will cause it to lose health.")

# **Dependencies**
The completion of this task is dependent on the completion of the `LightService` class which is a service allowing for access to the `RayHandler`.

- [x] #208 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Investigate how libgdx renders the `ui` entity
- [x] Plan out how the ui will either be rerendered or rendered after the lighting is rendered
- [x] Ensure that other teams are aware of rendering changes to their respective uis
 
**Completion Deadline:**  Sep 20

# **Documentation**
- [Lighting System](../wiki/Lighting-System)

# **Members**
- Lucas Hicks (@lucashicks1) (Lucas Hicks)

**Comment by lucashicks1** [comment]
Closed as complete - https://github.com/UQcsse3200/2023-studio-1/pull/294
