### ISSUE TITLE
Extend Inventory and Toolbar Display Classes

### ISSUE THREAD

**Issue by tristanduncombe** [UQcsse3200/2023-studio-1#221]
# **Description**
After the conclusion of Sprint 1, it was immediately evident that the originals goals of #5 had not come to fruition. Thus, the inventory needed to be extended to ensure that the functionality sought within Sprint 1 was completed. At the completion of Sprint 1, the back-end was mostly complete and the front end displayed the slot for the item texture to be displayed within. The purpose of this ticket is to further develop the front-end display of the inventory to the user and to further refine the back-end and testing.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Create an item slot class (Sept. 2)[#160]
- [x] Improve the back-end logic (Sept. 4)[#154]
- [x] Connect with the player entity (Sept. 6)
- [x] Allow item rearranging (Sept. 12)[#222]
- [x] Improve Unit Tests (Sept. 12)
- [x] Item Selection with HotKey (Sept. 12)[#199]
- [x] Inventory Display Independent (Sept. 12)[#261]

**Completion Deadline:** Sept. 12

# **Extras (optional)**
- [ ] Genericise the Inventory.

# **Documentation**
[Inventory](https://github.com/UQcsse3200/2023-studio-1/wiki/Inventory)

# **Members**
- Tristan Duncombe @tristanduncombe 
- Adam Fittler @adamFittlerUQ 
- Abhinav @Abhinavmohindersingh 
- Nimesh Garg @nimeshgarg 
- Leonard Guo @mashoo12

**Comment by nimeshgarg** [comment]
#199 
#261 
#222 
#160 
#154
