### ISSUE TITLE
Item Rearranging

### ISSUE THREAD

**Issue by tristanduncombe** [UQcsse3200/2023-studio-1#222]
# **Description**
**Task:** [Item Rearranging](#3).
**Feature:** [Extend Inventory](#221 )

This task is to allow the user to rearrange items in their inventory. It should use the powers of the draggable class from LibGDX to enable future iterations and use the premade functions within Inventory to adjust the internal inventory position

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Adjust Back-end of Inventory (#154)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Allow the use to drag an item slot (Sept. 10)
- [x] Adjust the inventory position hashmap based on user dragging (Sept. 11)
 
**Completion Deadline:** Sept. 11
 
# **Documentation**
- [Inventory](https://github.com/UQcsse3200/2023-studio-1/wiki/Inventory)
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Tristan Duncombe @tristanduncombe Tristan Duncombe
