### ISSUE TITLE
Completing Tile System Wiki

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#26]
# **Description**
**Task:** Completing Tile System Wiki
**Feature:** #8 

This task ticket is for completing the game wiki for the tile system. Since this system is used by multiple different feature teams, it is important that every team is able to understand its implementation, and this is best represented in a wiki page. This wiki page should include an overview of the current system implementation, the design considerations taken, the process flow of the system and the individual elements that make up the system.

# **Dependencies**
To fully complete this wiki page, all of the tasks that are related to the specific implementation of the tile system must be completed. These are as follows:

- [x] Abstract Factory for creating terrain entities needs to be created #16
- [x] Factory that creates crop tile entities needs to be created #18 
- [x] Crop tile component that is added to crop tile entities needs to be created #19 
- [x] Crop tile config needs to be created to store crop tile default values #28
 
# **Milestones**
- [x] Outline basis of tile system in the wiki (Aug. 18)
- [x] Complete relevant task dependencies for the tile system (Aug. 25)
- [x] Complete wiki sections on newly developed system elements 3 (Aug. 26)
- [x] Finalise wiki information for final implementation 4 (Aug. 27)
 
**Completion Deadline:** Aug. 27
 
# **Documentation**
- [Tile System Wiki](https://github.com/UQcsse3200/2023-studio-1/wiki/Tile-System)
 
# **Member**
- Lucas Hicks (@lucashicks1) (Lucas Hicks)
- Tom Strooper (@Tom-Strooper) (Tom Strooper)
- David Jeong (@DonghyugDavidJeong) (Donghyug David Jeong)

**Comment by lucashicks1** [comment]
Added sequence diagrams for crop tiles wiki [here](https://github.com/UQcsse3200/2023-studio-1/wiki/Crop-Tiles).

**Comment by lucashicks1** [comment]
Closed as complete
