### ISSUE TITLE
Inventory Display Independent

### ISSUE THREAD

**Issue by Abhinavmohindersingh** [UQcsse3200/2023-studio-1#261]
# **Description**
**Task:** Remove Reliance of InventoryDisplay
**Feature:** #5 

Currently, the InventoryDisplay class relies on the New Inventory mechanism. This dependency needs to be removed. Instead, InventoryDisplay should be connected directly to the Player's inventory which is initialized at the start of the game.
 
# **Dependencies**
1. NewInventory

InventoryDisplay should no longer have any references to New Inventory.
Items added to or removed from the Player's inventory should be immediately and accurately reflected in InventoryDisplay.
No regressions should be introduced in the process; existing game functionality outside of this scope should remain unaffected.
 
# **Milestones**
List of steps that need to be completed for this task.

- [x] Remove any references or dependencies on New Inventory from the InventoryDisplay class.
- [x] Establish a connection between InventoryDisplay and the Player's inventory.
- [x] Ensure that the Player's inventory, which is initialized at the start, is accurately reflected in InventoryDisplay.
 
**Completion Deadline:** Sep. 02
 
# **Documentation**
Inventory 
 
# **Member**
- Abhinav(@Abhinavmohindersingh )
