### ISSUE TITLE
Tile Sprites

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#27]
# **Description**
**Task:** Crop Tile Sprites
**Feature:** [Tile System](#8)

Create the sprites for the crop tiles. These tiles will have a different appearance based on various factors. The sprite will look different based on the water quality, whether the tile is occupied by a plant or whether there is fertiliser on the tile.
 
## **Example (optional)**
- **Water Level**: Depending on the water level the crop tile will have a different shade. The higher the water level, the darker the shade. 
- **Fertiliser**: When a player adds fertiliser to the crop tile the sprite will change to reflect this. For example, having yellow specks on the crop tile sprite.

# **Dependencies**
- [x] CropTileComponent
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Draft the designs (Aug 18)
- [x] Step 2 Create the assets (Aug 20)
- [x] Step 3 Integrate the assets into the code (Aug 24)
- [x] Step 4 Create some wiki documentation more geared to the user - what the various looks represent.
 
# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2023-studio-1/wiki/Crop-Tiles)
 
# **Member**
- @charliebkw

**Comment by lucashicks1** [comment]
Tasks have been completed, and hence issue is now closed.
