### ISSUE TITLE
Create Crop Tile Configs

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#28]
# **Description**
**Task:** Create Crop Tile Configs
**Feature:** #8 

This task involves setting up configurations for crop tiles in our farming game. For each tile, the setup will specify the following characteristics - the initial soil quality and the initial water content. It updates both the `CropTileConfig` and the corresponding configuration in `cropTile` json file. The `TerrainCropTileFactory` (#18) and `CropTileComponent`(#19) will be integrated with this task. It allows the player to interact with the crop tile and perform events like watering, fertilising and planting.
 
## **Example**
Each tile has properties like water content and soil quality, which influence plant growth. Players can water a tile to increase its water content, fertilise it to enhance soil quality, or plant crops.

# **Dependencies**
No dependencies.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create documentation in the wiki (Aug. 21)
- [x] Create `CropTileConfig` (Aug. 23)
- [x] Create `cropTile` json file (Aug 23)
- [x] Add JavaDoc (Aug 24)
 
**Completion Deadline:** Aug 24
 
# **Documentation**
- [Feature description](https://github.com/UQcsse3200/2023-studio-1/wiki/Tile-System)
- [JavaDoc](#TODO)
 
# **Member**
- Shristi Gupta (@shristigupta1408 ) (Shristi Gupta)

**Comment by lucashicks1** [comment]
Closed as done
