### ISSUE TITLE
Tractor

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#29]
# **Tractor Base Functionality**
**Task:** Complete the tractor.
**Feature:** Adding farm tools #7 

Imagine a farming game where you can't sit back and on your tractor and crack open a cold one. Well don't worry we got this covered! A tractor will be added to the game to enhance the player's experience by increasing the ceiling for productivity and increasing the amount of money you can make, whilst looking good on a tractor.

# **Dependencies**

- [x] Make the Tool Class #17 
 
# **Milestones**
This task is optional as per our feature task #7 so there won't be any hard deadlines.

- [x] Step 1 (Aug. 19): Create base factory for tractor
- [x] Step 2 (Aug. 21): Make base animations 
- [x] Step 3 (Aug. 25): Implement player getting in the tractor and moving in the tractor
- [ ] Step 4 (Aug. 28): Full animations done
- [ ] Step 5 (Aug 31) (Optional): Interactions with Tiles (Tilling, watering the ground etc.)
 
**Completion Deadline:** Aug. 31

# **Documentation**

 
# **Member**
- Jackson Trenerry @JTrenerry 
- Lakshan Chandrasekara @86LAK

**Comment by p-lahanas** [comment]
Tractor <sup>TM</sup>

**Comment by JTrenerry** [comment]
Note to self: Tractor starts un-muted and player starts muted, needs to be flipped, after that should be okay

**Comment by 86LAK** [comment]
After some testing found the following bugs
- when moving and exiting the tractor this results in movement of the character and tractor to break. Character is stuck in a direction and the tractor stuck moving in the opposite direction. This was tested with the tractor moving left on screen or using  "A"  key. The tractor continued heading left after the player exits the vehicle and the player continues in the opposite direction. 

-player can enter vehicle from anywhere by pressing F. The player should only be able to enter the tractor by standing next to it.

**Comment by JTrenerry** [comment]
second bit isn't implemented yet, did you hold 'A' and the player moved right?

**Comment by 86LAK** [comment]
yeh

**Comment by JTrenerry** [comment]
Okay I know the solution to tractor moving, but player im stumped on

**Comment by JTrenerry** [comment]
Tractor will continue unto sprint 2
