### ISSUE TITLE
SaveLoadService breaking everytime someone touches EntityType

### ISSUE THREAD

**Issue by 86LAK** [UQcsse3200/2023-studio-1#290]
# **Description**
SaveLoadService breaks everytime someone adds or unexpectedly removes an EntityType. 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix Documentation of SaveLoadService
- [x] Junit tests for EntityType
- [x] Fix filterEntities function logic. 
 
**Completion Deadline:** ASAP

# **Documentation**
- https://github.com/UQcsse3200/2023-studio-1/wiki/Save---Load-game
 
# **Member**
- Shanon Lakshan Chandrasekara @86LAK

**Comment by 86LAK** [comment]
I semi fixed the doco https://github.com/UQcsse3200/2023-studio-1/wiki/Save---Load-game

Am I missing any steps for new entities and components 
@JTrenerry ?

**Comment by JTrenerry** [comment]
@86LAK please has capital L on last line, other than that it is good

**Comment by 86LAK** [comment]
@JTrenerry fixed the typo ty for spotting it.
