### ISSUE TITLE
End Credits 

### ISSUE THREAD

**Issue by adamFittlerUQ** [UQcsse3200/2023-studio-1#293]
# **Description**
Once the player has successfully completed the game with either a win or a loss they will be greeted by the end credits screen, this will be similar to the intro screen and serve as a nice conclusion to the story and the gameplay.  This could include 3 major parts, the story wrap up, players in game stats such as number of plants placed etc, and finally a credits screen for the team members who developed the game. 

# **Dependencies**
- Win/Lose Timer 
- Win/Lose Conditions

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Implement Basic End Credits Screen (Sep. 15)
- [x] Implement Outro Story Wrap-up (Sep. 17)
- [x] Polish and Finalise End Credits (Sep. 25)
- [x] Complete End Credits Wiki (Sep. 27)

**Completion Deadline:** Sep. 27

# **Documentation**
- [Lose Screen](https://github.com/UQcsse3200/2023-studio-1/wiki/Menu-Screens#lose-screen)
- [Win Screen](https://github.com/UQcsse3200/2023-studio-1/wiki/Menu-Screens#win-screen)
- [Credits Screen](https://github.com/UQcsse3200/2023-studio-1/wiki/Menu-Screens#end-credits-screen)

# **Members**
- Adam Fittler (adamFittlerUQ)
