### ISSUE TITLE
Implement Basic End Credits Screen

### ISSUE THREAD

**Issue by adamFittlerUQ** [UQcsse3200/2023-studio-1#295]
# **Description**
**Task:** Implement Basic End Credits Screen
**Feature:** End Credits

Implementation of a fundamental end credits screen that displays after the player wins or loses the game.  This will be a base to build upon in future task tickets for the actual content of the ending of the game but for now we just need a screen to work on.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a new package and class for the end credits display (Sep. 14)
- [x] Get the screen to display upon the win/loss conditions of the game (Sep. 15)
- [x] Experiment with an ending text scroll (Sep. 15)

**Completion Deadline:** Sep. 15
 
# **Documentation**
- [End Credits Wiki](https://github.com/UQcsse3200/2023-studio-1/wiki/End-Credits)

# **Members**
- Adam Fittler (adamFittlerUQ)
