### ISSUE TITLE
Save Load Maintenance

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#296]
### **Feature:** #125

Saving and loading needs a lot of maintenance as when new features they need to be added or ignored to the save load methods and as such this feature ticket will be used to keep track of what was been saved and what is to be saved. The list below in milestones will not include those that were completed as part of the original feature ticket #125. Will be adding the label for any team that makes work that needs to be saved in order to better collaborate.
 
# **Milestones**
List of steps that need to be completed for this task. This will be expanded as more things that need to be saved are made.
- [x] Step 1 (TBD) - Fix saving inventory (waiting for inventory rework)
- [x] Step 2 (Sep. 26) - Add saving quests (waiting for additional features)
- [x] Step 3 (Sep. 26) - Fix saving weather events (Not correctly saving it at the moment)
- [x] Step 4 (Sep. 14) - Fixes the plant naming convention to match the ones in FactoryService.
- [ ] Step 5 (TBD) - Implement saving health (waiting for health to be made)
- [x] Step 6 (Sep. 21) - Saves minutes from time service
- [x] Step 7 (Sep. 26) - Redo save/load to use cascading read calls
- [x] Step 8 (Oct 3) - Saves/loads placeables
 
**Completion Deadline:** N/A
 
# **Documentation**
- https://github.com/UQcsse3200/2023-studio-1/wiki/Save---Load-game
 
# **Member**
Jackson Trenerry (@JTrenerry)

**Comment by JTrenerry** [comment]
As per above inventory is fixed so removing team 8 tag for now....

**Comment by JTrenerry** [comment]
nevermind did not fix

**Comment by lucashicks1** [comment]
Will get onto weather events soon. I'll make a PR this weekend implementing the methods you suggested for saving/loading.

**Comment by JTrenerry** [comment]
Readded team 8 due to inventory's lack of way to remove all items, tried most methods I know of and it clears the inventory array but the player somehow still has access to the items and they are still displayed?

**Comment by JTrenerry** [comment]
> Will get onto weather events soon. I'll make a PR this weekend implementing the methods you suggested for saving/loading.

I completely forget what I asked you to make? Weather seems okay I just have to iron some stuff out. Quests on the other hand needs more and I believe I asked for some stuff for it.

**Comment by JTrenerry** [comment]
Since this is a never ending cycle :(

**Comment by JTrenerry** [comment]
WE BACK!!!

**Comment by 86LAK** [comment]
Crazy times

**Comment by JTrenerry** [comment]
IM BACK BABY

**Comment by JTrenerry** [comment]
Save load will no longer be continued by team 1.
