### ISSUE TITLE
Tractor Animations

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#297]
# **Task:** Tractor Animations.
# **Feature:** #7 

It is about time that tractor is completed and finally up to the standard of the other art and animations in the game. At the moment there is only one direction for movement animation and no visual feedback for the different modes in the tractor. This task will further progress the impact of using the tractor by allowing the player to really see the tractor in all its glory. It will add different tools at the front and back of the tractor (currently in the art but not removing and adding on when it should) and will give the tractor 4 directional animations to reinforce player input with visual effects.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Sep. 26) - Bi-directional movement with correct tools
- [x] Step 2 (Sep. 29) - Idle frames for when the tractor isn't moving or the player is not in it (for all four directions).
- [x] Step 3 (Sep. 29) - Four way directional movement
- [x] Step 4 (Sep. 29) - Triggers and correct animations playing when they should be
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
- https://github.com/UQcsse3200/2023-studio-1/wiki/Tractor
 
# **Member**
- Jackson Trenerry @JTrenerry

**Comment by JTrenerry** [comment]
Added team 2 since they said they would pack my textures for me.

**Comment by JTrenerry** [comment]
Extended this work to better align the harvesting and tilling (gets the visually correct tiles) will need to wait for the map tile resizing until it is set in stone, thus will not make a PR til then.
