### ISSUE TITLE
Final Plant Functionality, Hunger, Progress Bar, Plant Info UI

### ISSUE THREAD

**Issue by kodee-koder** [UQcsse3200/2023-studio-1#301]
# **Description**
Plant harvesting:
On harvest, a plant will drop consumables and item seeds a user can add to their inventory. This will allow the user to continue planting the given plants and make use of the other drops. Additionally, the sprites for plants will be finalized.

Plant effects:
Plants will have an area of effect based on their plant type. All plants will have an impact on the game's oxygen level. This will add complexity to the game-play and add purpose to the various plant types.

Hunger functionality: 
The player will have a hunger bar that will deplete with time. Plant items that are dropped on harvest will be assigned values that will full up the hunger bar.

Progress bar and day counter:
Will indicate to the user the remain time of their game. This will be set to 30 in-game days. There will be a UI and day counter displaying this progress that will be updated once a day.

Oxygen for Plants:
Plants will be able to produce or consume oxygen depending on the type of plant and the growth stage of the plant. Plants will
produce oxygen when they are alive and healthy. When a plant is decaying it will consume oxygen which will encourage the player to remove decaying plants before they become an issue.

Plant Information UI:
When the player hovers their mouse cursor over a plant the relevant information about this plant will be shown on screen.
The information shown will include:
    - Plant name
    - current growth stage
    - water level/ideal water level
    - health/max health

# **Dependencies**
- [x] Team 2 has agreed to provide some seed sprites.

# **Milestones**
- [x] Fixing harvesting(Oct. 3)
- [x] Enhance Growth Stages (Sep. 24)
- [x] Include finalised seed sprites (Sep. 19)
- [x] Oxygen for plants (Produce/Consume) (Oct. 3)
- [x] Implementing plant effects (Oct. 3)
- [x] Hunger functionality (Oct. 3)
- [x] Progress bar and day counter (Oct. 3)
- [x] Plant information UI (Sep. 24)
- [ ] Ensure the plant component is able to be saved/loaded properly (Oct. 3)

**Completion Deadline:** Oct. 3

# **Extras (optional)**
- [ ] Temperature 

# **Documentation**

# **Members**
* Connor (@Quarter-645) (Connor Morrison)
* Tom (@tomedwa) (Tom Edwards)
* Aadya @abhat0 (Aadya)
* Sanchit (@Sanchitjain16) (Sanchit Jain)
* Zebb (@ZebbMcAteer) (Zebb)
* Codie (@kodee-koder) (Codie Chung)
