### ISSUE TITLE
Progress Bar and Day Counter

### ISSUE THREAD

**Issue by Quarter-645** [UQcsse3200/2023-studio-1#302]
# **Description**
**Task:** Progress Bar and Day Counter
**Feature:**  #301

This task is to build a progress bar that will be display a rocket going from earth to the planet we are on, getting closer each day. This will also display the day that the player is currently on. The day will start at 12am everyday.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Time System (#10)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create Animation (Sep. 24th)
- [x] Implement functionality (as days progress animation progresses) (Sep. 26th)
- [x] Fix Sanity (Sep. 28th)
 
**Completion Deadline:** Oct. 01
 
# **Documentation**
- [JavaDoc] Javadoc

# **Member**
- Connor (@Quarter-645) (Connor Morrison)
- Codie (@kodee-koder ) (Codie Chung)
