### ISSUE TITLE
Fences and Gates

### ISSUE THREAD

**Issue by p-lahanas** [UQcsse3200/2023-studio-1#303]
# **Description**
Add fences and gates to the game. A fence is a place-able object which acts as an obstacle (walking entities in the map are unable to pass through). A gate is similar to a fence but is able to be opened (action key). 

## SubFeature/component
Fences - Block movement of all entities (Helps keep your animals in check). Can be a reward from taming animals;
Gates - So you can enter the animals pen to feed them and say hi. Can be a reward from taming animals;

# **Milestones**
- [x] Goal 1 (Sep. 24) - Placeable framework completed,
- [x] Goal 2 (Sep. 27) - Fences and Gates completed,
- [x] Goal 3 (Sep. 29) - Junit Tests written

**Completion Deadline:** Oct. 4
# **Dependencies**
- Object placing framework

# Documentation
https://github.com/UQcsse3200/2023-studio-1/wiki/Placeables

# **Members**
Peter Lahanas (@p-lahanas)
