### ISSUE TITLE
Hunger Functionality

### ISSUE THREAD

**Issue by Sanchitjain16** [UQcsse3200/2023-studio-1#304]
# **Description**
**Task:** [Hunger Functionality] (#304).
**Feature:** [Final Plant Functionality, Hunger, Progress Bar] (#301)

Implement the hunger functionalities for plants and the player. By adding and introducing the maximum value a player can get by eating the certain food plant which help the player to get energy. There would be a hunger bar over the player indicating how hungry is it at a particular time within the game. This also includes the physical values for the player hunger integrated with the hunger bar. Each food plant will have different values for the amount the hunger that can be fulfilled by the player.

# **Dependencies**

# **Milestones**
- [ ] Creating new variable for adding values for food (Sept. 21)
- [ ] Introducing the player hunger  (Sept. xx)
- [ ] Creating a hunger bar for the player which indicates the hunger level of the player at a particular time in the game (Oct. xx)
 
**Completion Deadline:** Oct. 3

 
# **Documentation**
- [Plant Component] (https://github.com/UQcsse3200/2023-studio-1/wiki/Plant-Component)
- [Plant Properties and Types] (https://github.com/UQcsse3200/2023-studio-1/wiki/Plant-Properties-and-Types)
- [JavaDoc] (https://uqcsse3200.github.io/2023-studio-1/com/csse3200/game/components/plants/PlantComponent.html)
 
# **Member**
- Sanchit (@Sanchitjain16 ) (Sanchit Jain)
- Connor (@Quarter-645) (Connor Morrison)
- Tom (@tomedwa) (Tom Edwards)
