### ISSUE TITLE
Player Sprites and Animations

### ISSUE THREAD

**Issue by bunnyycat** [UQcsse3200/2023-studio-1#31]
# **Description**
**Task:** Player Sprites and Animations(#31)
**Feature:** Player Sprite & Animation(#2)

Create assets for the player including the following:
- Standing still (front, back, left right)
- Walking animation (front, back, left, right)
- Running animation (front, back, left, right)
- Idle animation - blinking eyes (front, left, right)
- Idle animation - dozing off (front, back, left, right)
- Idle animation - yawning (front, back, left, right)

# **Dependencies**
- Colour palette
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Colour palette created and posted in the server for a vote (Aug. 23)
- [x] Add colour palette to art guidelines page in wiki (Aug. 25)
- [x] Standing still sprites (Aug. 23)
- [x] Walking animation (Aug. 25)
- [x] Idle animations (blinking, yawning) (Aug. 27)
- [x] Idle animations (dozing off) (Aug. 27)
- [x] Running animation (Aug 28)
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- [Animations](https://github.com/UQcsse3200/2023-studio-1/wiki/Animations)
- [Art Guidelines](https://github.com/UQcsse3200/2023-studio-1/wiki/Art-Guidelines)
 
# **Member**
- Ali (@bunnyycat ) (Ali Spanevello)
