### ISSUE TITLE
Sprinkler System

### ISSUE THREAD

**Issue by cmp6** [UQcsse3200/2023-studio-1#310]
# **Description**
**Part of the [Quality of life and some place-able items](#292) feature.**
**Continued in [A Cleanse](#544) feature.**

Adds sprinklers to automate watering of the ground. This feature aims to add a fun, technical element to gameplay.

The sprinkler system consists of 2 placeable items, the pump, and the sprinklers. The pump is essentially the water source of the sprinklers. The sprinklers behave like plumbing, for watering to occur from any given sprinkler it must be connected to the pump via other sprinklers. 

## Example
The following is a rough sketch diagram of how the system comes together:
With area 1 illustrating the **pump**, area 2 - the individual **unconnected sprinklers**, and 3 - the **connected pump and sprinklers**.

![sprinkler_diag](https://github.com/UQcsse3200/2023-studio-1/assets/93989941/284e6d88-f85c-4f09-a35e-61151d575683)

**The sprinklers in area 2 will have no functionality because they are not connected to the pump in any way. However, the sprinkers in area 3 will water the ground in regular intervals as they are connected to the pump.**

## Obtaining the system in-game
The pump and sprinklers will be made available to the player via the quest-reward system. With the pump and minimal sprinklers available as a reward from a single quest, then more sprinklers available from subsequent quests.

## Implementation
The sprinkler system will be built upon the PlaceableFactory.

## **Dependencies**
- [x] [Quality of life and some place-able items](#292) - PlaceableFactory
- [x] Texturing
- [x] Quest integration
- [x] Save & Load compatibility 
- [x] #614

# **Milestones**
### Sprint 3
**Completion Deadline:** Sep. 30
- [x] Add pump and tubing as placeable (Sep. 16)
- [x] Simple texturing for in-game testing (Sep. 17)
- [x] Add watering functionality (Sep. 19)
- [x] Add dynamic updates (newly placed or destroyed sprinklers effect other sprinklers) (Sep. 25)
- [x] Add save & load compatibility (Sep. 30)
- [x] Write tests for sprinkler logic

### Sprint 4
**Completion Deadline:** Oct. 16
- [x] fine tune watering to suit all unique plants.
- [x] Add comprehensive unit testing

# Current Bugs:
- breaking a pump or sprinkler that is connected to 4 other sprinklers, with at least 1 other spanning sprinkler connected, can cause two sprinklers on either the north or south to remain powered when they shouldn't be.
Once a sprinkler is placed in one of these two sprinklers vicinity the sprinklers update and expected bahviour is restored.
~~It is quite a specific edge case and for that reason it's solution will not be actively explored until sprint 4.~~
+ My team believes this to be an engine bug, therefore we will not be fixing it

# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2023-studio-1/wiki/Placeables)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Cohen (@cmp6) (cmp1)
