### ISSUE TITLE
Mouse Fixes and Enhancements

### ISSUE THREAD

**Issue by 86LAK** [UQcsse3200/2023-studio-1#311]
# **Description**
**Task:** Mouse Fixes and Enhancements
**Feature:**  #292

For this task, we will be enhancing player interaction in the game with the mouse. Currently, there's a lack of accuracy with mouse interactions. To address this issue, we plan to implement a feature that highlights the tile currently being targeted. Additionally, we aim to improve the visual integration of the interactive tile with the overall game environment to create a smoother and more immersive player experience. This task also involves addressing various bugs related to mouse input and ensuring that gameplay with the mouse is accurate and fluid. These improvements will contribute to a more intuitive and enjoyable gaming experience for our players.

# **Dependencies**
n/a
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fixing accuracy of mouse clicks (19 sept)
- [x] Implementing visual tile highlighting on current targeted tile (27 sept)
- [x] Documentation of Changes and any wiki updates (30 sept)
- [x] junit tests (30 sept)

 
**Completion Deadline:** Sep 30
 
# **Documentation**
- Game Controls Page
- https://github.com/UQcsse3200/2023-studio-1/wiki/Interaction-with-non%E2%80%90tile-entities
- https://github.com/UQcsse3200/2023-studio-1/wiki/TerrainTile-Class
- 
 
# **Member**
- Shanon Lakshan Chandrasekara @86LAK

**Comment by 86LAK** [comment]
The tasks will be ticked as they are completed :)

**Comment by 86LAK** [comment]
I have ticked the box @JTrenerry. Just got documentation left :)

**Comment by 86LAK** [comment]
https://github.com/UQcsse3200/2023-studio-1/wiki/Player-Highlight-Selection#high-level-overview-of-how-it-works
