### ISSUE TITLE
Chests

### ISSUE THREAD

**Issue by LiamAnd** [UQcsse3200/2023-studio-1#313]
# Description
**Feature:** [Quality of life and some place-able items](#292 )

The implementation of the chest will allow players to store and organise excess items they do not wish to carry around. The chest will be a place-able item that will contain its own inventory similar to the players. Players then can interact with a placed chest using 'E', allowing the player to drag and drop items in and out of the chest.

# **Dependencies**

- [x] [Place-able Framework](#292 )
- [x] #320
 
# **Milestones**
**Sprint 3**
- [x] Place-able Chest Object (Sep. 17)
- [x] Temporary Chest Sprites  (Sep. 22)
- [x] Documentation (Sep. 30)
 
**Completion Deadline:** Sep. 30

**Sprint 4**

- [x] Finalised Chest Sprite (Oct. 18)
- [x] Functioning Chest Inventory  (Oct. 18)
- [x] J-Unit Tests (Oct. 18)

**Completion Deadline:** Oct. 18
 
# **Documentation**
- [Inventory Wiki](../wiki/Inventory)
- https://github.com/UQcsse3200/2023-studio-1/wiki/Placeables
 
# **Member**
- Liam Anderson (@LiamAnd )

**Comment by tristanduncombe** [comment]
We're working on a lot of changes to inventory, so we're implementing the backend for this to work.

Let me know if you have any issues, I'll let you know when we've successfully genericised the inventory.

**Comment by JTrenerry** [comment]
Postponed due to inventory rework taking longer than expected.

**Comment by JTrenerry** [comment]
Due to the way the chest works there is not a need for j-unit tests for it as it uses already tested code.

**Comment by JTrenerry** [comment]
Just needs a sound then this ticket can be shut @86LAK @p-lahanas
