### ISSUE TITLE
command - add weather event

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#317]
# **Description**
**Feature:** [Terminal Game Commands](#60)

Task ticket for adding weather commands into the game allowing the player to create a weather event. This will be mainly useful for development (save/load, testing other entity interactions, etc.) 

# **Dependencies**

- [ ] #149 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement the command (Sep 16)
- [x] Add Javadocs (Sep 16)
- [x] Add testing (Sep 16)
- [x] Add to wiki (Sep 16)
 
**Completion Deadline:** Sep 16

# **Documentation**
- [Wiki Page](../wiki/Debug-Terminal)
 
# **Member**
- Lucas Hicks (@lucashicks1 ) (Lucas Hicks)
