### ISSUE TITLE
Weather Event Visual Effects

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#319]
# **Description**

Alongside weather events affecting the climate of the game (temperature and humidity), particle effects should be visible on the player's screen when they are occurring. This will remove the need for the current `WeatherDisplay` and will make the UI significantly cleaner.

## SubFeature/components
- Adjust game lighting during solar surge/lightning
- Particle effect factory that creates particle effects for weather events

# **Dependencies**

- #207 
- #102 
- #149 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Investigate how particle effects work in libgdx [here](https://libgdx.com/wiki/graphics/2d/2d-particleeffects) (Sep. 18)
- [x] Create a `ParticleService` which will keep track of and manage all of the particle effects that occur in the game (Sep 20.)
- [x] Create `ParticleEffectWrapper` which wraps all of the necessary information that is required for libgdx to render a particle effect (Sep 22.) ~ If this wrapper isn't needed this can be removed
- [x] Draw basic particle effect that is provided by libgdx [here](https://www.youtube.com/watch?v=3OwIiELYa70)
- [x] Adjust the `AcidShowerEvent` and the `SolarSurgeEvent` by including the `startEffect()` and `stopEffect()` methods
- [x] Adjust the `ClimateController` so that it calls `startEffect()` and `stopEffect()` when updating the current weather event

**Completion Deadline:** October 1

# **Extras (optional)**
- [ ] Particle effect component

# **Documentation**
- [Weather and Climate System](../wiki/Weather-and-Climate-System)
- [Particle Effects](../wiki/Particle-Effects)

# **Members**
- Lucas (@lucashicks1) (Lucas Hicks)

**Comment by JTrenerry** [comment]
Hey, just a quick question about weather events, is there any visual cue or somehow I can tell that they are going on without the display at the moment?

**Comment by lucashicks1** [comment]
> I

Not at the moment, that's why we are adding the visual effects. Maybe in sprint 4 we could integrate time, weather and climate stats in the one ui component?

**Comment by lucashicks1** [comment]
> You should be able to tell by the indicator on the left

He is asking whether there is a way to tell without using the display

**Comment by shristigupta1408** [comment]
My bad, got confused by the "is there any visual cue"
