### ISSUE TITLE
Implement Outro Story Wrap-up

### ISSUE THREAD

**Issue by adamFittlerUQ** [UQcsse3200/2023-studio-1#321]
# **Description**
**Task:** Implement Outro Story Wrap-up
**Feature:** End Credits 

Implementation of the basic story conclusion for the game based off of if the game is won or lost.  There should be separate winning and losing story text as well as visuals, and a button allowing the player to return to the main menu and begin a new game.   This should provide the player with a stratifying conclusion to the game and bring the entire experience full circle.  
 
# **Dependencies**
- [x]  Implement Basic End Credits Screen
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Write up story text for win/lose (Sep. 17)
- [x] Implement separate win/lose credits (Sep. 18)

**Completion Deadline:** Sep. 18

# **Documentation**
- [End Credits Wiki](https://github.com/UQcsse3200/2023-studio-1/wiki/End-Credits)
 
# **Member**
- Adam Fittler (adamFittlerUQ) (Adam Fittler)
