### ISSUE TITLE
Player Ship

### ISSUE THREAD

**Issue by yetanothercarbot** [UQcsse3200/2023-studio-1#327]
# **Description**

The Player Ship aims to bring together most of the systems implemented in our game in a way that gives the player purpose. It will extend on already implemented tiles, items, rewards & entitites, and will work closely with the quest framework in hopes of creating a meaningful player experience.

A full high level description can be found on the [Player Ship](../wiki/Player-Ship) wiki page.

## Lore

This is the ship with which the player crash-landed on this planet while escaping earth. As such, while not fully destroyed, there are pieces damaged or missing - the player must trade with the aliens through the questgiver to receive parts to repair their ship, or find them by digging on the map.

## Subfeature

- `Ship` Entity - must include various states of disrepair for the player to repair it
    - `ShipProgressComponent` - tracks the state of the ship's repair
    - `ShipTimeSkipComponent` - allows the player to 'sleep' through the night, usage unlocked after first ship repair
    - `ShipAnimationController` - manages the ship's sprite
- `ShipPartItem` - these are the parts required to repair the ship
- `ShipPartClueItem` - these contain a clue or location as to how or where the player can find the part
- `ShipPartTile` - this is where the player can find hidden part items
- `ShipDebris` Entity - generated around the crashed ship on start of game, can be removed with a shovel. also marks where ship part tiles are.

# **Dependencies**

- Time system, for the bed (time skip)
- Quests for story progression to fix the ship

# **Milestones**

- [x] Ship entity - basic factory created (24 Sep.)
- [x] Ship Progress Component (24 Sep.)
    - [x] Tests (30 Sep.)
- [x] Ship Time Skip Component (27 Sep.)
    - [x] Tests (30 Sep.)
- [x] Ship Animation Controller (27 Sep.)
    - [x] Tests (30 Sep.)
- [x] Ship Part Items (27 Sep.)
- [ ] Ship Part Clue Items (27 Sep.)
    - [ ] Tests (30 Sep.)
- [x] Ship Part Tile (27 Sep.)
    - [x] Tests (30 Sep.)
- [x] Ship Debris Entity (27 Sep.)
    - [x] Tests (30 Sep.)

**Completion Deadline:** 3 October 2023

# **Extras (optional)**

- [x] Ship Light Component - ship can emit a light after a certain amount of repairs is made
- [ ] Ship UI Component - for better interaction with ship, can show progress, allow sleeping, applying ship repairs, etc.
- [ ] Enterable ship
- [ ] Completely repaired ship allows movement to new game area

# **Documentation**

- [Player Ship](../wiki/Player-Ship)

# **Members**

- Liv (@vilnor) (Liv Ronda)
- Wilko (@yetanothercarbot) (Wilko Grunefeld)
- Ali (@bunnyycat) (Ali Spanevello)
- Alvaro (@alw0ng) (Alvaro Wong)
- Liam (@liamhemmett) (Liam Hemmett)

**Comment by vilnor** [comment]
TO THE MOOOON

**Comment by JTrenerry** [comment]
Hey, just a quick question about the artefacts, will they only spawn in when the clue is in the game? or if you get lucky will you be able to just find them?

**Comment by vilnor** [comment]
> Hey, just a quick question about the artefacts, will they only spawn in when the clue is in the game? or if you get lucky will you be able to just find them?


At this stage, `ShipArtefactItem`s will generally be given as quest rewards. However, there will be some quests where the reward is a `ShipArtefactClueItem`, in which case a `ShipArtefactTile` will spawn on the map for the player to find and dig up. 

There will also be a `ShipDebris` entity which is separate from the artefacts - a certain amount of debris will be generated on the map at the start of the game and I believe cleaning this up will be the first quest according to the initial quest design by Team 7. When a `ShipArtefactTile` is spawned, a `ShipDebris` entity will be placed on top to help show the player where the tile is. 

This is all just the initial design, I'm sure there will be changes as things are implemented and feedback is received.
