### ISSUE TITLE
Mission System Updates & Storyline Quest Progression

### ISSUE THREAD

**Issue by Tom-Strooper** [UQcsse3200/2023-studio-1#331]
# Description
This feature will involve updates to the missions system, including implementing the game-over functionality associated with a mandatory quest expiring and triggering events to notify the Alien NPC that an update to the available quests/achievements has occurred.

This feature also introduces a storyline to the game through the use of in-game dialogue and a progression of mandatory quest, which aim to both introduce key features of the game to the player, and also provide progression to the game, to give the player the opportunity to beat the game.

## Features
- Updating the `Mission` and `MissionManager` classes to trigger a game-over upon expiry of a mandatory `Quest`
- Updates to the Rewards to allow for a QuestReward so that new `Quest`s are unlocked on the completion of another `Quest`
- Create a dialogue screen to simulate communication with the Alien NPC before/after important storyline-related `Quest`s complete
- Creation of a collection of storyline-centric `Quest`s which introduce progression to the game
- Mission system save/load functionality

## Examples
- When the player begins the game, the first few mandatory `Quest`s should guide the player through the basic mechanics and introduce the game’s storyline

# Dependencies
- Missions system preliminary implementation #148 
- Alien NPC preliminary implementation #186 
- Space shuttle debris and interaction for storyline progression #327 

# Milestones
- [x] Map out storyline of game in its entirety (Sep. 17)
- [x] Make expiry of mandatory quests trigger game over (Oct. 1)
- [x] Come up with storyline and mandatory quests outline (Sep. 20)
- [x] Add the new `Reward`s which add a new quest/s to the `MissionManager` (Sep. 30)
- [x] Implement the new `Reward`s and NPC Dialogue screens by creating the mandatory `Quest`s for the game (Sep. 30)
- [x] Create new `Quest` constructor, which makes it so the `Quest` does not expire (for the smaller in-game story-based `Quests`) (Sep. 30)
- [x] Implement save/load functionality for the mission system and the `MissionManager`
- [ ] Update testing suite (Oct. 2)

# Documentation
- [Missions System](https://github.com/UQcsse3200/2023-studio-1/wiki/Missions-%28Achievements-and-Quests%29-System)
- [Storyline](https://github.com/UQcsse3200/2023-studio-1/wiki/Storyline)

# Members
- Tom Strooper (@Tom-Strooper) (Tom Strooper)
- Charlotte Birkinshaw (@charliebkw)
