### ISSUE TITLE
Additional Quest Reward Classes and Reward Updates

### ISSUE THREAD

**Issue by charliebkw** [UQcsse3200/2023-studio-1#332]
# **Description**
**Task:** [Quest Rewards](#332).
**Feature:** [Feature which this tasks contributes to implementing](#331)

To allow for story progression there are changes needed to be made to the current `Reward` system. There are a multitude of additional reward classes to help with the progression. It makes sense for the completion of one `Quest` to unlock another one. Therefore it is necessary for there to be a `QuestReward` class that can be added as a reward to a `Quest`.
 
## **Example (optional)**
- Completing the first `Quest` in the game will unlock the next mandatory `Quest`.
- Completing a `Quest` should trigger a dialogue screen - Alien dialogue, final win dialogue, radio communication dialogue.
- Completing part 2 should trigger a new solar surge event with the `ClimateController`
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial `QuestReward` class creation (Sep. 18)
- [x] Initial `DialogueReward` class creation - for alien dialogue screen, win screen and radio communication screen (Sep. 22)
- [x] Initial `TriggerWeatherReward` class creation. (Sep. 22)
- [x] Initial `TriggerHostilesReward` class creation (Sep. 30)
- [ ] Testing for the `QuestReward` class (Sep. 25)
- [ ] Testing for the `DialogueReward` class (Sep. 25)
- [ ] Testing for the `TriggerWeatherReward` class (Sep. 25)
- [ ] Testing for the `TriggerHostilesReward` class (Sep. 30)
- [x] Changing the Quest implementation to have a list of `Reward`s (Sep. 20)
- [ ] Updating Reward documentation for Reward creations (Sep. 22)
 
# **Dependencies**
- `DialogueReward`s will call the associated dialogue screen implemented by team 3.
 
# **Documentation**
- TBA
 
# **Member**
- Charlotte Birkinshaw (@charliebkw)
