### ISSUE TITLE
Event Delays

### ISSUE THREAD

**Issue by pchsa** [UQcsse3200/2023-studio-1#345]
# **Description**
**Task:** [Event Delays](#3).
**Feature:** Anything with a delay

Modify the eventhandler to be able to schedule events. This will be used for timed gameplay features that should not depend on the in game time system. Instead of doing this in each system seperately, will be handled in eventhandler. Implementation will be similar to JavaScript setTimeout, such that scheduling the event will return an eventID. Return value can be used to cancel the scheduled event. 
 
## **Example (optional)**
- **NPC behaviour**: Hitting an animal will cause it to panic for x seconds, hostile will attack every x seconds.
- **Timed Animations**: Play an animation for x seconds when taming an animal etc.

# **Dependencies**
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement delayed events. (Sept 18).
- [x] Write tests. (Sept 20)
- [x] Write Documentation. (Sept 25)

# **Documentation**
- [Event Delays Wiki](https://github.com/UQcsse3200/2023-studio-1/wiki/Event-Delays)
- [JavaDoc](https://uqcsse3200.github.io/2023-studio-1/com/csse3200/game/events/EventHandler.html)
 
# **Member**
- Pocholo (GitHub pchsa) (pocholo)
