### ISSUE TITLE
Implement Oxygen Eater

### ISSUE THREAD

**Issue by v1dyut** [UQcsse3200/2023-studio-1#348]
* in progress *
# **Oxygen Eater**
**Task:** [Oxygen Eater](#348).
**Feature:** [Implement Hostile Animals](#169)

The Oxygen Eater is an antagonistic NPC that decreases oxygen levels. It remains in a stationary position and while alive removes oxygen from the environment. The player must take action against this entity otherwise they risk not being able to meet a win condition for the game.

# **Dependencies**
- [ ] Oxygen meter (#149)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Aug. 19)
- [ ] Step 2 (Aug. 20)
- [ ] Step 3 (Aug. 23)
- [ ] Step 4 (Aug. 23)
 
**Completion Deadline:** Aug. 23

e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
-
