### ISSUE TITLE
Implement `ShipTimeSkipComponent`

### ISSUE THREAD

**Issue by vilnor** [UQcsse3200/2023-studio-1#349]
# **Description**
**Task:** Implement `ShipTimeSkipComponent`.
**Feature:** Player Ship (#327)

After a certain number of ship repairs is reached, the player will be able to 'sleep' through the night by interacting with the ship. This component will handle listening for the `progressUpdated` events triggered by the [`ShipProgressComponent`](../wiki/Player-Ship#shipprogresscomponent), and will 'unlock' the sleeping functionality after the threshold has been reached. It will also listen for `timeSkip` events which will be triggered by the player interacting with the ship. Once the sleeping functionality is unlocked and a `timeSkip` event is triggered, this component will handle calling the time service to skip to the next morning. 
 
# **Dependencies**
- [ ] Time system for skipping to the next morning
- [ ] Ship factory to add the component to an entity (#328)
- [ ] `ShipProgressComponent` that triggers the `progressUpdated` event

# **Milestones**
- [x] Component created (24 Sep.)
- [x] Sleep functionality unlocks after `progressUpdated` is called with \<X\> repairs (25 Sep.)
- [x] `timeSkip` event triggers time service skip (26 Sep.)
- [x] Tests implemented (30 Sep.)
 
**Completion Deadline:** 30 Sep.

# **Documentation**
- [Player Ship](../wiki/Player-Ship)
 
# **Member**
- Liv (@vilnor) (Liv Ronda)
