### ISSUE TITLE
Implement `ShipDebris` Entity

### ISSUE THREAD

**Issue by vilnor** [UQcsse3200/2023-studio-1#350]
# **Description**
**Task:** Implement `ShipDebris` Entity.
**Feature:** Player Ship (#327)

Upon starting the game, a fixed amount of `ShipDebris` will be spawned around the `Ship`. It will take up the size of a block similar to a plant. `ShipDebris` can be removed ('cleared') from the map by the player using a shovel, but it does _not_ drop any items and therefore cannot be placed by the player. It will trigger a `debrisCleared` event on the `MissionManager` as clearing it will be a requirement for certain quests. 

When a quest reward is a [Ship Part Clue Item](../wiki/Player-Ship#ship-part-clue-item) that generates a tile with a [`ShipPartTileComponent`](../wiki/Player-Ship#shipparttilecomponent) on the map, a `ShipDebris` Entity will also spawn on top of the tile containing a [`ShipPartTileComponent`](../wiki/Player-Ship#shipparttilecomponent) to make its position obvious to the player.
 
# **Dependencies**
- Map/terrain system
- Ship Factory for getting the position around which to generate
- Ship Part Clue Item for generating on top of tiles with the `ShipPartTileComponent`

# **Milestones**
- [x] Entity created (25 Sep.)
- [x] Debirs generated on game start (26 Sep.)
- [x] Cleared on use shovel event (27 Sep.)
- [x] Generate when a Ship Part Clue Item is picked up (27 Sep.)
- [x] Tests implemented (30 Sep.)
 
**Completion Deadline:** 30 Sep.

# **Documentation**
- [Player Ship](../wiki/Player-Ship)
 
# **Member**
- Liv (@vilnor) (Liv Ronda)

**Comment by Tom-Strooper** [comment]
Would it be possible for the `debrisCleared` event to be replaced with a name of a new enum value in `MissionManager.MissionEvent` to keep it consistent with the other events triggered on the `MissionManager`'s `EventHandler`? Let me know if this is fine! Thank you!
