### ISSUE TITLE
Implement `ShipPartTileComponent`

### ISSUE THREAD

**Issue by vilnor** [UQcsse3200/2023-studio-1#351]
# **Description**
**Task:** Implement `ShipPartTileComponent`.
**Feature:** Player Ship (#327)

Tiles containing this component will generate once a player receives a [Ship Part Clue Item](../wiki/Player-Ship#ship-part-clue-item) as a quest reward. Similar to the Crop Tiles, these will take up the space of one Terrain Tile, and are able to be interacted with through a `shovel` event. Upon a player successfully using a shovel on the tile, a [Ship Part Item](../wiki/Player-Ship#ship-part-item) will be dropped, and the tile destroyed. The corresponding [Ship Part Clue Item](../wiki/Player-Ship#ship-part-clue-item) in the player's inventory will also be destroyed.
 
# **Dependencies**
- [ ] Map/terrain system
- [ ] Ship Part Clue Item for generating the tile
- [ ] Ship Part Item to drop once dug up

# **Milestones**
- [x] Tile factory updated (25 Sep.)
- [x] Cleared on use shovel event (26 Sep.)
- [x] Drop item on iteractiong with shovel (27 Sep.)
- [x] Tests implemented (30 Sep.)
 
**Completion Deadline:** 30 Sep.

# **Documentation**
- [Player Ship](../wiki/Player-Ship)
 
# **Member**
- Liv (@vilnor) (Liv Ronda)
