### ISSUE TITLE
Plant Area of Effect

### ISSUE THREAD

**Issue by tomedwa** [UQcsse3200/2023-studio-1#357]
# **Description**
Implement an area of effect component that can be added to plants. This component will have unique effects based on the type of plant it is applied to and the current growth stage of the plant. The effects include a healing, poison, eating, and dead/decay.

Also a sound proximity component will be introduced. Plants should only play sounds when the player is close by. This will prevent the game from being cluttered with noises from plants. 
  
# **Milestones**

Healing Effect: Increases the health the player and any animals or plants within the area. This effect applies to the Hammer Plant.
Poison Effect:  Decreases the health of the player and any animals within the area. This effect applies to the Deadly Nightshade plant.
Eating Effect: Any animal that enters the area will be 'eaten' by the plant. This effect applies to the Space Snapper plant.
Dead/Decay Effect: When a plant is decaying or is dead, the health of all plants around it will be decreased. This effect applies to all plants. 

**Task:** [Plant Area of Effect](#357).
**Feature:** [Final Plant Functionality, Hunger, Progress Bar](#301 ) 

# **Dependencies**
- [ ] Health implemented for animals (So the AOE for plants can effect them)
 
# **Milestones**
- [x] Implement basic functionality for new area of effect components for plants (Sep. 28)
    - [x] When a plant is decaying/dead make the plant decrease the health of all plants within a 1 tile radius (Sep. 22)
    - [x] Deadly nightshade should damage all entities (excluding plants) within its radius when it reaches adulthood (Sep. 25)
    - [x] Hammer plant heals all plants within its radius when it reaches adulthood (Sep. 28)
    - [x] Create Wiki page (Sep. 21)
    - [x] Javadocs (Oct. 3)
    - [ ] unit testing (Oct. 3)
- [x] Create a component for plants that detects when the player is/isn't in range (Sep. 24)

**Extra Milestones (Optional)**
- [x] Animation when the Space Snapper eats an animal.
- [ ] Visuals for different effects (e.g. green for health, red for poison, dark for decay etc) (Oct. 3)
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [Plant Descriptions](../wiki/Plant-Properties-and-Types)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
* Tom (@tomedwa) (Tom Edwards)
* Aadya (@abhat0) (Aadya Bhatia)
