### ISSUE TITLE
Save Load Mission System Updates

### ISSUE THREAD

**Issue by Tom-Strooper** [UQcsse3200/2023-studio-1#359]
# **Description**
**Task:** Save Load Mission System Updates #359
**Feature:** Mission System Updates #331 & Save Load Maintenance #296 

Make updates to the Mission System to allow save/load functionality. This involves the creation of a `QuestFactory` class which will be used to generate all `Quest` instances in-game. It will also involve the addition of 2 new methods in the `Mission` class:

- `void setProgress(JsonValue state)` - accepts a `JsonValue` as formatted from a previous call to `getProgress()`, which updates the internal state of a `Mission` to match the state as described by the `JsonValue`. All `Mission` implementations will require an override to this method.
- `JsonValue getProgress()` - returns a `JsonValue` which describes the current state of a `Mission` (including the progress of all tracked values in the `Quest`/`Achievement`). The `JsonValue` will need to be formatted such that it can be read by `setProgress()`

# **Milestones**
List of steps that need to be completed for this task.
- [x] Add `setProgress` and `getProgress` to `Mission` class (Sep. 20)
- [x] Add overrides for `setProgress` and `getProgress` to example `Quest`/`Achievement`s (Sep. 20)
- [x] Implement `QuestFactory` methods for example `Quest`/`Achievement`s (Sep. 20)
- [x] Extend testing to account for `get/setProgress` (Oct. 2)
- [x] Extend documentation (Oct. 2)

**Completion Deadline:** Oct. 2

# **Documentation**
- [Missions (Achievements and Quests) System](https://github.com/UQcsse3200/2023-studio-1/wiki/Missions-%28Achievements-and-Quests%29-System)
- [How to Guide: Creating a Mission](https://github.com/UQcsse3200/2023-studio-1/wiki/How-to-Guide%3A-Creating-a-Mission)
 
# **Member**
- Tom Strooper @Tom-Strooper (Tom Strooper)
