### ISSUE TITLE
Implement Inventory Unit Tests

### ISSUE THREAD

**Issue by adamFittlerUQ** [UQcsse3200/2023-studio-1#36]
# **Description**
**Task:** Inventory Unit Tests 
**Feature:** Player Inventory

I will implement tests that can be used to make sure the player inventory has been implemented correctly and all of the object methods are working as intended.  The InventoryComponentTest class will inherit from the GameExtension class.  Initially, before each test a list of items will be created then added to a new InventoryComponent object.  This methods of this object will then be tested and evaluated to see how well they are working.  These tests cover the hasItem, addItem, removeItem and getInventory methods. 
 
# **Dependencies**
This task is dependent on the implementation of the inventory component class. All functions should be completed and syntax error free before tests are started
- [x] Inventory Component  
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Read through inventory implementation (Aug. 18)
- [x] Break down ways each method may fail (Aug. 18)
- [x] Write basic functionality tests (Aug. 19)
- [x] Cover edge cases in tests (Aug. 19)
 
**Completion Deadline:** Aug. 20

# **Member**
- Adam (@adamFittlerUQ ) (Adam Fittler)
