### ISSUE TITLE
Light it up

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#361]
# **Description**
It's kind of dark in the game at the moment and this feature will hopefully brighten up the world, and that player's day, by adding some new light sources into the game! This will use preexisting components and just add them onto new and existing entities.

## **Examples**
- Tractor headlights will allow the player to see when they are driving roun' town
- Lights (maybe torches or little glowing orbs) will be used as the player primary placeable light source, will be attainable via quests
- Fireflies will bring atmosphere and life to a seeming dark night life. These will randomly spawn in and have no interaction with the player, just a small amount of light in the nearby areas, may add that they vanish when near player.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Goal 1 (Sep. 29) - Tractor headlights
- [x] Goal 2 (Sep. 29) - Placeable lights
- [x] Goal 3 (Sep. 29) - Fireflies

**Completion Deadline:** Sep. 30

# **Documentation**
https://github.com/UQcsse3200/2023-studio-1/wiki/Placeables
https://github.com/UQcsse3200/2023-studio-1/wiki/Lighting-System
https://github.com/UQcsse3200/2023-studio-1/wiki/Animals
https://github.com/UQcsse3200/2023-studio-1/wiki/Tractor

# **Members**
- Jackson Trenerry @JTrenerry
