### ISSUE TITLE
 Implement `ShipEater` Entity

### ISSUE THREAD

**Issue by vilnor** [UQcsse3200/2023-studio-1#363]
# **Description**
**Task:** Implement `ShipEater` Entity.
**Feature:** ~~Player Ship (#327)~~ Ship Enhancements #616

The `ShipEater` is an entity that has a chance of spawning when a player destroys a [`ShipDebris` Entity](../wiki/Player-Ship#shipdebris-entity). Upon spawning, they move towards the  [`Ship` Entity](../wiki/Player-Ship#ship-entity). Once close enough, they will periodically _decrease_ the repair state of the ship. `ShipEater` Entities will only have a chance to spawn once the player unlocks weapons (part of the [Home Sick Quest](../wiki/Storyline#quest-home-sick)) so that they can have a chance to defeat them.

Note: any existing unlocks on the ship (e.g. time skip or light) will _not_ be removed as the repair state decreases, but further progress will be hindered. 
 
# **Dependencies**
- [ ] Player weapon implementations

# **Milestones**
- [x] Entity created
- [x] Spawn after `ShipDebris` is destroyed
- [x] Move to `Ship` and reduce repair state
- [x] Tests implemented
 
**Completion Deadline:** Oct 15

# **Documentation**
- [Player Ship](../wiki/Player-Ship)
 
# **Member**
- Liv (@vilnor) (Liv Ronda)
