### ISSUE TITLE
Implement `ShipProgressComponent`

### ISSUE THREAD

**Issue by vilnor** [UQcsse3200/2023-studio-1#364]
# **Description**
**Task:** Implement `ShipProgressComponent`.
**Feature:** Player Ship (#327)

This component will handle the `Ship`'s internal state of repair. It will listen for `addPart` events on the [`Ship` Entity](./Player-Ship#ship-entity), which will pass the number of [Ship Part Items](./Player-Ship#ship-part-item) the player is using on the ship, and increment its internal state of repair by that amount. It will also trigger a `progressUpdated` event on the [`Ship` Entity](./Player-Ship#ship-entity) along with the current state of repair for other components to use.
 
# **Dependencies**
- [x] Ship factory

# **Milestones**
- [x] Component created (24 Sep.)
- [x] Updates state on `addPart` event  (24 Sep.)
- [x] Save/load functionality (30 Sep.)
- [x] Tests implemented  (30 Sep.)
 
**Completion Deadline:** 24 Sep.

# **Documentation**
- [Player Ship](../wiki/Player-Ship)
 
# **Member**
- Wilko (@yetanothercarbot) (Wilko Grunefeld)
