### ISSUE TITLE
Implement `ShipAnimationController`

### ISSUE THREAD

**Issue by vilnor** [UQcsse3200/2023-studio-1#365]
# **Description**
**Task:** Implement `ShipAnimationController`.
**Feature:** Player Ship (#327)

This component will function as a way of visually showing the [`Ship` Entity's](./Player-Ship#ship-entity) repair state. It will listen for `progressUpdated` events, and change the current animation depending on thresholds that are reached. For sprint 3, these will be simply showing more parts of a single sprite, but in the future this would control actual animations. 
 
# **Dependencies**
- [x] Ship factory
- [x] Sprites?

# **Milestones**
- [x] Component created (27 Sep.)
- [x] Sprite state updates on `progressUpdated` event (27 Sep.)
- [x] Tests implemented (30 Sep.)
 
**Completion Deadline:** 30 Sep.

# **Documentation**
- [Player Ship](../wiki/Player-Ship)
 
# **Member**
- Ali (@bunnyycat) (Ali Spanevello)
