### ISSUE TITLE
Implement Ship Part Clue Item & Reward

### ISSUE THREAD

**Issue by vilnor** [UQcsse3200/2023-studio-1#368]
# **Description**
**Task:** Implement Ship Part Clue Item & Reward.
**Feature:** Player Ship (#327)

This will be an item added to the `ItemFactory`, and can be obtained either as a quest reward. It will have an internal state that contains a random, valid tile location for spawning an part. Upon collection by the player, the reward will trigger a tile to spawn with a [`ShipPartTileComponent`](./Player-Ship#shipparttilecomponent) at its stored location. A [`ShipDebris` Entity](./Player-Ship#shipdebris-entity) will also spawn in this same location. 
 
# **Dependencies**
- [x] Ship factory
- [x] ShipPartTileComponent / ShipDebris Entity
- [x] Quests

# **Milestones**
- [x] Item added to factory (27 Sep.)
- [x] Collection of reward generates tile & debris
- [x] Tests implemented (30 Sep.)
 
**Completion Deadline:** 30 Sep.

# **Documentation**
- [Player Ship](../wiki/Player-Ship)
 
# **Member**
- Liam (@liamhemmett) (Liam Hemmett)

**Comment by liamhemmett** [comment]
Completed. All tasks maenad into main.
