### ISSUE TITLE
Implement Inventory User Interface

### ISSUE THREAD

**Issue by adamFittlerUQ** [UQcsse3200/2023-studio-1#37]
# **Description**
**Task:** Implementing Basic UI for Player Inventory

**Feature:** Player Inventory

Now that the inventory functionality has been implemented with the ability to add, remove, and update item amounts, it's time to enhance the user experience by creating a basic UI for the player's inventory. This UI will allow players to see their items, observe changes when new items are added, and interact with the inventory more intuitively. This UI improvement will facilitate better testing of the game.

## **Example (optional)**
- **Scenario:** A player presses the E key
- **Expected Outcome:** The inventory UI is displayed

# **Dependencies**
- [x] Inventory functionality (Implemented)
- [x] UI framework integration 

# **Milestones**
List of steps required to complete the task:

- [x] Design the inventory UI layout and components (Aug. 22)
- [x] Integrate UI components with existing inventory functionality (Aug. 22)
- [x] Implement display of UI (Aug. 23)
- [ ] Test the displaying of the UI (Aug. 23)

**Completion Deadline:** Aug. 23

# **Documentation**
- [Main description of inventory feature](../wiki/Player-Inventory)
- [JavaDoc for UI classes](JavaDoc/UI/Inventory)

# **Member**
- Tristan (@tristanduncombe) (Tristan Duncombe)
- Adam (@adamFittlerUQ) (Adam Fittler)
- Nimesh (@nimeshgarg) (Nimesh Garg)
