### ISSUE TITLE
Tractor lights

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#370]
**Task:** Tractor lights
**Feature:** #361 

Adds headlights for the tractor, also maybe constant small light while in tractor, headlights will occur on clicking 't'.

# **Dependencies**

- [x]  #207 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Sep. 29) - Headlights
- [x] Step 2 (Sep. 29) - Ambient light
- [x] Step 3 (Sep. 29) - Updating javadoc
- [x] Step 4 (Sep. 29) - Testing suite completed
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
https://github.com/UQcsse3200/2023-studio-1/wiki/Tractor
https://github.com/UQcsse3200/2023-studio-1/wiki/Lighting-System
 
# **Member**
- Jackson Trenerry

**Comment by JTrenerry** [comment]
Had some issues with trying to test the functions, i.e. calling on T click or triggering lights on enter/exit, but since Light Components had extensive testing and I ran in game testing under different conditions should be okay, feel free to assign me to any bugs it may produce though!

**Comment by JTrenerry** [comment]
Will close this ticket when in main
