### ISSUE TITLE
Light Placeable

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#372]
**Task:** Placeable light.
**Feature:** #361 

Adds a new placeable entity that will have an AuraLightComponent, this will let the player light up their farm and see!

# **Dependencies**
- [x] #207 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Sep. 29) - Make a light placeable
- [x] Step 2 (Sep. 29) - Make sprite for light
- [x] Step 3 (Sep. 29) - Create Javadocs for it
- [x] Step 4 (Sep. 29) - Testing scripts for it
 
**Completion Deadline:** Sep. 30

# **Documentation**
https://github.com/UQcsse3200/2023-studio-1/wiki/Placeables
https://github.com/UQcsse3200/2023-studio-1/wiki/Lighting-System
 
# **Member**
- Jackson Trenerry @JTrenerry

**Comment by JTrenerry** [comment]
Just needs sprite
