### ISSUE TITLE
Fireflies

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#373]
**Task:** Adding fireflies
**Feature:** #361 

The nightlife of the game at the moment is lackluster and to combat this, fireflies will be added to hopefully add the visual appeal of the game and add some juice.

# **Dependencies**
- [x] #207 
- [x] #372 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Sep. 29) - Create FireFly entity that vanishes if there is a #372 or the player nearby
- [x] Step 2 (Sep. 29) - Add random spawning to them at night
- [x] Step 3 (Sep. 29) - Add a light component to them
- [x] Step 4 (Sep. 29) - JavaDoc
- [x] Step 5 (Sep. 29) - Wiki
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
https://github.com/UQcsse3200/2023-studio-1/wiki/Lighting-System
https://github.com/UQcsse3200/2023-studio-1/wiki/Fireflies
 
# **Member**
- Jackson Trenerry @JTrenerry

**Comment by JTrenerry** [comment]
Decided to not make fireflies vanish when player / light is nearby, instead will dissapear on day

**Comment by JTrenerry** [comment]
Done from above PR
