### ISSUE TITLE
Custom item drops for animals

### ISSUE THREAD

**Issue by 27abdullah** [UQcsse3200/2023-studio-1#375]
# **Description**
**Task:** [Custom item drops for animals](#375).
**Feature:** [Implement Alien Animals Advance](#168)

Create and integrate `DropComponent`. This component will inherit from `Component` and will allow animals to drop different items on different triggers. These items will be beneficial for the player as to encourage them to interact with the animals. Different animals will drop different items. Using this component, animals will be able to drop items on death, drop items once tamed and drop items on regular intervals.
 
# **Dependencies**
- [x] Items (#15)
- [x] Time system - determine when the item is dropped (#10 )
- [x] TameableComponent - determine when to activate the component
- [x] PassiveDropComponent

# **Milestones**
- [x] Design different items to be dropped by the different animals. (Sep. 25)
- [x] Choose design pattern to facilitate passing custom triggers. (Sep. 26)
- [x] Integrate component - add to animals, add items to each animal's DropComponent. (Sep. 29)
- [x] Tests for class (Sep. 30)
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
- [Animals](../wiki/Animals)
 
# **Member**
- Abdullah (@27abdullah)

**Comment by JTrenerry** [comment]
If animals can die, and there is no breeding, how does the player get more?

**Comment by 27abdullah** [comment]
> If animals can die, and there is no breeding, how does the player get more?

Respawning - like in minecraft
