### ISSUE TITLE
Rewrite Inventory Component (Sept. 23)

### ISSUE THREAD

**Issue by nimeshgarg** [UQcsse3200/2023-studio-1#378]
**Task:** InventoryComponent
**Feature:** Inventory Rework #376 

Reworking the Inventory Component to clean up and optimize the existing code.

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Sept. 23) - Remove extra code
- [x] Step 2 (Sept. 23) - Optimize functions
- [x] Step 3 (Sept. 29) - JavaDoc
- [ ] Step 4 (Sept. 29) - Wiki
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
 
# **Member**
- Nimesh @nimeshgarg
