### ISSUE TITLE
Sound System Implementation

### ISSUE THREAD

**Issue by gilgilgilgilgil** [UQcsse3200/2023-studio-1#385]
# **Description**
The sound system will be responsible for operating the sound aspects of the whole game. This encompasses the background music (with support for dynamic tracks) and sound effects throughout the game (both one off and repeating). The sound system will be implemented by developing a SoundService that will be exposed in every area of the game. Multiple sound effects can be played at the same time, but only one background track may be played at any given time. The individual background music tracks and sound effects will be codified in EffectSound and BackgroundMusicSound enums, which will have a name and associated filepath.

### Background Music
Background music is played by streaming a long music file in chunks from disk. Given this, only 1 background music track can be played at any given time. To start a new track, the old one must be stopped. Upto 10 tracks can be loaded into memory though. There is no upper limit to the length of background music tracks. 

### Sound Effects
Sound effects are short snippets of upto 5s, which are played from memory. These should be in the WAV file format to ensure no issues with looping the audio. Any number of tracks can be loaded on a given screen, but they need to be disposed before that screen is closed.

## **Examples**
- **Part/Feature**: Depending on the ticket, you will often want to provide some examples of how it would play out in the game. See next point for example...
- **Background Music**: An ongoing theme 
# **Dependencies**

List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented and the issue does not already exist... make a new ticket and leave it unassigned for someone else to take on.

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Poll teams for types of short sound events (Sept. 22)
- [x] Setup code structure for both sound effects and background music (Sept. 23)
- [x] Create structure for sound effects to be logged/loaded for use. (Sept. 25)
- [x] Implement the option for different background music for different events/situations (Sept. 29)
- [x] Connect playing of sound effects to in-game triggers. (Oct. 1)
- [x] Connect playing of background music to game start (Oct. 2)

**Completion Deadline:** Oct. 3rd.

# **Documentation**
- [Sound System](https://github.com/UQcsse3200/2023-studio-1/wiki/Sound-System)

# **Members**
- Gil (@gilgilgilgilgil ) (Gil)
- Arjun (@arj-sng) (Arjun Singh)
