### ISSUE TITLE
Implement Mandatory Quest Classes

### ISSUE THREAD

**Issue by Tom-Strooper** [UQcsse3200/2023-studio-1#387]
# **Description**
**Task:** Implement Mandatory Quest Classes #387
**Feature:** Mission System Updates & Storyline Quest Progression #331

The storyline of the game will be driven by mandatory quests, which are quests that result in a game over if they are not completed before they expire. These quests need to be implemented as per the story outline in the wiki page.

# **Dependencies**
- Different screens need to be displayed at certain points throughout the story, as rewards for various quests. This requires screen implementations from team 3, team 5 and team 8

# **Milestones**
- [x] Implement game over trigger on expiry of mandatory quests (Oct. 1)
- [x] Implement all Mandatory Quest classes (Sep. 30)
	- [x] Implement MainQuest class
	- [x] Implement AutoQuest class
	- [x] Implement ClearDebrisQuest class
	- [x] Implement PlantInteractionQuest class
	- [x] Implement TameAnimalsQuest class
	- [x] Implement ManageHostilesQuest class
	- [x] Implement OxygenLevelQuest class
	- [x] Implement ShipRepairQuest class
- [ ] Complete in-game and JUnit testing for quests & storyline progression (Oct. 2)

Due date: Oct. 2

# **Documentation**
- [Storyline](https://github.com/UQcsse3200/2023-studio-1/wiki/Storyline)
- [Missions System](https://github.com/UQcsse3200/2023-studio-1/wiki/Missions-%28Achievements-and-Quests%29-System)
 
# **Member**
- Tom Strooper (@Tom-Strooper) (Tom Strooper)
