### ISSUE TITLE
Plant Information UI

### ISSUE THREAD

**Issue by tomedwa** [UQcsse3200/2023-studio-1#389]
# **Description**
**Task:** [Plant Information UI](#389).
**Feature:** [Final Plant Functionality, Hunger, Progress Bar, Plant Info UI](#301)

Implement a UI component that displays relevant information about a plant on the screen when the user hovers their mouse cursor over the plant they are interested in.
The information shown will include:
    * Plant name
    * current growth stage
    * water level/ideal water level
    * health/max health
    * Some information specific to the type of plant (e.g. When the space snapper is digesting)
 
# **Milestones**
- [x] Show relevant information in a basic window (Sep. 20)
- [x] Format the layout of the UI window so it conforms with the style of the game (Oct. 3)
- [x] Create wiki page (Sep. 22)
- [x] javadocs (Oct. 3)
- [ ] tests (Oct. 3)

 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
* Tom (@tomedwa) (Tom Edwards)
