### ISSUE TITLE
Implement basic functionality for the animals to be tamed

### ISSUE THREAD

**Issue by UniversalTze** [UQcsse3200/2023-studio-1#39]
Alien Animals' ability to be tamed
**Task:** Add basic functionality so player can tame alien animals.
**Feature:** Implement Alien Animals Basic #4

To main premise of this task is to create a component where the animals can be tamed by the main player. This will be apart of the npc package in the project and will inherit from component. To tame an animal, the user will be able to feed the animals food, which will result in the user accumulating tame points. When these points surpass a threshold, the animal will become tamed and  an event handler will occur to indicate this behaviour. 
 
- **Taming Benefits**:  The tamed animal may be able to protect the farm/ crops from whoever dares to harm it. Also allows for a companion to follow the user around. 

Due to the dependencies, finishing it off this task may have to wait till later sprints. 

# **Dependencies**
- [x] Different varieties of animals will need to be implemented. 
- [x] Player interaction with regards to feeding the animals. #33
- [x] Variety of food options to feed animals
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Implement some basic functionality for taming (Aug. 25)
- [x] Step 2 Merge all changes into the main branch(Aug. 28)

**Completion Deadline:** Aug. 28

e.g.
- [x] Create Wiki (Aug 23) 
- [x] Finish some functionality (Aug. 25).
- [x] Unit tests implemented for `Taming` (Aug. 28).
- [x] Update Wiki (Aug. 27).
- [x] Merge to Main (Aug. 28).
 
# **Documentation**
- [Animals](https://github.com/UQcsse3200/2023-studio-1/wiki/Animals)

 
# **Member** 
- Tze Kheng @UniversalTze  (Tze Kheng Goh)
- David Pocholo @pchsa (Pocholo)
- Vidyut @v1dyut (Vidyut)

**Comment by yetanothercarbot** [comment]
#33 has a preliminary implementation on the 2-player-animation-wilko branch where it's just bound to a key. We probably would need proper key-handling system where an 'interact' key would be bound and used for whatever relevant (e.g. doors/chests/animals/etc)

**Comment by UniversalTze** [comment]
Note that basic functionality has been implemented but the dependencies on finishing the tasks were underestimated. In order to fully finish this project, player animation to feed animal, types of food to feed animals and the ability to access inventory and use inventory needed to be done.
