### ISSUE TITLE
Implement Alien Animals Basic

### ISSUE THREAD

**Issue by v1dyut** [UQcsse3200/2023-studio-1#4]
# **Description**
This feature seeks to implement basic alien animals which will include visuals, movement, behaviour patterns and interaction with player/environment. The animals can help progress towards the win condition, they may assist the player by providing a means of resource generation. Animals are initially wild and can be tamed/domesticated using their favourite plants.

## SubFeature/component (optional)
* Visuals and animations
* Movement
* Behaviour patterns (etc., skittish, neutral). Tamed vs untamed.

## **Examples (optional)**
- Alien equivalents of cows, chickens and dogs. Details may change later.

# **Dependencies**
- Can be coded without plants but will be required for future functionality.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Develop characters for animals including description, visuals and behaviour (Aug. 16)
- [x] Create visual assets, standing animation, moving animation (calm, frightened, interested), death animation (Aug. 23)
- [x] Integrate animals into the game which includes entity representation, basic movement (Aug. 26)
- [x] Implement behaviours such as tamed, frightened etc., (Aug. 28)

**Completion Deadline:** Aug. 30

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- [Animals](../wiki/Animals)

# **Members**
- @27abdullah 
- @v1dyut 
- @pchsa 
- @UniversalTze 
- @Bradbowi

**Comment by 27abdullah** [comment]
Despite most features being implemented, due to dependencies on other teams, the tameable functionality will be finalised in Sprint 2.
