### ISSUE TITLE
Time System Assets 

### ISSUE THREAD

**Issue by ManavTriv** [UQcsse3200/2023-studio-1#41]
# **Description**
**Task:** [Time System Assets](#3).
**Feature:** [Time System](#2)

Create assets for the time-system UI. This includes:
- Clock frame - which will contain the day-night indicator
- Time frame - which will contain the in-game time)
- Day-night indicator - asset that indicates the time of day. So when it is the day it will show a sun in front of a sky blue background whereas night will be a moon in front of a dark blue background
- Clouds - an asset that will be displayed on top of the day-night indicator to show clouds in front of the sun or moon

We will also implement a transition in the day-night indicator, so as the time approaches night the sun will slowly move out of frame and the moon will take over. This will be done by implementing 24 different variations of the day-night indicator (1 for each hour) which will all be slightly different from each other to show a transition.

# **Dependencies**

- Colour palette
- (https://github.com/UQcsse3200/2023-studio-1/issues/10)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Design clock frame
- [x] Step 2: Design time frame
- [x] Step 3: Design day-night indicator
- [x] Step 4: Design the transition assets for the day-night indicator
- [x] Step 5: Design clouds
- [x] Step 6: Update to match colour palette
 
**Completion Deadline:** Aug. 28

# **Documentation**
- (https://github.com/UQcsse3200/2023-studio-1/wiki/Time-System)
 
# **Member**
- Manav Trivedi (@ManavTriv) (Manav Trivedi)
