### ISSUE TITLE
Cutscene Class

### ISSUE THREAD

**Issue by RileyWhitty** [UQcsse3200/2023-studio-1#418]
# **Description**
A class that can be used to generate dialogue cutscenes to be used to enhance the story telling of the game. When called, it can pause the game, spawn in the cutscene sprites and animate them, generate the dialogue box and its text and create an exit button that can be used to exit the cutscene dialogue. 

## Components
- Pause the game - when the cutscene is instantiated/created it should pause the game
- Spawn sprites - when the cutscene is instantiated/created it should spawn the sprites (Player and Alien) to the left and right of the screen
- Animate sprites - when the cutscene begins it should animate the sprites spawned in (probably easiest to spawn sprites in as entities and use the animation features already present in the game) to make it look like they are speaking
- Spawn dialogue box and populate it - create a dialogue box when the when the cutscene is instantiated/created and populate it with text (text is either taken from method input as a input String or is read from a text file which is provided as an input as a file path)
- Spawn exit button - create a exit button in the middle bottom part of the screen that when pressed stops the cutscene
- Handle cutscene end - when the exit button is selected all of the sprites, dialogue and exit button should be deleted/cleared and the game unpaused

The story elements (main quest line) being created by team 7 will have this cutscene feature added to enhance the story telling of the game. It is not critical

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Create base class (Sep. 24)
- [x] Pause game (Sep. 28)
- [x] Spawn Alien Sprite (Sep. 28)
- [x] Spawn Dialogue box (Sep. 28)
- [x] Spawn Exit button (Sep. 28)
- [x] Populate Dialogue box (Sep. 30)
- [x] Add special case for radio contact with other humans (Oct. 01)
- [x] Handle Exit button being pressed (Oct. 02)

**Completion Deadline:** Oct. 03

# **Extras (optional)**
- [ ] Cutscene background (instead of just overlaying everything ontop of the game)
- [ ] Extra dialogue boxes - make it so the player/alien can have back and forth conversations instead of just only having one dialogue box between the both of them

# **Documentation**
- https://github.com/UQcsse3200/2023-studio-1/wiki/Cutscene-Class
- Test plan: https://github.com/UQcsse3200/2023-studio-1/wiki/Cutscene-Class

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- Hunter (HunterWhitty) (Hunter Whitlock)
- Riley (RileyWhitty) (Riley Whitlock)
- Angus (AngusWhittaker) (Angus Whittaker)
- Nathaniel (Radius-XT)
- Thang (thanghoang7020202) (Cao Quoc Thang Hoang)

**Comment by RileyWhitty** [comment]
Notes for Sprint 4:
Need to add window or backdrop behind text
Need to make textbox width proportional to the screen width
Need to add the Radio scenario

**Comment by RileyWhitty** [comment]
Possible bug, NPC's are paused but their animations still run during the cutscene

**Comment by RileyWhitty** [comment]
Another bug: All UI components are not dimmed/are not covered by the cutscene in the very first cutscene. Is not an issue for other cutscenes spawned after the beginning of the game
