### ISSUE TITLE
Handle animal visuals and animations

### ISSUE THREAD

**Issue by 27abdullah** [UQcsse3200/2023-studio-1#43]
# **Description**
**Task:** Handle animal visuals and animations(#43).
**Feature:** [Implement alien animals basic](#4)

Determine physcial appearances of the animals and their distinctive characteristics.

Create assests for the animals including:
* Idle behaviour - e.g., blinking, tail wagging etc
* Walking left and right
* Running left and right
* Standing still

Handle the animation related code components e.g., animation controllers, updating event listeners and triggers. 

# **Dependencies**
- [x] Style guidelines
- [x] Colour palette

 
# **Milestones**
- [x] Decide on animals (Aug. 19)
- [x] Make sprites corresponding to guidelines (Aug. 20)
- [x] Implement animation code (Aug. 23)
- [x] Write tests for implemented code (Aug. 23)
 
**Completion Deadline:** Aug. 28

 
# **Documentation**
- Animal wiki (to be completed)
 
# **Member**
- Abdullah Badat (@27abdullah) (Abdullah)
- Pocholo Sarmiento (@pchsa ) (Pocholo)
