### ISSUE TITLE
Quests with Tractor, fence, gate, chest and lights as rewards

### ISSUE THREAD

**Issue by 86LAK** [UQcsse3200/2023-studio-1#430]
# **Description**
**Task:** Making some quests which involve Tractor, fence, gate, chest and lights as rewards
**Feature:** The overall game. #292 

Rough plan for appropriate quests for each reward are as follows: 
tractor - you get the quest to get tractor as a reward from the last mission in part 1, (so you have it in part 2) and it should be like complete 10 or 15 quests
fence & gates - tame / feed / care for animals
sprinkler & pump - water x amount of crops
chest - get one everynow and then from random story missions
light - same as above

# **Dependencies**
- [x] #303 fences and gates base placeable finished
- [x] #361  lights base placeable finished
- [x] #313 chests base placeable finished
- [x] #310 sprinkler base placeable finished
- [x] #214 Missions / quests implemented
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Read all wiki for quests and relevant other wikis (27/09/2023)
- [x] Sort out appropriate quests for each reward item (28/09/2023)
- [x] Implement the quests (1/10/2023)
- [x] junit testing (?) (2/10/2023)
- [x] Update game quests or any other documentation (2/10/2023)
 
**Completion Deadline:** 2/10/2023
 
# **Documentation**
- https://github.com/UQcsse3200/2023-studio-1/wiki/Game-Quests
- 
 
# **Member**
- Shanon Lakshan Chandrasekara @86LAK

**Comment by 86LAK** [comment]
I read the wiki today 👍

**Comment by 86LAK** [comment]
I read the thought about appropriate quests today 👍

**Comment by 86LAK** [comment]
I made quest which rewards player with tractor 👍

**Comment by 86LAK** [comment]
I made finished implementing the quests 👍 🦖

**Comment by 86LAK** [comment]
I made some junit tests 👍 🤖
