### ISSUE TITLE
Quest Giver NPC UI Updates for Quests

### ISSUE THREAD

**Issue by Tom-Strooper** [UQcsse3200/2023-studio-1#432]
# **Description**
**Task:** Quest Giver NPC UI Updates for Quests (#432).
**Feature:** Mission System Updates & Storyline Quest Progression (#331)

A few UI updates to the QuestGiver NPC for Quests display. This involves:
- A button to switch between screens which only show Quests at a certain state (i.e., selectable quests only, active quests only, expired quests only, completed quests only)
- Removal of the 'claim reward' button when a reward for a quest is claimed (rewards should only be able to be claimed once, and the UI should reflect this)

# **Milestones**
- [x] Implement different quest screens
- [x] Remove 'claim reward' button once rewards have been claimed
- [x] Update testing suites to match changes
