### ISSUE TITLE
Creation of acid rain particle effect file

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#440]
# **Description**
**Feature:** [Weather Events for visual effects](#319 )

This task ticket is for the creation of the particle effects file (created using the [Libgdx Particle Editor](https://libgdx.com/wiki/tools/2d-particle-editor)). 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Learn how to use the Libgdx particle editor
- [x] Create an acid rain particle effect file
- [x] Load particle effect using `AssetManager` and `ResourceService`

# **Documentation**
- [Weather and Climate System](../wiki/Weather-and-Climate-System)
- [Particle Effects](../wiki/Particle-Effects)

**Comment by lucashicks1** [comment]
This particle effect was created during our weekly team 7 meeting on 23/09/23. All team members were involved.

**Comment by lucashicks1** [comment]
All tasks have been completed.
