### ISSUE TITLE
Update `ClimateController` and `WeatherEvent` for effects

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#443]
# **Description**
**Feature:** [Weather Events for visual effects](#319 )

In order for the effects to be rendered for each weather event, the `ClimateController` must be able to *activate* any potential vfx that may occur. As some weather events may not have particles associated with them, the `WeatherEvent` class should have a `startEffect()` method which could add a particle effect, change lighting or even both (all depends on weather event). If the implementation of the `WeatherEvent` were to require particle effects, it would use a method provided by the `ParticleService` (#441)

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] `ParticleService (#441 )
- [x] `ParticleEffectWrapper` (#442)
- [x] Creation of particle effect (#440)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Add methods to `WeatherEvent`
- [x] Implement methods in the concrete classes\
- [x] Update the `ClimateController`
- [x] Update Javadocs
- [x] Update Wiki
- [x] Update tests
 
**Completion Deadline:** Sep 25

# **Documentation**
- [Weather and Climate System](../wiki/Weather-and-Climate-System)
- [Particle Effects](../wiki/Particle-Effects)

# **Members**
- Lucas (@lucashicks1) (Lucas Hicks)
