### ISSUE TITLE
Implement Plant Eater/Dragonfly

### ISSUE THREAD

**Issue by v1dyut** [UQcsse3200/2023-studio-1#449]
# **Plant Eater**
**Task:** [Implement Plant Eater/Dragonfly](#449).
**Feature:** [Implement Hostile Animals](#169)

The Plant Eater is an antagonistic NPC that damages/destroys plant entities. The Plant Eater hinders the player’s ability to meet the win condition of producing enough food.. The player must take action against this entity otherwise they risk not being able to meet a win condition for the game.

# **Dependencies**
- [x] Plants must be implemented (#20)
- [x] Hostile Animation Controller
- [x] Entity interaction mechanism (#176)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement MoveToPlantTask (Sep. 28)
- [x] Implement DragonFlyAttackPattern (Sep. 30)
- [x] Write tests and documentation (Oct. 2)
 
**Completion Deadline:** Oct. 3

# **Documentation**
- [Hostiles](https://github.com/UQcsse3200/2023-studio-1/wiki/Hostile-Animals#hostile-species)

 
# **Member**
- @v1dyut 
- @pchsa 
- @UniversalTze
