### ISSUE TITLE
Item Pickup

### ISSUE THREAD

**Issue by p-lahanas** [UQcsse3200/2023-studio-1#46]
# **Description**
Makes an item able to be picked up and added to the player inventory. 

## SubFeature/component
- [x] Add the item to the player's inventory
- [x] Remove item from the ground
- [ ] Write unit tests
    - [ ] unit test for inventory full case -- NOTE: cannot be implemented due to inventory team not yet adding inventory capacity.
    - [x] unit test for item is added to inventory

Relies on:
#5 Implement Player Inventory

# **Milestones**
- [x] Complete all sub Features (Aug. 28)

**Completion Deadline:** Aug. 28

# **Documentation**

# **Members**
Peter Lahanas (@p-lahanas)
Cohen Porteous (@cmp6)
Liam Anderson (@LiamAnd)
