### ISSUE TITLE
Remove consumable items from inventory when used

### ISSUE THREAD

**Issue by Tom-Strooper** [UQcsse3200/2023-studio-1#462]
# **Description**
**Task:** Remove consumable items from inventory when used 
**Feature:** Assorted

When consumable items are used, they should be removed from the inventory. This includes:
- Plant Seeds - when plants are planted, the see item should be removed from the inventory
- Animal Food - when you give food to an animal, the food should be removed from the inventory
- Fertiliser - when you fertilise a crop tile, the fertiliser should be removed from the inventory
- Ship Parts - when you repair the ship, the ship part used should be removed from the inventory
- Placeables (e.g. fence, light etc) - when you place an item in the world, the item should be removed from the inventory

# **Dependencies**
The `removeItem()` method needs to work, which requires the updates to the `InventoryComponent` and inventory system. These updates should be included in the Inventory Rework #376 (team 8).

# **Milestones**
- [x] Remove plant seeds on use (team 7)
- [x] Remove animal food on use (team 4)
- [x] Remove fertiliser on use (team 7)
- [x] Remove ship parts on use (team 2)
- [x] Remove placeables on use (team 1)

**Comment by JTrenerry** [comment]
Removing our label as this is a team 8 issue and if they need help they can ask.
