### ISSUE TITLE
Fix win/lose screen rendering bugs 

### ISSUE THREAD

**Issue by adamFittlerUQ** [UQcsse3200/2023-studio-1#469]
# **Description**
**Task:** Resolve win/lose rendering bugs 
**Feature:** Win and Lose Screen

The bugs relating to the rendering of the win and lose screens need to be resolved either in this sprint of in the refinement of the game in sprint 4. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Identify cause of bug (Oct. 1)
- [x] Resolve bug (Oct. 2)
- [x] Merge into main (Oct. 3)
 
**Completion Deadline:** Oct. 3 (Subject to extension into sprint 4)

# **Member**
- Adam Fittler (@adamFittlerUQ ) (Adam Fittler)
