### ISSUE TITLE
Implement Player Attacker/Bat

### ISSUE THREAD

**Issue by v1dyut** [UQcsse3200/2023-studio-1#482]
# **Description**
**Task:** [Implement Player Attacker/Bat](#481).
**Feature:** [Implement Hostile Animals](#169).

The Player Attacker is an antagonistic NPC that seeks out and attacks the player. The player must take action against this entity otherwise they risk dying and not being able to win the game.
 
# **Dependencies**
- [x] Hostile Animation Controller
- [x] Entity interaction mechanism (#176)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement BatAttackPattern (Sep. 27)
- [x] Write tests and documentation (Oct. 2)

**Completion Deadline:** Oct. 3

# **Documentation**
- [Hostiles](https://github.com/UQcsse3200/2023-studio-1/wiki/Hostile-Animals#hostile-species)
 
# **Member**
- @v1dyut 
- @pchsa 
- @UniversalTze
