### ISSUE TITLE
Implement Player Inventory

### ISSUE THREAD

**Issue by tristanduncombe** [UQcsse3200/2023-studio-1#5]
# **Description**
This ticket is for the game's inventory system. One of the most important aspects of the game is that the player can carry and use items and tools such as  farming implements and seeds. Therefore, in the world it is important to be able to use, pickup, rearrange or manipulate an inventory of items to enable the game play. To accompany this system, an item component is necessary to hold all necessary information related to the item and its features (i.e its id or name or what item it actually is). As the user will use an item in a hot-bar, the inventory must know what item the player is holding and how it interacts with the world (which is an extension to the item class)

The aim of this system is to be responsible and flexible so that the user can shape their inventory to their desired shape and so that we can implement a myriad of items to implement the desired gameplay .

## SubFeature/component

- `ItemComponent `class which stores what the item is, it's name, and other important information related to the specific item
- `InventoryComponent` class which stores the players current inventory and has various functions to manipulate the state of the players inventory
- An `InventoryDisplay` class which is responsible for rendering the ui for the inventory itself which should display a number of `ItemDisplays`.
- A `ToolbarDisplay` class which shows one row of the inventory and allows the user to equip an item or use an item

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Develop Basic Item Class and Inventory (Aug. 14)
- [x] Improve item class and extend functionality (Aug. 15)
- [x] Add unit tests to ensure functionality of basic item and inventory (Aug. 18)
- [x] Develop User Interface (Aug. 23)
- [ ] Allow Item Rearranging (Aug. 26)
- [x] Show user first row of inventory in toolbar (Aug. 27)
- [x] Improve unit tests to encapsulate entire feature (Aug. 28)

**Completion Deadline:** Aug. 30

# **Dependencies**
Team 1: #7 as this will be extension of the basic item class and thus, we will have to ensure that it functions with their extension to this class 

# **Documentation**
[Inventory](https://github.com/UQcsse3200/2023-studio-1/wiki/Inventory)

# **Members**
- Tristan Duncombe @tristanduncombe 
- Adam Fittler @adamFittlerUQ 
- Abhinav @Abhinavmohindersingh 
- Nimesh Garg @nimeshgarg 
- Leonard Guo @mashoo12
