### ISSUE TITLE
Farming tools

### ISSUE THREAD

**Issue by 86LAK** [UQcsse3200/2023-studio-1#51]
# **Description**
**Task:** Finishing tools implementation including all required farming tools for the game
**Feature:** #7 

This task is to fully implement hoe, shovel, watering can and sickle into the game. Including interaction with the map. 
Implementing a tool interaction with the environment (map). Implement hoe, shovel, sickle, and watering can. 
Junit testing for all tool components and events. Wiki update for items and how to create own tools and items. 

# **Dependencies**
- [ ] #11 
- [ ] #8 
- [x] #12 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] View and understand current tool component and factory
- [x] Create action  event on item use.  
- [x] Fully implement hoe, watering can, sickle  and shovel (27/8)
- [x]  Junit tests for all above and wiki update on tool component (28/8)
 
**Completion Deadline:** Aug. 28

# **Documentation**
https://github.com/UQcsse3200/2023-studio-1/wiki/Items
 
 
# **Member**
- Shanon Lakshan Chandrasekara @86LAK 
- Jackson Trenerry @JTrenerry

**Comment by 86LAK** [comment]
@JTrenerry run a pull when you can . pulled from main onto our branch
