### ISSUE TITLE
Code smells

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#528]
**Task:** Cleaning up the code.
**Feature:** #544 
Recently the the planet has become quite pungent with a rubbish filled smell, is that cow fertilizer or team 1's code, we will never know! But these few small changes should increase the air quality (and our code) to a reasonable level, this may also unveil possible bugs within the code and as such benefit the overall state of the game from a player perspective and not just a game dev one!
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Oct. 3) Remove 300 code smells
- [x] Step 2 (Oct. 5) Remove 500 code smells
- [x] Step 3 (Oct. 6) Remove 700 code smells
- [x] Step 4 (Oct. 15) Bye Bye code smells (Remove 900 code smells)
 
**Completion Deadline:** Oct. 15

# **Member**
- Jackson Trenerry @JTrenerry 
- Lakshan Chandrasekara @86LAK 
- Tristan Duncombe @tristanduncombe 
- Abhinav @Abhinavmohindersingh

**Comment by JTrenerry** [comment]
PR #527 #526 were also apart of this.

**Comment by JTrenerry** [comment]
Start was 1070 -> 919 -> 861

**Comment by vilnor** [comment]
10/10 issue description

**Comment by JTrenerry** [comment]
no done yet

**Comment by 86LAK** [comment]
841 smells, 4 bugs and 6 security hotspots now

**Comment by JTrenerry** [comment]
Down to 821 code smells, 1 bug and 6 security hotspots

**Comment by JTrenerry** [comment]
WE DID IT!!!!

**Comment by 86LAK** [comment]
We are back!!! just heading to sleep

**Comment by JTrenerry** [comment]
Down to 712 code smells, 0 security hotspots and 1 bug

**Comment by JTrenerry** [comment]
> Down to 712 code smells, 0 security hotspots and 1 bug

bug was removed making it just 712 code smells

**Comment by JTrenerry** [comment]
712 -> 708 by team 5

**Comment by JTrenerry** [comment]
708 -> 628 done in #548

**Comment by JTrenerry** [comment]
From above pr #550 628 -> 626 (removed all consistency code smells)

**Comment by 86LAK** [comment]
We back baby

**Comment by 86LAK** [comment]
And we return again!!!

**Comment by 86LAK** [comment]
WE now have 550 smells.

**Comment by JTrenerry** [comment]
Went from 626 -> 539, marking 500 off (1070 -> 539 (4 was done by other people than those on ticket))

**Comment by JTrenerry** [comment]
539 -> 498 from @Abhinavmohindersingh

**Comment by 86LAK** [comment]
we back

**Comment by 86LAK** [comment]
down to 357

**Comment by 86LAK** [comment]
only 217 code smells to go !!!!! 🚜 👯

**Comment by JTrenerry** [comment]
217 -> 214

**Comment by JTrenerry** [comment]
214 -> 161 code smells from #579

**Comment by JTrenerry** [comment]
1070 -> 161 (4 from team 5) (50 from team 8) (855 from team 1)

**Comment by p-lahanas** [comment]
182 ->171 (several teams with unused imports)
