### ISSUE TITLE
Non Player Entity Movement Modifiers

### ISSUE THREAD

**Issue by HunterWhitty** [UQcsse3200/2023-studio-1#551]
# **Description**
Currently, entities have a movement speed modifier which is kept in the PhysicsMovementComponent class. This variable is represented as a static Vector2 instance. The goal of this feature ticket is to introduce a movement speed modifier that is affected by the type of terrain the entity is standing on.

## SubFeature/component
- Make it so that the terrain movement modifiers only affect non-flying entities

# **Milestones**
- [x] Successfully implement movement modifiers within the PhysicsMovementComponent (Oct. 6)
- [x] Update JUnit tests broken by implementing code which requires a GameArea and GameMap to function (Oct. 8)
- [x] Modify the implementation of the terrain movement modifiers to only affect non-flying entities (Oct. 9)
- [x] Create JUnit tests for both Terrain Movement Modifiers for the player entity, non-player entities, and non-player flying entities (Oct. 12)

**Completion Deadline:** Oct. 12

# **Documentation**
- [Terrain Movement Modifiers](https://github.com/UQcsse3200/2023-studio-1/wiki/Terrain-Movement-Modifiers)

# **Members**
- Hunter (HunterWhitty) (Hunter Whitlock)
