### ISSUE TITLE
Clean up code & Improve Documentation

### ISSUE THREAD

**Issue by Quarter-645** [UQcsse3200/2023-studio-1#556]
# **Description**
**Task:** Clean up code & Improve Documentation
**Feature:** Polish and Final Integration #560

The current state of the documentation lacks detail that teams may need to bug fix and improve code. Furthermore, there are some remaining code smells that have occurred throughout the development process. The purpose of this task is to implement improvements to the documentation and to correct code smells. This task will be completed at an accelerated rate as to allow for programmers from other teams to bug fix and understand integration better. There is also intent to finalise a missing functionality from the last sprint, that being saving/loading.
 
# **Milestones**
- [ ] Correct Code Smells (Oct. 11)
- [x] Correct Documentation (Oct. 11)
- [x] Update saving and loading of plants to work properly with new plant state (Oct. 13)
 
**Completion Deadline:** Oct. 11

# **Member**
- Name (GitHub Username) (Slack Handle)
- Connor (@Quarter-645) (Connor Morrison)
- Tom (@tomedwa) (Tom Edwards)
- Aadya @abhat0 (Aadya)
- Sanchit (@Sanchitjain16) (Sanchit Jain)
- Zebb (@ZebbMcAteer) (Zebb)
- Codie (@kodee-koder) (Codie Chung)

**Comment by JTrenerry** [comment]
Hey, I think we can deal with code smells, we plan to get them done reasonably quick #528

**Comment by Quarter-645** [comment]
https://youtu.be/dQw4w9WgXcQ @JTrenerry
