### ISSUE TITLE
Unit tests for plant classes

### ISSUE THREAD

**Issue by abhat0** [UQcsse3200/2023-studio-1#558]
# **Description**
**Task:** [Unit tests for plant classes](558).
**Feature:** [Polish and Final Integration](560)

Adding unit tests for all plant related classes and other classes that Team 6 has done over the semester. Unit tests should achieve 90-100% code coverage.
 
# **Dependencies**
Code in plant related classes should be finalized, including classes added/edited in the following feature tickets:
- [x] [Clean code](556)
- [x] [UI adjustments and quests](559)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Complete unit tests for our classes in the `entities` package, e.g., `PlantFactoryTest.java` (Oct. 10)
- [x] Complete unit tests for our classes in the `components/plants` package, e.g., `PlantAreaOfEffectComponent.java`, `PlantComponent.java`, `PlantInfoDisplayComponent.java`, `PlantMouseHoverComponent.java`, `PlantProximityComponent.java` (Oct. 10)
- [x] Complete unit tests for our classes in the `services` package, e.g.: `PlantCommandService.java`, `PlantInfoService.java`, etc... (Oct. 17)
- [x] Complete unit tests for our classes in the `UI` package, e.g.: `PlantCommand.java` (Oct. 17)

**Completion Deadline:** Oct. 17
 
# **Documentation**
- [JavaDoc](x)
 
# **Member**
- Aadya Bhatia (@abhat0) (Aadya Bhatia)
- Thomas Edwards (@tomedwa) (tomedwa)

**Comment by abhat0** [comment]
@tomedwa @Quarter-645 @Sanchitjain16 
Please add any new classes you've created or any that I've missed.
