### ISSUE TITLE
Design & Implement Optional Quests

### ISSUE THREAD

**Issue by Quarter-645** [UQcsse3200/2023-studio-1#559]
# **Description**
**Task:** Design & Implement Optional Quests
**Feature:** Polish and Final Integration #560

Optional quests involving plant items have yet to be fully implemented. As such, more quests will be implemented to complete this task and flesh out a portion of game.

# **Dependencies**
- [ ] Optional Quest System
- [ ] Plant Functionality
 
# **Milestones**
- [ ] Design Quests (Oct. 10)
- [ ] Implement Quests (Oct. 11)
 
**Completion Deadline:** Oct. 11
 
# **Member**
- Tom (@tomedwa) (Tom Edwards)
