### ISSUE TITLE
J Unit Tests for PlantConponents and PlantFactory

### ISSUE THREAD

**Issue by kodee-koder** [UQcsse3200/2023-studio-1#56]
# **Description**
**Task:** Write J Unit Tests for the PlantConfigs and PlantFactory CLasses
**Feature:** [Plant Component and Plants](#20)

The tests will ensure the functions of each class are working as intended.

# **Dependencies**

- [x] PlantComponents completion (#xx)
- [x] PlantFactory completion (#xx)
 

**Completion Deadline:** Aug. 29

- [x] Unit tests implemented for PlantComponents (Codie)
- [x] Unit tests implemented for PlantFactory (Aadya)
 
 
# **Member**
- Codie (@kodee-koder ) (@Codie Chung)
- Aadya (@abhat0 ) (@Aadya)
