### ISSUE TITLE
Polish and Final Integration

### ISSUE THREAD

**Issue by Quarter-645** [UQcsse3200/2023-studio-1#560]
# **Description**
Currently the majority of items team 6 has provided functions as intended, other than those connected to this feature ticket, as such the main effort of this sprint is to polish and finish final integration. This will involve improved documentation, bug fixing, sound system integration, implementing optional quests, user interface adjustments, and testing.

Documentation & Bug Fixing:
Improving detail in previous documentation and for any tasks in this sprint. Also, correcting bugs such as dropped items displaying incorrectly.

Sound System Integration:
Updating sound effects to play using the sound system.

Optional Quests:
Adding optional quests that relate to plants.

User Interface Adjustments:
Moving progress bar and implementing plant scanner

Tests:
Improving test coverage for code

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Documentation and bug fixing (Oct. 11)
- [x] Sound System Integration (Oct. 10)
- [x] Optional Quests (Oct. 09)
- [x] User Interface Adjustments (Oct. 10)
- [x] Tests (Oct. 11)

**Completion Deadline:** Oct. 11

# **Members**
- Connor (@Quarter-645) (Connor Morrison)
- Tom (@tomedwa) (Tom Edwards)
- Aadya @abhat0 (Aadya)
- Sanchit (@Sanchitjain16) (Sanchit Jain)
- Zebb (@ZebbMcAteer) (Zebb)
- Codie (@kodee-koder) (Codie Chung)
