### ISSUE TITLE
Complete Inventory

### ISSUE THREAD

**Issue by tristanduncombe** [UQcsse3200/2023-studio-1#567]
# **Description**
Throughout Sprint 1, 2, and 3, the inventory has been improved and developed to a functional level. This feature seeks to add improvements to ensure that the inventory is full and feature complete and adds nice to have functionality to enable gameplay mechanics and improve the user experience and user interface. This feature should be complete by the half way through Sprint 4 and it should be closely monitored for adverse consequences on the code base.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Drag and Drop Between Inventories (Oct. 08)
- [ ] Drag to Drop Item (Oct. 09)
- [x] Delete Items in Inventory (Oct. 10)
- [x] Resolve Lag when an inventoryDisplay is created (Oct. 08)
- [x] Resolve inventory moving to the bottom left of the screen when alt tabbing (Oct. 08)
- [x] Add open inventory sound (Oct. 06)
- [x] Add Inventory quests (Oct. 08)
- [x] Improve styling of InventoryDisplay and ToolbarDisplay (Oct. 10)

**Completion Deadline:** Oct. 11

# **Documentation**
- [Inventory](../wiki/Inventory)

# **Members**
- Tristan Duncombe @tristanduncombe  Tristan Duncombe
