### ISSUE TITLE
Plant Sprites

### ISSUE THREAD

**Issue by abhat0** [UQcsse3200/2023-studio-1#57]
# **Description**
**Task:** [Plant Sprites](#57)
**Feature:** [Plant Components](#20)
 
Plants will have a spacey twist.

Will create a sprite for plants in each of the following categories: 
- food (cosmicCob) 
- deadly (atropaBelladonna)
- defence (venusFlyTrap)
- health (aloeVera)
- repair (hammerPlant)
- production (waterWeed)

Sprites will be created following the stylistic guide as described in [Art Guidelines].

# **Dependencies**
- [x] Size, shading, and colours will follow [Art Guidelines](Art-Guidelines).
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Brainstorm a plant concept for each category (Aug. 24)
- [x] Sprite outlines for each category (Aug. 26)
- [x] Sprite shading for each category (Aug. 28)
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- Wiki - [Plant Properties and Types](Plant-Properties-and-Types)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Aadya (abhat0) (Aadya Bhatia)
