### ISSUE TITLE
Add open inventory sound

### ISSUE THREAD

**Issue by tristanduncombe** [UQcsse3200/2023-studio-1#573]
# **Description**
**Task:** [Add open inventory sound](#573).
**Feature:** [Complete Inventory](#570)
 
 A nice JUICE feature would be the implementation of an inventory opening/closing sound. This ticket seeks to add that sound effect and the ability to pass a sound effect for opening to inventory display (for chests and other inventories)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Find a sound (i.e opening rucksack) (Oct. 07)
- [x] Implement sound (Oct. 08)
- [x] Make it possible to pass sound on creation of inventoryDisplay (Oct. 09)

**Completion Deadline:** Oct. 09
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
