### ISSUE TITLE
Improve styling of inventoryDisplay and toolbarDisplay

### ISSUE THREAD

**Issue by tristanduncombe** [UQcsse3200/2023-studio-1#576]
# **Description**
**Task:** [Improve styling of inventoryDisplay and toolbarDisplay](#568).
**Feature:** [Complete Inventory](#567)

Currently the inventoryDisplay and toolbarDisplay do not match the style of the game and are not consistent. This ticket seeks to resolve this issue.

# **Dependencies**
- [ ] Window skin needs to be created(#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Improve Styling of inventoryDisplay (Oct. 08)
- [x] Improve Styling of toolbarDisplay (Oct. 08)
- [x] Add number to inventory to show respective slot number and selection (Oct. 13)
- [x] Remove need for the ItemFrame and Selection Image, use Libgdx Rectangle Instead (Oct. 13)
- [ ] Verify skin satisfies design committee's design (Oct. 15)
 
**Completion Deadline:** Oct. 16

# **Documentation**
- [Inventory](../wiki/Inventory)
 
# **Member**
- Tristan Duncombe (@tristanduncombe) Tristan Duncombe

**Comment by tristanduncombe** [comment]
It seems as though the Skin will not be completed. May need to be merged with the new skin.
