### ISSUE TITLE
Implement PlantComponent class

### ISSUE THREAD

**Issue by tomedwa** [UQcsse3200/2023-studio-1#58]
# **Description**
**Task:** Implement PlantComponent class (#58).
**Feature:** Plant Component and Plants (#20)

Create the PlantComponent class to establish a foundation for all plant-related functionality in Sprint 1. This class will serve as the base for various plant types and will encapsulate essential properties and behaviours shared by all plants.

# **Dependencies**
- [x] plant.json (#55) - Dependent for the relevant plant properties passed to the constructor of the PlantComponent class.
- [x] **CropTileComponent** #8 : Dependent for getting the growthRate from the tile.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a PlantComponent class that extends the existing component class (25/08)
- [x] Initialise private class variables that reflect the required properties defined in the plant.json file (26/08)
- [x] Create constructor for the plant component class (28/08)
- [x] Create relavent getters and setters for the class (28/08)
- [x] Finalise the Wiki for the PlantCompontClass (29/08)
 
**Completion Deadline:** 29/08
 
# **Documentation**
- wiki: https://github.com/UQcsse3200/2023-studio-1/wiki/Plant-Component
- javadoc: https://uqcsse3200.github.io/2023-studio-1/com/csse3200/game/components/plants/PlantComponent.html
 
# **Member**
- Tom Edwards (tomedwa) (Thomas Edwards)
- Sanchit (@Sanchitjain16) (Sanchit Jain)
