### ISSUE TITLE
Sounds for placeables and tools

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#580]
# **Description**
**Task:** Sound design for placeable items and tools.
**Feature:** #544 

The game is lacking juice!!! So to help this red team aka DJ khaled team will be implementing sounds for things implemented by us across the semester. This includes placeables, items, tools etc 

# **Dependencies**

- [x] #385 
- [ ] #582 
- [x] #310 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] List of things to be implemented (Oct. 8)
- [x] read sound system wiki (Oct. 8)
- [x] source sounds wav files for all below (Oct 10)
- [x] Have half the sounds implemented (Oct 14)
**Completion Deadline:** October 17

# **List of things to implement sounds for**
Sounds for 

- [x] tools
    - [x] shovel
    - [x] hoe
    - [x] scythe
    - [x] watering can
    - [x] fishing rod
- [x] placeables
    - [x] noise will be the same "place noise" for the following
        - [x] chests
        - [x] sprinklers
        - [x] fences
        - [x] gates
        - [x] pumps
- [x] tractor
    - [x] enter/startup noise
 
# **Documentation**
- TO BE DONE
- will incl links to everywhere  I implemented sounds ig 
 
# **Member**
-  Shanon Lakshan Chandrasekara @86LAK
- Peter ASMR @p-lahanas

**Comment by 86LAK** [comment]
i am the sound guy. i will write ticket probs tomoz :)

**Comment by 86LAK** [comment]
i wrote the task ticket 👍

**Comment by 86LAK** [comment]
Did a test run and got tractor working. took the noise from https://www.wavsource.com/sfx/sfx.htm
with policy https://www.wavsource.com/dis.htm

**Comment by 86LAK** [comment]
stuck until fishing guy does fishing stuff @JTrenerry
