### ISSUE TITLE
Fishing

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#582]
# **Description**
**Task:** Adds fishing
**Feature:** #544

The majority of the map feels empty or useless to gameplay, and as such to make more use of the map fishing will be added. This will force the player to use the beaches to catch fish for quests or food whilst providing a stable source of food for the early game (while they wait for plants to grow). Since this only forces the player to the water we will also be making lava fishing, this will allow the player to catch special fish that will heal / feed the player an increased amount in comparison to other foods. This will hopefully force the player to expand their horizons and explore more of the map.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Oct. 17) - Create fishing rod item
- [x] Step 2 (Oct. 17) - Create fishing quests
- [x] Step 3 (Oct. 17) - Create fishing animations and tool art
- [x] Step 4 (Oct. 17) - Create fishing mechanics
- [x] Step 5 (Oct. 17) - Create documentation on fishing
- [ ] Step 6 (Oct. 17) - #596 
- [x] Step 7 (Oct. 17) - Create tests for the fishing rod
- [x] Step 8 (Oct. 17) - Trigger animations when needed.
 
**Completion Deadline:** Oct.17
 
# **Documentation**
https://github.com/UQcsse3200/2023-studio-1/wiki/Tool-Types
https://github.com/UQcsse3200/2023-studio-1/wiki/Fishing
https://github.com/UQcsse3200/2023-studio-1/wiki/Fish
 
# **Member**
- Jackson Trenerry @JTrenerry

**Comment by JTrenerry** [comment]
Tool / item sprites are done, only art to do is animating the cast of the rod

**Comment by JTrenerry** [comment]
Fish eating is done

**Comment by JTrenerry** [comment]
Just waiting on art in game / to be triggered correctly

**Comment by JTrenerry** [comment]
Since this was done pre quick might make more fosh
