### ISSUE TITLE
Add toggleable map

### ISSUE THREAD

**Issue by AngusWhittaker** [UQcsse3200/2023-studio-1#584]
# **Description**
Currently, the player may get lost while wandering around the map due to the size until they are more experienced. To help minimise this confusion a toggleable map will be created such that the player can know the map layout and deduce where they are located. This map should be toggleable using a key command such as 'M'.

## **Examples**
- **Toggleable Map**: The user can press a key, such as 'M', to display a map on the screen.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Create a displayable map (Oct. 8)
- [x] Make it so that the player keyboard toggles its appearance (Oct. 9)

**Completion Deadline:** Oct. 11

# **Extras (optional)**
- [x] Would be nice to have the map display where the player is located as well via a visual cue.

# **Members**
- Angus (@AngusWhittaker)
- Thang (@thanghoang7020202 )
