### ISSUE TITLE
Storyline Improvements & Tuning

### ISSUE THREAD

**Issue by Tom-Strooper** [UQcsse3200/2023-studio-1#588]
# Description
This feature involves improving the game’s storyline by adding a secret ending to the game (when 100% of the quests and achievements have been completed, this idea is up to the studio’s discretion), by integrating other teams’ features into the storyline (e.g., fishing, the tractor, placeable items, hostile animals), and by balancing the overall progression of the game.

## Features
- [ ] Discuss possibility of secret ending with studio (and add into game if enough support)
- [ ] Integration of fishing, tractor, placeables and hostile animals into the game
- [ ] Balancing updates
	- [ ] Game/quest duration
	- [ ] Make it harder for oxygen to increase
	- Possible other balancing issues wrt how features are introduced to the player

# Dependencies
Fishing #582
Placeables #404

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Goal 1 (Aug. 20)
- [ ] Goal 2 (Aug. 23)
- [ ] Goal 3 (Aug. 26)
- [ ] Goal 4 (Aug. 28)

**Completion Deadline:** Aug. 30

# Documentation
- [Storyline](https://github.com/UQcsse3200/2023-studio-1/wiki/Storyline)

# Members
-
