### ISSUE TITLE
Particle/Lighting System Improvements

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#589]
# Description
This feature involves improving the Particle System software implementation, as well as adding particle effects and lighting effects to a bunch of different in-game interactions and events.

## Features
- [x] General improvements and extension of the ParticleService
- [ ] Add particle effects for…
	- [x] Player sprinting (like kicking up dirt)
	- [x] Harvesting crops
	- [x] Player tilling the ground
	- [x] Feeding animals
	- [x] Hitting enemies
- [x] Add lighting effects for…
	- [x] Alien NPC (aura light)
	- [x] Some plants (e.g., aloe vera, deadly nightshade)
- [x] Add mixed effects for:
	- [x] Player success interactions (e.g., completing quests/achievements, adding ship parts, taming animals, catching fish) - [motivation](https://www.youtube.com/watch?v=2On73cfe41U)

# Milestones
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Extend `ParticleService` Oct 10
- [x] Create basic `ParticleComponent` Oct 11
- [x] Create new particle effects in libgdx particle editor for features above
- [x] Integrate lighting effects with particle effects
- [x] Fully integrate lighting and particle effects into game

**Completion Deadline:** Oct. 15

# Documentation
- [Particle Effects](../wiki/Particle-Effects)
- [Lighting System](https://github.com/UQcsse3200/2023-studio-1/wiki/Lighting-System)

# Members
- Lucas Hicks (@lucashicks1) Lucas Hicks
