### ISSUE TITLE
Implement Inventory Hotkey Selection

### ISSUE THREAD

**Issue by adamFittlerUQ** [UQcsse3200/2023-studio-1#59]
# **Description**
**Task:** Implement Hotkey Selection
**Feature:** Player Inventory

The goal of this task is to implement a feature that allows players to quickly select and use farming tools from their inventory using hotkeys. The selected hotkeys will correspond to numeric keys (1-0) on the keyboard, offering players a convenient way to switch between tools for efficient farming. This selection mechanism is inspired by similar mechanics found in farming games like Stardew Valley and Harvest Moon.

This task involves enhancing the player's experience by enabling them to assign specific farming tools to hotkeys. When a player presses a designated hotkey, the corresponding tool in their inventory will be selected for immediate use. For instance, if a player assigns a watering can to the "1" hotkey, they can press "1" to quickly water their crops without needing to access the inventory menu.
 
# **Example** 
Part: Imagine a player is tending to their crops and notices that some areas need watering. With the tool hotkey selection feature, they can press the assigned hotkey for the watering can (e.g., "1") and efficiently water the crops without interrupting their workflow.

# **Dependencies**
This task relies on the player inventory component class being correctly implemented and the inventory functionality working correctly as completed in the previous feature tasks.  This also relies upon having the player class properly setup  to have an inventory component  as well as having a way of identifying what the user has selected.  In the worse case scenario I will implement this feature myself. 

- [x]  Inventory component basic implementation
- [x] Player component basic implementation

# **Milestones**
List of steps that need to be completed for this task.
- [x] Breakdown and understand the current implementations of the player and inventory classes (Aug. 24)
- [x] Research Implementation of Hotkeys and Begin setting the foundation in both the inventory and player classes (Aug. 25)
- [x] Refine hotkey implementation (Aug. 26)
- [x] Write a comprehensive test suite to check if the hotkeys are correctly working (Aug. 27)
 
**Completion Deadline:** Aug. 28
 
# **Member**
- Adam (adamFittlerUQ) (Adam Fittler)
