### ISSUE TITLE
Weather System Effects & Improvements

### ISSUE THREAD

**Issue by shristigupta1408** [UQcsse3200/2023-studio-1#590]
# Description
This feature involves improving the weather system by adding additional visual effects, additional weather events, improving the design of the ClimateController/WeatherEvent classes, and adding mechanical consequences to weather events.

## Features
- [x] Adding additional weather effects
	- [x] `SnowStormEvent`
	- [x] `RainStormEvent`
- [x] Add lighting effects to all weather events
- [x] Add sound effects to all weather events
- [x] Weather interactions
	- [x] Increase/decrease plant health
	- [x] Increase/decrease water levels of CropTiles
	- [x] Increase/decrease player health
	- [x] Player speed (for sufficiently strong rainstorms/acid showers, and for snow storms)
	- [x] Affect quality/ability of plant effects (e.g., during snow storms, aoe effects of plants reduce)
	- [x] Dousing flames of torches

# Dependencies
 - Completion of sound system into main and ability 

# Milestones
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Add additional weather events
- [x] Add weather interactions
- [x] Add lighting effects
- [x] Add sound effects

**Completion Deadline:** Oct 15

# Documentation
- [Weather and Climate System](https://github.com/UQcsse3200/2023-studio-1/wiki/Weather-and-Climate-System)

# Members
- Shristi (@shristigupta1408) (Shristi Gupta)
