### ISSUE TITLE
Weather Interactions

### ISSUE THREAD

**Issue by shristigupta1408** [UQcsse3200/2023-studio-1#592]
# **Description**
**Task:** Weather Interactions
**Feature:** Weather System Effects & Improvements (#590)

This task ticket is to implement weather interactions to improve gameplay dependent on weather events. These interactions will have an impact on many areas of the game, including plant health, water levels, player health, player speed, and the quality/ability of plant effects under various weather situations.

# **Dependencies**

- [x] Add New Weather Events (#603)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Effects on plants 
- [x] Effects on cropTiles 
- [x] Effects on players 
- [x] Effects on animals
- [x] Updating Tests
- [ ] Wiki documentation
 
**Completion Deadline:** Oct 15
 
# **Documentation**
- [Main description of feature](../wiki/Weather-and-Climate-System)
 
# **Member**
- Shristi (@shristigupta1408 ) (Shristi Gupta)
