### ISSUE TITLE
Mission System Improvements

### ISSUE THREAD

**Issue by Tom-Strooper** [UQcsse3200/2023-studio-1#598]
# Description
**Task:** Mission System Improvements (#598)
**Feature:** Storyline Improvements & Tuning (#588)

Involves minor updates to the mission system backend.
 
# Dependencies
- Mission System

# Milestones
- [x] Make `QuestReward` use lists of `Supplier<Quest>` instead of just `Quest`, to delay the creation of `Quest` until necessary (Oct 11)
- [x] Make `AutoQuest` have a few minutes of delay before collecting a reward (Oct 12)
- [x] Add `InventoryStateQuest` to replace "Home Sick" quest type (Oct 12)
- [x] Add `ConsumePlayerItemsReward` to add as a reward for the "Home Sick" quest (so the alien consuming berries has in-game mechanical effect) (Oct 12)
- [x] Remove QuestGiver notification for completed quests (Oct 12)
- [x] Increase text display speed for story screens (Oct 14)
- [x] Update testing suites to get better coverage (Oct 14)
- [x] Update javadocs for any additions (Oct 14)

# Member
-
