### ISSUE TITLE
Integrate Other Features into Storyline

### ISSUE THREAD

**Issue by Tom-Strooper** [UQcsse3200/2023-studio-1#599]
# **Description**
**Task:** Integrate Other Features into Storyline (#599)
**Feature:** Storyline Improvements & Tuning (#588)

Integrates features made by other teams into the game's storyline. This includes updating story rewards and dialogue to introduce hostile animals, placeables, and fishing into the game as per the wishes of the teams who created these features.

# **Dependencies**
- Mission System
- Fishing (#582)
- Placeables
- Hostile Animals & Weapons

# **Milestones**
- [ ] Integrate features as rewards (Oct 14)
- [ ] Update testing suites (Oct 14)
- [ ] Update javadocs (Oct 14)

# **Documentation**
- [Storyline](https://github.com/UQcsse3200/2023-studio-1/wiki/Storyline)
 
# **Member**
-

**Comment by Tom-Strooper** [comment]
Other teams will be integrating their own features into the storyline, so this is no longer a team 7 task
