### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by arj-sng** [UQcsse3200/2023-studio-1#6]
# **Description**
The Home Screen is the first page users visit when opening the game. The framework for the home screen which provides general functionality including buttons and background graphics that link to other pages such as the settings, start game, or game help and exit. The layout of the home screen will be managed by `MainMenuDisplay` and the result of clicking buttons such as the "Start Game" will be controlled by the class "MainMenuActions".  The action of clicking Settings or Help Menu will redirect the player to a new page controlled by a separate class `SettingsMenuDisplay` and `HelpMenuDisplay`, and the player will be able to return to the main menu by clicking the exit button on these pages. 

## SubFeature/component
- Settings - Controlled by `SettingsMenuDisplay` but will largely be blank until the game mechanics are full developed so that only relevant settings will be included
- Help Menu - A new class `HelpMenuDisplay` will need to be implemented for a page to describe the controls and objectives of the game
- Exit - A button on both the Settings and Help Menu page to return the player to the main menu
- Start Game - Button to begin the game
- Exit Game - Button to exit the game
- Background Graphics - Background visual graphics for the main menu, settings and help menu pages, controlled by `MainMenuScreen`, `SettingsScreen` and a new class `HelpMenuScreen`

# **Dependencies**

The settings screen will be largely blank until the game mechanics are fully developed, as these will inform what settings users can change. Will have to communicate with other feature teams to ensure that the game help page sufficiently covers the controls and objectives for the game
- Player Movement (https://github.com/UQcsse3200/2023-studio-1/issues/14) 
- Operating Player Inventory (https://github.com/UQcsse3200/2023-studio-1/issues/5)
- Taming Animals (https://github.com/UQcsse3200/2023-studio-1/issues/4)
- Using Farm Tools (https://github.com/UQcsse3200/2023-studio-1/issues/7)

# **Milestones**
- [x] Background Graphics (Aug. 20) 
  - [x] #44
  - [x] Implement background animation on menu screens
- [x] Basic Functionality (Aug. 25)
  - [x] Create new classes `HelpMenuScreen` and `HelpMenuDisplay` for the help menu page (Implemented as ControlsMenuDisplay)
  - [x] Create placeholders for potential settings for the game on the settings page
  - [x] Create buttons for new features such as the help menu page
  - [x] Update `MainMenuActions` to link all the pages together
  - [x] Implement the background visuals for all the pages
- [x] UI Layout (Aug. 28)
  - [x] Finalise the visual layout of the UI - button sizes, button positions, colour scheme etc.
- [x] Introduction Screen (Aug. 30)
  - [x] Add first version of animation and story
- [x] UI Skin (Aug. 28)
  - [x] Implement preliminary pixel themed skin
  - [x] Implement preliminary space themed skin
- [x] Finalise Testing (Aug. 30)
  - [x] Thorough testing and debugging of `MainMenuActions`

**Completion Deadline:** Aug. 30

# **Extras**
- [ ] Animated transition from Home page to the start of the game (with a brief background of the story)

# **Documentation**
- [Art Influences](https://github.com/UQcsse3200/2023-studio-1/wiki/Art-Influences)
- [UI](https://github.com/UQcsse3200/2023-studio-1/wiki/UI)
- [Storyline](https://github.com/UQcsse3200/2023-studio-1/wiki/Storyline)

# **Members**
- Gil Wise (@gilgilgilgilgil) (Gil)
- Manav Trivedi (@ManavTriv) (Manav Trivedi)
- Daniel Cottrell (@daniel-cottrell) (Daniel Cottrell)
- Matilda Damman (@MatildaDamman) (Matilda Damman)
- Arjun Singh (@arj-sng) (Arjun Singh)

**Comment by MatildaDamman** [comment]
<img width="668" alt="Screenshot 2023-08-23 at 9 24 58 am" src="https://github.com/UQcsse3200/2023-studio-1/assets/140562296/01c74dfb-749f-419a-9eae-64d5e22b9460">
<img width="666" alt="Screenshot 2023-08-23 at 9 24 50 am" src="https://github.com/UQcsse3200/2023-studio-1/assets/140562296/0d989691-0a2e-48da-a28d-bfb09b76eb81">

The very first iteration of the UI for the home screen system. These mocks were made so that team had a rough idea of the final design, and we knew what we were working towards. 
These mocks are to be changed as the design committee refines their colour schemes and other visual aspects.
