### ISSUE TITLE
Terminal Game Commands

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#60]
# In game terminal commands

This feature ticket is for the development of in-game commands that can be entered into the in-game terminal. These commands will speed up development for teams allowing them to advance through the the game through commands rather than playing the game. This will also reduce the amount of test code required for teams, cleaning up the project. This will most likely be an ongoing feature ticket until the main game features mature.

## SubFeature/component
The main parts of this feature will be documentation and the commands themselves. The documentation will allow players and developers to use the commands without having to memorise them.

## **Examples (optional)**
- **Add Item command**: Entering `addItem shovel` will add a `Shovel` item to a player's inventory without them having to find one and pick one up.
- **Set time command**: Entering `setTime 12` will set the game time to the 12th hour, without having to wait for the time to advance

# **Dependencies**
- Time System - #10 
- Player Tools - #7 
- Player Inventory - #5

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Brainstorm commands and command structure
- [x] Complete a basic wiki for these commands
- [x] Complete the `setTime` command
- [x] Complete the `setDay` command
- [x] Complete the `addItem` command
- [x] Complete the `spawn` command

**Completion Deadline:** TBD

# **Documentation**
- [Debug Terminal](https://github.com/UQcsse3200/2023-studio-1/wiki/Debug-Terminal)

# **Members**
- Lucas Hicks (@lucashicks1) (Lucas Hicks)

**Comment by UniversalTze** [comment]
Just a quick question for this feature, where will the player type these commands when playing the game. 
Like will they use the terminal or will there be like a command bar, that will allow them to use commands instead of using the keyboard buttons?

**Comment by lucashicks1** [comment]
> Just a quick question for this feature, where will the player type these commands when playing the game. Like will they use the terminal or will there be like a command bar, that will allow them to use commands instead of using the keyboard buttons?

Sorry only just saw this. They will use the in-game terminal (you can open it up by pressing F1). Have a look at this wiki page for a better explanation -> https://github.com/UQcsse3200/2023-studio-1/wiki/Debug-Terminal
