### ISSUE TITLE
Storyline - Balancing

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#600]
# **Description**
**Task:** Storyline - Balancing
**Feature:** [Storyline Improvements & Tuning](#588 ).

This task ticket is for making general balancing changes to the game and storyline. The main changes will be to game/quest duration, changing the rate at which oxygen level increases and any other balancing issues with respect to how different features are introduced to the player. Additionally, any bugs that are encountered with the storyline and general progression of the game will relate to this task ticket.

# **Dependencies**
- #137 - Oxygen system
- #588 - Storyline improvements
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Change game/quest duration (Oct. 10)
- [x] Discuss any storyline changes with studio (Oct. 11)
- [x] Changing oxygen level rates (Oct. 13)
- [x] Reduce decrease rate of water level (Oct. 13)
- [x] Reduce amount of water added when watering crop tiles (Oct. 13)
 
**Completion Deadline:** Oct. 14
 
# **Member**
-
