### ISSUE TITLE
Improvements to Particle System

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#601]
# **Description**
**Task:** Improvements to Particle System
**Feature:** [Particle/Lighting System Improvements](#589)

This task ticket is for general improvements and extensions to the current particle system (#441). These improvements would allow the rendering of smaller particles that are only present in one position rather than screen-wide particle effects (eg: rain). This will enable other effects to be rendered more easily in the game.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Creation of `ParticleEffectComponent` which can be attached to entities to render a particle effect on them (Oct. 10)
- [ ] Extend `ParticleService` to use these new components (Oct. 11)
- [ ] Testing for new component and extensions to service (Oct. 12)
- [ ] Use new features for particle effects introduced in other features/tasks (Oct. 13)
- [ ] Extend wiki to include new information in regards to system (Oct. 14)
 
**Completion Deadline:** Oct. 14
 
# **Documentation**
- [Particle System](../wiki/Particle-Effects)
 
# **Member**
- Lucas Hicks (@lucashicks1) (Lucas Hicks)
