### ISSUE TITLE
Add Particle and Light Effects to in-game Interactions

### ISSUE THREAD

**Issue by Tom-Strooper** [UQcsse3200/2023-studio-1#602]
# **Description**
**Task:** Add Particle and Light Effects to in-game Interactions ()
**Feature:** Particle/Lighting System Improvements (#589)

Adds particle and lighting effects to a variety of in-game player interactions to add juice to the game, and make interactions more enjoyable.

# **Dependencies**
- Particle System

# **Milestones**
- [ ] Add & implement particle effects when the player is sprinting
- [ ] Add & implement particle effects when harvesting
- [ ] Add & implement particle effects when tilling tiles
- [ ] Add & implement particle effects when feeding animals
- [ ] Add & implement particle effects when hitting or being hit by enemies
- [ ] Add & implement lighting effects around the Alien NPC
- [ ] Add & implement lighting effects around some plants (with auras)
- [ ] Add & implement lighting/particle effects for successful interactions (e.g., when an animal is tamed, when the player catches a fish, when the player completes an achievement, when the player collects a quest reward, when the player adds a ship part to the ship)

# **Documentation**
- [Particle Effects](https://github.com/UQcsse3200/2023-studio-1/wiki/Particle-Effects)

# **Member**
-
