### ISSUE TITLE
Add New Weather Events

### ISSUE THREAD

**Issue by Tom-Strooper** [UQcsse3200/2023-studio-1#603]
# **Description**
**Task:** Add New Weather Events ()
**Feature:** Weather System Effects & Improvements (#590)

Adds (at least) 2 new weather events into the game, along with their associated particle effects. Sound effects, lighting effects and game interactions of these new events are covered in other task tickets.

# **Dependencies**
- Weather System
- Particle System
- Lighting System

# **Milestones**
- [ ] Create SnowStormEvent class (Oct 11)
- [ ] Create RainStormEvent class (Oct 11)
- [ ] Updating testing suites (Oct 15)
- [ ] Update javadocs (Oct 15)
- [ ] Update wiki (Oct 15)

# **Documentation**
- [Weather and Climate System](https://github.com/UQcsse3200/2023-studio-1/wiki/Weather-and-Climate-System)
 
# **Member**
-
