### ISSUE TITLE
Weather Events - Lighting/Sound Effects

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#604]
# **Description**
**Task:** Weather Events - Lighting/Sound Effects
**Feature:** [Weather System Effects & Improvements](#590)

This task ticket is for adding sound and lighting effects to different weather events.
 
## **Example (optional)**
- **Sound Effects**: When an acid shower is occurring in the game, a rain sound effect would be played to increase the ambience and juice up the game.

# **Dependencies**

- [x] Sound System (#385)
- [x] Lighting System and Particle System Improvements (#589)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Sound files need to be created for various weather events (Oct 14)
	- [x] Rain sound for `RainStormEvent`
	- [x] Acid rain sound for `AcidShowerEvent`
	- [x] Snow sound for `BlizzardEvent`
	- [x] Solar storm sound for `SolarSurgeEvent`
- [x] Using lighting system improvements, change the in-game lighting when weather event is triggered (Oct 14)
 
**Completion Deadline:** Oct. 14
 
# **Documentation**
- [Main description of feature](../wiki/Weather-and-Climate-System)
- [Sound System](../wiki/Sound-System)
- [Particle System](../wiki/Particle-Effects)
- [Lighting System](../wiki/Lighting-System)
 
# **Member**
- Tom Strooper (@Tom-Strooper)
