### ISSUE TITLE
Visual Effects and User Feedback for Animal Interactions

### ISSUE THREAD

**Issue by pchsa** [UQcsse3200/2023-studio-1#621]
# **Description**
**Task:** Visual Effects and User Feedback for Animal Interactions (#).
**Feature:** Implement Alien Animals Advanced #168

In this task, we aim to improve the visual effects and user feedback for interactions between players and animals in the game. This includes improving combat knockback, visual feedback when damaging animals or when the player gets damaged, visual effects when feeding animals, and visual effects when the player is within an animal's range. For instance, when the player damages an animal, there should be appropriate visual cues to signify the impact of the attack, and when feeding an animal, there should be an animation or effect to indicate the successful interaction.

## **Example (optional)**
- **Damaging Animals**: When the player attacks an animal, there should be a particle effect or animation indicating the hit. The animal could also react visually to signify that it has been hurt.

- **Player Damage**: When the player receives damage from an animal, there should be a visual indicator, such as a screen shake or a red flash effect on the screen, to convey the impact.

- **Feeding Animals**: When the player feeds an animal, there should be a positive visual feedback, like hearts or  appearing above the animal's head, to show that the interaction was successful.

- **Animal Range**: When the player is within the range of an animal, there should be an indicator, such as an exclamation mark, to inform the player.

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Improve knockback effect for player-animal interactions (Oct. 7)
- [ ] Create visual effects for damaging animals and player damage (Oct. 8)
- [ ] Implement visual feedback for feeding animals (Oct. 9)
- [ ] Add visual indicators for player-animal interaction range (Oct. 10)

**Completion Deadline:** Aug. 23

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)

# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g., Richard (@AppleByter) (Richard Thomas)
