### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by tristanduncombe** [UQcsse3200/2023-studio-1#633]
# **Description**
**Task:** [Discord Rich Presence](#633).
**Feature:** [TBD](#001)

Add Discord Rich Presence to the Game. Make it so that it shows the game, what is being done actively, and add an icon and timer.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement Basic Rich Presence (Oct. 12)
- [x] Add Custom States for Specific Screens (Oct. 12)
- [x] Add Icon and Timer (Oct. 12)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Tristan Duncombe @tristanduncombe Tristan Duncombe
