### ISSUE TITLE
Add Animal and Weapon Sounds

### ISSUE THREAD

**Issue by v1dyut** [UQcsse3200/2023-studio-1#645]
# **Add Animal and Weapon Sounds**
**Task:** [Add Animal and Weapon Sounds](#645).
**Feature:** [Implement Alien Animals Advanced](#168) and [Implement Hostile Animals](#169).

To add JUICE and provide feedback to the player, audio sounds are being added for the animals and weapons. Specifically the following sounds,

*Animals*
- Hostile attack sounds
- Animal being fed sound

*Weapons*
- Gun shot sound
- Sword swing sound

# **Dependencies**
- [x] Sound System Implementation (#385)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Find sounds (Oct. 13)
- [x] Implement sounds into the game (Oct. 16)

**Completion Deadline:** Oct. 16

# **Documentation**
- [Hostiles](https://github.com/UQcsse3200/2023-studio-1/wiki/Hostile-Animals#hostile-species)
- [Animals](../wiki/Animals)

 
# **Member**
- @v1dyut 
- @UniversalTze
