### ISSUE TITLE
Add Inventory sounds

### ISSUE THREAD

**Issue by masoo12** [UQcsse3200/2023-studio-1#656]
# **Add Inventory sounds**
**Task:** [Add Inventory sounds](#3).
**Feature:** [Complete Inventory](#2)

This feature adds sounds to the inventory, such as drag and drop, throwing items into bin, and switching toolbar tabs.
Also adds new functionality to allow switching the toolbar display to show the next 10 items in the inventory.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add drag and drop sounds (Oct 14.)
- [x] Add sounds after dragging item into bins (Oct 14.)
- [x] Add sounds for when the toolbar switches (Oct 14.)
 
**Completion Deadline:** (Oct 14.)

# **Documentation**
- [Inventory](../wiki/Inventory)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Leonard (masoo12) (masoo12)
