### ISSUE TITLE
Modify Hostile Entity Indicator

### ISSUE THREAD

**Issue by ManavTriv** [UQcsse3200/2023-studio-1#660]
# **Description**

Modify the hostile entity indicator to address issues from sprint 3. The indicator should not overlap other UI components while it moves along the screen. The current implementation has a UI issue where it is hidden behind the time display, and quest display. This prevents the indicator from being visible in the top left and bottom left corners of the screen. Therefore this needs to be addressed.

Furthurmore, the `EntityIndicator` class should be updated and designed in a way that can be re-used for other purposes. Such as a pointer to other entities such as an NPC or a plant. This will allow the same implementation to be re-used instead of having to re-write code.

- [Entity Indicator](https://github.com/UQcsse3200/2023-studio-1/issues/182)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 : Adjust logic to prevent overlapping other UI elements
- [x] Step 2: Design the class so it can re-used for other purposes
- [x] Step 3 : Test functionality

**Completion Deadline:** Oct. 16

# **Documentation**
- https://github.com/UQcsse3200/2023-studio-1/wiki/Entity-Indicator

# **Member**
- Manav Trivedi (@ManavTriv)
