### ISSUE TITLE
More Quests

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#663]
# **Description**
**Task:** More Quests.
**Feature:** #544 

The game is empty. So to fix this more quests will be added to hopefully fill out the game and provide game play and things to do. These include fishing quests, and recursive quests such as watering plants, planting plants and taming animals which will reward you with placeables.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Oct. 17) - Fishing quest
- [x] Step 2 (Oct. 17) - Tame animal quest
- [x] Step 3 (Oct. 17) - Watering crops quest
- [x] Step 4 (Oct. 17) - Planting crops quest
 
**Completion Deadline:** Oct. 17
 
# Documentation
https://github.com/UQcsse3200/2023-studio-1/wiki/Game-Quests

# **Member**
- Jackson Trenerry @JTrenerry
