### ISSUE TITLE
New cutscenes

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#666]
# **Description**
In order to further progress the story and keep everything fresh a new cut-scene image will be used for some cut-scenes to decrease the similarity and increase freshness and juiciness of the game. It also will attempt to make an in game cut-scene rather than just a text box.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Goal 1 (Oct. 17) - Setup new Image for new cut-scene character
- [x] Goal 2 (Oct. 17) - Setup triggers and events for new cut-scenes
- [x] Goal 3 (Oct .17) - Setup in game cut-scene using AnimationRenderComponents

**Completion Deadline:** Oct. 17

# **Documentation**
https://github.com/UQcsse3200/2023-studio-1/wiki/Cutscene-Class

# **Members**
- Jackson Trenerry @JTrenerry
- Liv ([@vilnor](https://github.com/vilnor)) (Liv Ronda)
