### ISSUE TITLE
Implement PanicTask.

### ISSUE THREAD

**Issue by pchsa** [UQcsse3200/2023-studio-1#67]
# **Description**
**Task:** Implement Panic Task(#3).
**Feature:** [Basic Alien Animal Behaviour](#4)

The task involves implementing a Panic Task for AI entities. The Panic Task will cause the AI entity to move randomly within a specified range for a certain duration. This behavior should enhance the AI's response to triggering events, adding more dynamic behavior to the game's AI system.
 
## **Example (optional)**
- **Scenario**: An AI enemy is hit by a player's attack.
- **Panic Behavior**: The AI enemy enters a state of panic for a brief duration, moving randomly within a predefined range. This makes the AI's response less predictable and adds variety to the gameplay.

# **Dependencies**
To implement this, first a way to trigger a task via an event (e.g. "hit") must be implemented. This EventTriggeredTask must integrate with the existing Goal Oriented Action Plan of the AITaskComponent. Creation of this will be included in this ticket.

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement TimedTask (Aug. 24)
- [x] Implement PanicTask (Aug. 25)
- [x] Write Test (Aug. 26)
- [x] Make documentation

# **Extras**'
- [ ] Refactor TimedTask by making an initial EventTriggeredTask which TimedTask inherits from. Currently TimedTask is triggered by event will stop after setduration. In future sprints, we should be able to trigger off and on tasks for more dynamic NPC behaviour (making animal follow you / sit). (next sprint probably)

**Completion Deadline:** Aug. 26

 
# **Documentation**
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Pocholo (pchsa) (Pocholo)

**Comment by v1dyut** [comment]
No longer required as tasks were refactored.
