### ISSUE TITLE
Implementing the Time UI Display

### ISSUE THREAD

**Issue by daniel-cottrell** [UQcsse3200/2023-studio-1#69]
# **Implementing the Time UI Display**
**Task:** [Implement Time UI](#3).
**Feature:** [Time System](#2)

The UI which shows the current game time will be displayed on the Main Game Screen.  `GameTimeDisplay` extends `UIComponent` and will detect the time through a time controller. It will be positioned in the top left corner of the screen, and continually update its planet image and the time label depending on the time.
 
## **Example**
- **Visual Appearance**: The clock display will always appear in the game, updating as time progresses.

# **Dependencies**
- #10
- #41
- #71

# **Milestones**
- [x] Step 1 (Aug. 24): Set up the positioning of the clock frame, the planet image and the time label correctly.
- [x] Step 2 (Aug. 25): Add a function in `GameTimeDisplay` to manually be able to set the planet image and time label.
- [x] Step 3 (Aug. 25): Add functionality to get the current game time and update the time display based on it.
- [x] Step 4 (Aug. 27): Add unit tests to check that `GameTimeDisplay` behaves correctly with `GameTime` and `TimeController`.
- [x] Step 5 (Aug 28): Update the relevant wiki with information relating to `GameTimeDisplay`.
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- [Time System](../wiki/Time-System)
 
# **Member**
- Daniel Cottrell (@daniel-cottrell) (Daniel Cottrell)
- Manav Trivedi (@ManavTriv) (Manav Trivedi)
- Gil Wise (@gilgilgilgilgil) (Gil)
