### ISSUE TITLE
Time Functionality

### ISSUE THREAD

**Issue by ManavTriv** [UQcsse3200/2023-studio-1#71]
# **Description**
**Task:** Time Functionality
**Feature:** [Feature which this tasks contributes to implementing](#2)](https://github.com/UQcsse3200/2023-studio-1/issues/10)

The functionality of the time system will be implemented in the using an observer pattern. 
- A new class `TimeController` will be the observable
- `Entity` and 'GameTimeDisplay' will be the observers

The time display UI and entities will be logged in the in the new class as observers and `TimeController`  will notify the observer to call their corresponding `update()` functions. The time display UI  will need to be updated so that it can update the time indicator and text to correspond to the current time in game. 

Entities should be stored in a list or array, and should have the ability to add to remove them from the list or array. This will require add() and remove() functions. This functionality will likely be used in later sprints when plants need to be updated with the time so that there growth is updated.

Other functionality will also be implemented so that future features can be easily implemented. This includes getter methods for the current hour in the game, or current time in the day in milliseconds or seconds, as well as a pause and unpause function. A setTime function could also be implemented for debugging and testing.

# **Dependencies**
- https://github.com/UQcsse3200/2023-studio-1/issues/10
- https://github.com/UQcsse3200/2023-studio-1/issues/69
- https://github.com/UQcsse3200/2023-studio-1/issues/41
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Create the observable class `TimeController` and define basic functions and variables
- [x] Step 2: Link the observers to the observable class. Add a `GameTimeDisplay` observer and a list or array of entities
- [x] Step 3: Implement logic to determine the current hour of the game in the updateDisplay() method of `TimeController`. In this function also call the update() function in `GameTimeDisplay`. Ensure that the UI updates every 30 seconds, as 12 minutes of real time is a whole day in the game, hence every hour is 30 seconds.
- [x] Step 4: Implement the `add()`, `remove()` and `update()` functions for the entities
- [x] Step 5: Implement the addition features 

**Completion Deadline:** Aug. 27
 
# **Documentation**
- https://github.com/UQcsse3200/2023-studio-1/wiki/Time-System
 
# **Member**
- Daniel Cottrell (@daniel-cottrell) (Daniel Cottrell)
- Manav Trivedi (@ManavTriv) (Manav Trivedi)
- Gil Wise (@gilgilgilgilgil) (Gil)
-
