### ISSUE TITLE
Validation - User Testing of Alien Fauna and Overall Gameplay

### ISSUE THREAD

**Issue by 27abdullah** [UQcsse3200/2023-studio-1#714]
# **Description**
User testing is an important validation activity in game development that can be used to inform design decisions and improve the overall quality of the game. User testing will be conducted to leverage user feedback to identify the changes that need to be made regarding design, game mechanics and usability in order to make the game as fun as possible for players. The testing will focus on the alien fauna features and the overall gameplay.

## **Examples (optional)**
- **Part/Feature**: Depending on the ticket, you will often want to provide some examples of how it would play out in the game. See next point for example...
- **map seed**: maps can be generated from a "seed" where there may be different attributes, e.g. island, mainland, etc.

# **Milestones**
- [x] Methodology (Oct. 12)
- [x] Find participants for test (Oct. 13)
- [x] Conduct test and collect data (Oct. 14)
- [x] Discussion (Oct. 15)
- [x] Act on code improvements (Oct. 16)

**Completion Deadline:** Oct. 16

# **Documentation**
- [User testing](../wiki/Validation-‐-User-Testing-of-Alien-Fauna-Features-and-Overall-Gameplay)
- [Data collection template](../wiki/Validation-‐-User-Testing-Template-for-Think‐Aloud-and-SUS#think-aloud-template)

# **Members**
- Abdullah Badat (@27abdullah) (Abdullah)
- Braden Bowie (@Bradbowi) (Braden)
