### ISSUE TITLE
Implementation of intro animation

### ISSUE THREAD

**Issue by gilgilgilgilgil** [UQcsse3200/2023-studio-1#735]
# **Description**
A cutscene-esque animation to give the game context. Information will be given to the player through a star-wars like text on screen with stars in the background to give the impression of being in space.  A crash scene is also to be added which will bea first person view from a cockpit of the player crashing into the planet.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Intro screen created (Date)
- [x] Intro text displaying (Date)
- [x] Planet coming into view animation with text (Date)
- [x] Implement continue button to progress to next screen. (Date)
- [x] Crash animation cockpit view and add button to move to next screen (Player 'awakens') (Oct 15.)

**Completion Deadline:** Oct 17th

# **Extras**
- [x] Sound effects for crash.

# **Documentation**
- [Storyline](https://github.com/UQcsse3200/2023-studio-1/wiki/Storyline)

# **Members**
- Name (GitHub Username) (Slack Handle)
- Gil (@gilgilgilgilgil) (Gil)
- Arjun (arj-sng)
