### ISSUE TITLE
Recipe JSON Creation

### ISSUE THREAD

**Issue by Joanna-Wang105** [UQcsse3200/2023-studio-1#752]
# **Description**
**Task:** [JSON creation and loading/parsing to the factory](#3).
**Feature:** [Food Recipes](#9)

Creating a JSON file that includes all the recipe, loading and parsing it into the Factory, and create a cooking config that include all the variables from the JSON file
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create JSON file and adding recipe into that file (Aug. 23)
- [ ] Load into Factory(Aug. 23)
- [ ] Save data into the Config file (Aug. 23)
 
**Completion Deadline:** Aug. 23
 
# **Member**
- Joanna Wang @Joanna-Wang105 
- Daleela Hanna Khairil @daleelakhairil

**Comment by Joanna-Wang105** [comment]
close ticket
