### ISSUE TITLE
Tile System

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#8]
# Description
This ticket is for the game's tile system. The world for this game will be made up of repeating square-shaped images (tiles). Additionally, as this game heavily revolves around farming, the player must be able to change the game world around them, therefore, the player must have the ability to interact with these tiles. As players will have the ability to place plants on these tiles, the tile must hold the information that is relevant to the plant, but not information about the plant itself (eg: water level, soil quality). Additionally, players must also be able to change the ‘state’ of the tile/crop (eg: normal ground, tilled soil, planted soil, etc.) through interactions with tools in the game.

An aim of this system is to be flexible so that it limits coupling between components with the ECS, also allowing easy integration between the game’s future tooling system (eg: hoe, watering can, etc.), save/load system, complex plant behaviours within the farming system and any other future features.

## Sub-Features
- `CropTileComponent` which stores useful information for growing crops on the tile (such as water content, soil quality, and fertiliser/plant food content), allows for the player to affect a selection of these parameters, allows for the player to plant and harvest crops
- A factory responsible for the creation of crop tile entities placed on the terrain holding the aforementioned `CropTileComponent`
- `CropTileConfig` storing all of the default crop tile data (eg: `soilQuality`, `waterLevel`, etc.)
- Tile sprites that will be used to visually represent a crop tile

## Examples
- When a player attempts to till a spot of land which is unoccupied, an entity is spawned containing a `CropTileComponent` (the position of this entity will be based off of the terrain map’s cell coordinates)
- Tiles have certain properties, such as water content, soil quality, and whether or not the soil has plant food or fertiliser. All of these properties will be used to calculate a flat growth rate modifier, which will affect the speed with which crops grow, and (possibly) their quality (depending on how plants are implemented)
- The player can affect the tile’s properties with tool interactions (e.g., watering a tile, placing fertiliser, increasing soil quality etc.)
# Dependencies
While our extensions to the game system are largely not dependent on the features of other teams, the implementation of many teams’ features is dependent on our implementation of the tile system. Here are the teams with which we will likely require the most communication and collaboration:
- **Team 1** - #7  - we will need to communicate with this team to understand the implementation of the system to place objects/till soil on the terrain, and change tile state
- **Team 3** - #11  - we will need to communicate with this team to reach common ground on how the `TerrainComponent` should be modified and how that may interface with their plans to extend the map generation system
- **Team 6** - #20  - we will need to communicate with this team to discuss what information the `CropTileComponent` contains that is relevant to plant growth and quality. We will need to reach a consensus on how plants should be spawned in the world in relation to the tile components

# Milestones
- [x] Create `CropTileComponent` to handle interactions with planting and modifying soil quality
	- [x] Creating documentation in the wiki
	- [x] Add unit testing in the test directory for the added class
	- [x] Create the component
	- [x] Add Javadocs
- [x] Create `TerrainCropTileFactory` which spawns an entity with a `CropTileComponent` to allow the player to interact with crop tiles
	- [x] Create documentation in the wiki
	- [x] Add unit testing in the test directory
	- [x] Fully implement factory
	- [x] Add Javadocs
- [x] Create custom crop tile sprites to use in `TerrainCropTileFactory` to be used by the renderer component of the created entities to represent the different tile states
- [x] Create `CropTileConfig` which contains basic stats about crop tiles
- [x] Develop tile system wiki to better convey the workings of the system to the other teams

# Extras

- Soil degradation through successive planting and harvesting of crops
- Dynamic water level decreases with game’s time system and type of plant accompanying tile
- Create planter-boxes and other entities which are placeable on the terrain
- Visuals to indicate which grid cell the player can interact with
# Documentation
- [Tile System](https://github.com/UQcsse3200/2023-studio-1/wiki/Tile-System)
- [Terrain](https://github.com/UQcsse3200/2023-studio-1/wiki/Terrain)

# Members
- Charlotte (@charliebkw) (Charlotte Birkinshaw) 
- David (@DonghyugDavidJeong) (Donghyug David Jeong)
- Lucas (@lucashicks1) (Lucas Hicks)
- Shristi (@shristigupta1408) (Shristi Gupta)
- Tom (@Tom-Strooper) (Tom Strooper)

**Comment by lucashicks1** [comment]
Feature ticket has been adjusted to better suit the current implementation of the tile system.

**Comment by lucashicks1** [comment]
Reopening as system is still being worked on (initial pull request was just for base functionality)

**Comment by lucashicks1** [comment]
Closed as complete
