### ISSUE TITLE
Extend TerrainComponent

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#9]
# **Task Description**
**Task:** Extend TerrainComponent
**Feature:** #8 

Extends `TerrainComponent` (#TODO JavaDoc link) allowing the player to place objects and till soil in unoccupied spaces on the terrain. As a result, the 'TerrainComponent' is responsible for listening to the player's actions and call the appropriate factories. Instead of creating an 'interaction' layer on top of the 'visual' tile layer, the decision was made extend the `TerrainComponent` to avoid confusion with other teams. Additionally, it is planned that 'interactive' tiles are only created when a user needs them to reduce complexity. 

# **Dependencies**
The implementation of this task is reliant on the completion of the various entity factories.

- [ ] `TerrainEntityFactory` needs to be created - #16
- [ ] `TerrainCropTileFactory` needs to be created - #18 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create documentation in the wiki (Aug. 19)
- [ ] Add unit testing in the test directory for added methods (Aug. 20)
- [ ] Modifying class (Aug. 22)
- [ ] Add to Javadocs (Aug. 23)
 
**Completion Deadline:** Aug. 24

# **Documentation**
- [Feature description](https://github.com/UQcsse3200/2023-studio-1/wiki/Tile-System)
- [JavaDoc](#TODO)
 
# **Member**

**Comment by lucashicks1** [comment]
Reopen issue as still needed.
